access-control-app/project.clj, acl-lib/project.clj, bootstrap-app/project.clj, collection-renderer-lib/project.clj, common-app-lib/project.clj, common-lib/project.clj, cubby-app/project.clj, dev-system/project.clj, elastic-utils-lib/project.clj, es-spatial-plugin/project.clj, index-set-app/project.clj, indexer-app/project.clj, ingest-app/project.clj, message-queue-lib/project.clj, metadata-db-app/project.clj, mock-echo-app/project.clj, oracle-lib/project.clj, oracle-lib/src/cmr/oracle/connection.clj, orbits-lib/project.clj, project.clj, search-app/project.clj, spatial-lib/project.clj, system-int-test/project.clj, transmit-lib/project.clj, umm-lib/project.clj, umm-spec-lib/project.clj, vdd-spatial-viz/project.clj, virtual-product-app/project.clj
This change adds support for various Clojure static analysis tools.
For subprojects:
* a new profile has been added with new lein plugins for running the tools against the codebase
* new aliases have been added that conveniently wrap the longer lein commands for the new profile
For the top-level project:
* support has been added for running the most useful new static analysis commands across all projects
* note that the CI/CD script has not yet been updated to use these (depends on future code cleanup work)
Future work:
* there are pending branches which address the kibit issues
* once those are addressed, we can update the CI/CD script to run `lein kibit` at the top-level
* once we address the eastwood errors, we can add the combo command `lein lint` to the CI/CD script (which does both …
=> Feature: add static analysis

README.md, dev-system/README.md, dev-system/support/setup_local_dev.sh, oracle-lib/README.md, oracle-lib/support/install_oracle_jars.sh, project.clj
As part of the new-dev onboarding, this updates the docs.
In particular, the following were done:
* Added docs for testing
* Added docs for new static analysis features
* Added missing steps in old docs
* Updated commands for consistency
* Updated a script to be used from either the top-level (as originally documented) or from `dev-system`
* Updated READMEs with long lines to be more easily read in the terminal
=> Task: tweak docs

.gitignore, bootstrap-app/src/cmr/bootstrap/data/bulk_index.clj, bootstrap-app/src/cmr/bootstrap/services/bootstrap_service.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index_test.clj
Added fix for deleting granules by id when they are not in the 1_small_collections index.
=> CMR-3873: Added fix for deleting granules by id

common-app-lib/src/cmr/common_app/services/search/parameter_validation.clj, ingest-app/src/cmr/ingest/validation/instrument_validation.clj, ingest-app/src/cmr/ingest/validation/platform_validation.clj, search-app/api_docs.md, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, system-int-test/test/cmr/system_int_test/ingest/collection_update_test.clj
Fixes this problem by adding the exclude_collection option to searching granules by parameter: platform, sensor, and instrument.  This problem was only caught with the platform parameter, but it will be a problem for the other two as well.
=> CMR-3926 Unable to update a collection if granules do not refer to any platform

ingest-app/src/migrations/005_create_bulk_update_tables.clj
Ran the setup-oracle.sh. The ingest migration part was successful:
------------------------------------------------------------------------
Building cmr-ingest-app 0.1.0-SNAPSHOT (base,system,user,provided,dev)
------------------------------------------------------------------------
17-Apr-12 14:04:06 mbp-sxu2.edn.ecs.nasa.gov INFO [user] - Custom user.clj loaded.
migrations.001-create-quartz-tables up...
migrations.002-create-provider-acl-hash-table up...
migrations.003-update-provider-acl-hash-table up...
migrations.004-update-quartz-to-2-2-2 up...
migrations.005-create-bulk-update-tables up...
=> CMR-3968: Added the bulk update tables.

bootstrap-app/src/cmr/bootstrap/config.clj, ingest-app/src/cmr/ingest/api/routes.clj, search-app/README.md, search-app/dev/user.clj, search-app/project.clj, search-app/src/cmr/search/api/keyword.clj, search-app/src/cmr/search/api/routes.clj, search-app/src/cmr/search/services/acl_service.clj, search-app/src/cmr/search/services/json_parameters/conversion.clj, search-app/src/cmr/search/services/query_execution.clj, search-app/src/cmr/search/services/query_service.clj, search-app/src/cmr/search/services/tagging_service.clj, search-app/src/cmr/search/site/routes.clj, search-app/src/cmr/search/system.clj, search-app/src/cmr/search/web/routes.clj, search-app/test/cmr/search/test/api/routes.clj, search-app/test/cmr/search/test/site/routes.clj, search-app/test/cmr/search/test/web/routes.clj
This is part of the CMR-3988 feature work (adding landing pages to the search-app). 
In particular, it: 
* separates `api` routes from `site` routes
* adds a new `web` namespace for combining these two
* moves the handlers to that new namespace (which is also the new namespace used when setting up the web server)
In the next change set, the number of routes in the new `site` namespace will increase, making the need for the separation even more clear.
=> Task: split out site and api routes

search-app/src/cmr/search/web/routes.clj, search-app/test/cmr/search/test/web/routes.clj
There was an error in the regex that could lead to false positives. Added two test cases that triggered the error then fixed the regexes to prevent the issue.
=> Fixed regex for find-query-str-mixed-arity-param and added test.

common-app-lib/src/cmr/common_app/api_docs.clj, search-app/docs/api.md, search-app/docs/site.md, search-app/project.clj, search-app/resources/templates/base.html, search-app/resources/templates/directory-links.html, search-app/resources/templates/eosdis-directory-links.html, search-app/resources/templates/index.html, search-app/resources/templates/provider-tag-landing-links.html, search-app/resources/templates/search-docs-static.html, search-app/resources/templates/search-docs.html, search-app/resources/templates/structure.html, search-app/src/cmr/search/site/data.clj, search-app/src/cmr/search/site/pages.clj, search-app/src/cmr/search/site/routes.clj, search-app/src/cmr/search/site/static.clj, search-app/src/cmr/search/site/util.clj, search-app/test/cmr/search/test/site/routes.clj, system-int-test/test/cmr/system_int_test/search/collection_directory_pages_test.clj
This change adds support for EUI styling in the CMR Search pages, including the static documentation pages.
The static docs are still generated using `cmr.common-app.api-docs` but with the new CMR Search Selmer templates. In order to do this, `api-docs/generate` needed to be refactored to allow for overriding the default HTML generation.
Note that since `common-app` has changed (`search-app` now expects the presence of some new functions in `common-app`), you will need to reinstall local jars: `lein modules do clean, install, clean`.
=> Task: CMR-4075 EUI for CMR Search pages

search-app/docs/api.md, search-app/src/cmr/search/api/routes.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, search-app/src/cmr/search/services/query_service.clj, system-int-test/src/cmr/system_int_test/utils/search_util.clj, system-int-test/src/cmr/system_int_test/utils/url_helper.clj, system-int-test/test/cmr/system_int_test/search/deleted_collections_search_test.clj
To support metadata harvesting, a harvesting client can search CMR for collections that are deleted within a time period. The only search parameter supported is `revision_date` and its format is the same as the `revision_date` parameter in regular collection search. The only supported result format is xml references. The response is the references to the highest non-tombstone collection revisions of the collections that are deleted within the given revision date period.
=> Added deleted-collections endpoint for harvesting client

umm-spec-lib/src/cmr/umm_spec/test/iso19115_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso19115_2.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso19115_2/data_contact.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso19115_2/data_contact.clj, umm-spec-lib/test/cmr/umm_spec/test/generate_and_parse.clj
Map contacts from the citedResponsibleParty path and do not drop contacts with an organization that does not have a corresponding data center.
=> CMR-3849 and CMR-3950 Additional data center and contact person iso mappings

search-app/docs/api.md, search-app/src/cmr/search/services/parameters/parameter_validation.clj, system-int-test/test/cmr/system_int_test/search/deleted_collections_search_test.clj
We only returning the highest revision of the deleted collections with the deleted-collections endpoint after a given date. This PR enforces the revision date validation to make sure that clients can't submit revision date ranges like in the regular search.
=> CMR-3999: Added revision date format validation and updated api doc.

dev-system/src/cmr/dev_system/system.clj, ingest-app/src/cmr/ingest/api/ingest.clj, ingest-app/src/cmr/ingest/config.clj, ingest-app/src/cmr/ingest/data/bulk_update.clj, ingest-app/src/cmr/ingest/data/ingest_events.clj, ingest-app/src/cmr/ingest/data/memory_db.clj, ingest-app/src/cmr/ingest/services/bulk_update_service.clj, ingest-app/src/cmr/ingest/services/event_handler.clj, ingest-app/src/cmr/ingest/system.clj, mock-echo-app/src/cmr/mock_echo/client/echo_util.clj, system-int-test/src/cmr/system_int_test/utils/ingest_util.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_endpoint_test.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_flow_test.clj
Implement ingest queueing for bulk update - this includes adding a new queue and exchange to ingest.
First, create rows in the status tables and get the task id that we can return to the user. Queue a bulk update event that queues individual bulk update events for each concept-id to be updated.
Currently all the bulk update event does is set the status to complete. The actual update is coming in another ticket, this is to get the flow working.
I also replaced all the endpoint dummy data with actual data from the db. I removed tests related to the dummy data and added a new test file testing the overall flow setting statuses to complete.
=> Cmr 3971 - Bulk Update Queueing

search-app/resources/templates/search-eosdis-directory-links.html, search-app/src/cmr/search/site/data.clj, search-app/test/cmr/search/test/site/data.clj, system-int-test/test/cmr/system_int_test/search/collection_directory_pages_test.clj
@chris-durbin provided some feedback after the initial deployment of the landing pages and sitemap features. Changes include:
* Alphabetical listing of providers
* Providers with no landing pages aren't linked
* All providers get a parenthetical count of landing pages after their link
Note that this branch is part 1 of 2; the second branch will include UX fixes for layout.
=> CMR-4090 Deployment fixes for landing pages directory

README.md, bootstrap-app/src/cmr/bootstrap/data/virtual_products.clj, bootstrap-app/src/cmr/bootstrap/services/health_service.clj, bootstrap-app/src/cmr/bootstrap/services/replication.clj, bootstrap-app/src/cmr/bootstrap/system.clj, common-app-lib/src/cmr/common_app/api/routes.clj, common-app-lib/src/cmr/common_app/cache/cubby_cache.clj, common-app-lib/src/cmr/common_app/services/search/datetime_helper.clj, common-app-lib/src/cmr/common_app/services/search/messages.clj, common-app-lib/src/cmr/common_app/services/search/parameter_validation.clj, common-app-lib/src/cmr/common_app/services/search/query_execution.clj, common-app-lib/src/cmr/common_app/services/search/query_to_elastic.clj, dev-system/src/cmr/dev_system/system.clj, dev-system/src/cmr/dev_system/tests.clj, dev-system/support/build.sh, dev-system/support/setup_local_dev.sh, spatial-lib/src/cmr/spatial/arc.clj, spatial-lib/src/cmr/spatial/geodetic_ring.clj, spatial-lib/src/cmr/spatial/line_segment.clj, spatial-lib/src/cmr/spatial/lr_binary_search.clj, spatial-lib/src/cmr/spatial/math.clj, spatial-lib/src/cmr/spatial/ring_relations.clj, spatial-lib/src/cmr/spatial/serialize.clj, spatial-lib/src/cmr/spatial/test/generators.clj, spatial-lib/src/cmr/spatial/tile.clj, transmit-lib/src/cmr/transmit/echo/rest.clj, transmit-lib/src/cmr/transmit/metadata_db2.clj
This work returns to one of several on-going tickets whose focus is cleaning up old code.
Additionally, the following was done:
* Updated "Testing" section in README to demonstrate usage of `(reset :db :external)`
* Updated setup scripts to use new top-level alias
* Updated setup scripts to do documentation generation after install (in the same step)
=> CMR-4036 kibit fixes

common-lib/src/cmr/common/concepts.clj, metadata-db-app/README.md, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/tag_association_save_test.clj, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/tag_save_test.clj, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/variable_save_test.clj, metadata-db-app/int_test/cmr/metadata_db/int_test/utility.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concept_tables.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/variable.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/search.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, metadata-db-app/src/cmr/metadata_db/services/concept_validations.clj, metadata-db-app/src/cmr/metadata_db/services/messages.clj, metadata-db-app/src/cmr/metadata_db/services/search_service.clj, metadata-db-app/src/migrations/048_setup_variables_table.clj, metadata-db-app/test/cmr/metadata_db/test/services/concept_service.clj
Variable concepts are system level concepts and this added db migration to create the CMR_VARIABLES table and added support to save Variable concept in the table. I have added the CREATED_AT column in CMR_VARIABLES table, but didn't add any special handling of it between revisions. It will be added after CMR-4000 is done which is setting up a framework for doing that.
=> CMR-4013: Added support to metadata-db to save a Variable concept. 

metadata-db-app/src/migrations/038_add_indices_to_tag_associations_table.clj, search-app/docs/api.md, search-app/src/cmr/search/api/tags_api.clj, search-app/src/cmr/search/services/tagging_service.clj, system-int-test/src/cmr/system_int_test/utils/tag_util.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index_test.clj, system-int-test/test/cmr/system_int_test/search/tagging/collection_revisions_tag_search_test.clj, system-int-test/test/cmr/system_int_test/search/tagging/enable_disable_test.clj, system-int-test/test/cmr/system_int_test/search/tagging/tag_acl_test.clj, system-int-test/test/cmr/system_int_test/search/tagging/tag_association_collection_revisions_test.clj, system-int-test/test/cmr/system_int_test/search/tagging/tag_association_test.clj, transmit-lib/src/cmr/transmit/tag.clj
This PR has no real code change except added logging and fixed typos. The logging is added so that we can monitor tagging request better.
=> CMR-4105: Added logging for tagging requests; Fixed typo.

search-app/src/cmr/search/services/humanizers/humanizer_report_service.clj, system-int-test/test/cmr/system_int_test/search/collection_directory_pages_test.clj, system-int-test/test/cmr/system_int_test/search/collection_humanized_search_test.clj
This is important for troubleshooting in production.
I'm not yet convinced that this job is running as expected in AWS deployments. When I hit a deployment URL for the report this morning, it look a long time to get the download data; this should not have happened. The report data should have already been made available in the cache and thus downloaded immediately. It seems that the initial request I made today was what generated the report, indicating that the report did not generate upon post-deployment startup of CMR.
Fortunately, it did cache and my next request was immediate. However, I do have concerns about the job execution and would like to check ElasticSearch after deployments to ensure that it is running as a properly scheduled job.
=> CMR-3529 Added logging for when the report generator runs as a job.

ingest-app/resources/bulk_update_schema.json, ingest-app/src/cmr/ingest/data/bulk_update.clj, ingest-app/src/cmr/ingest/data/memory_db.clj, ingest-app/src/cmr/ingest/services/bulk_update_service.clj, ingest-app/src/cmr/ingest/services/ingest_service.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_endpoint_test.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_flow_test.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj, umm-spec-lib/src/cmr/umm_spec/field_update.clj, umm-spec-lib/test/cmr/umm_spec/test/field_update.clj
This is another part of CMR-3965. Put in the framework to bulk update collections through umm conversion, save to metadata db, and report errors. This is not going to handle every bulk update case, but right now focusing on science keywords as that is the main use case and goal of this PI. I will have another PR coming for this ticket with more fields to bulk update.
=> Cmr 3965 umm update

access-control-app/src/cmr/access_control/system.clj, dev-system/dev/user.clj, ingest-app/src/cmr/ingest/system.clj, search-app/src/cmr/search/system.clj, transmit-lib/src/cmr/transmit/config.clj
It seems that the last attempt to fix this bug was only a partial success: the ingest application is now using the same public conf set as the other apps and a little bit more configuration data has made it into the base url for the ingest app. Sadly, `cmr.ingest.system/public-conf` did not set the host and port (though it did set the protocol/scheme). Instead of the old value of `null://null:null` we are now getting `http://null:null`. 
In order to address that, there are two steps necessary:
1. the new ingest config data in this PR
1. an update to the ingest config overrides in the configuration service for CMR
With both of those changes, we *should* see this further updated to the full `https://cmr.sit.earthdata.nasa.gov:443` when this gets rolled out to SIT.
Updates:
* Brought …
=> CMR-4132 - Attempt to fix ingest application public root URL again

transmit-lib/src/cmr/transmit/humanizer.clj
There's a bug with clj-http.client that brings back non-English characters correctly when decompressing gzip. 
We can't upgrade clj-http at the moment because the newer versions of clj-http cause problems with our parameter parsing, so Chris and I determined this was an acceptable workaround.
I am going to write another ticket to explore other places in our code where this may be occurring. Through normal curl everything is fine.
=> CMR-4117 Humanizers not showing non-english characters correctly

search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/query_execution.clj, search-app/src/cmr/search/services/query_execution/facets/facets_v2_results_feature.clj, search-app/src/cmr/search/services/query_walkers/facet_condition_resolver.clj, system-int-test/test/cmr/system_int_test/search/facets/collection_facets_v2_search_test.clj
This fixes Organizations v2 facets so that data center searches don't affect the returned Organizations facets.
=> CMR-4111: Fixed v2 facets for Organizations.

common-lib/src/cmr/common/concepts.clj, metadata-db-app/README.md, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/tag_association_save_test.clj, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/variable_association_save_test.clj, metadata-db-app/int_test/cmr/metadata_db/int_test/utility.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concept_tables.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/collection.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/granule.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/group.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/service.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/tag.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/tag_association.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/variable_association.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/search.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, metadata-db-app/src/cmr/metadata_db/services/concept_validations.clj, metadata-db-app/src/cmr/metadata_db/services/messages.clj, metadata-db-app/src/cmr/metadata_db/services/search_service.clj, metadata-db-app/src/migrations/050_setup_variable_associations_table.clj
This is part 1 of a four-parter for creating variable associations with collections:
1. Add creating variable association concept in metadata-db
2. Add search of variables in metadata-db
3. Add search of variable associations in metadata-db
4. Add variable associations endpoint in search-app
=> CMR-4145: create variable association in metadata-db

metadata-db-app/README.md, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/search_test.clj, metadata-db-app/int_test/cmr/metadata_db/int_test/utility.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/search.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, metadata-db-app/src/cmr/metadata_db/services/search_service.clj
This is part 2 and part 3 of a four-parter for creating variable associations with collections:
1. Add creating variable association concept in metadata-db
2. Add search of variables in metadata-db
3. Add search of variable associations in metadata-db
4. Add variable associations endpoint in search-app
=> CMR-4145: Added search of variables and variable associations in metadata-db

ingest-app/resources/bulk_update_schema.json, ingest-app/src/cmr/ingest/api/ingest.clj, ingest-app/src/cmr/ingest/data/bulk_update.clj, ingest-app/src/cmr/ingest/data/ingest_events.clj, ingest-app/src/cmr/ingest/services/bulk_update_service.clj, ingest-app/src/cmr/ingest/services/event_handler.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_endpoint_test.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj, umm-spec-lib/src/cmr/umm_spec/field_update.clj, umm-spec-lib/src/cmr/umm_spec/util.clj, umm-spec-lib/test/cmr/umm_spec/test/field_update.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_spec_test_util.clj
This is to finish the actual bulk update for all fields required for our objective. 
The decision was recently made that when we do a bulk update to save in umm-json as the new native format, so I have tests based off of that. That's subject to change.
This PR includes:
- Implement additional bulk update fields (had science kws done before)
- Bulk update save in umm-json
- Re-index provider collections after bulk update
- Change replace functionality to merge fields provided, not completely replace
- Update bulk update to handle nested params
- Restrict bulk update to certain fields via enum
- Integration and unit tests for different update scenarios
=> Cmr 3965 umm bulk update

common-lib/src/cmr/common/api/web_server.clj
Set request log format to log timestamps the same way as our debug log. See if that addresses Splunk issue of combining distinct entries into a single event. In any case we've wanted to make this change even if it does not resolve the Splunk issue.
=> CMR-4152: Set request log format to log timestamps the same way

common-lib/src/cmr/common/api/web_server.clj
Explicitly set the time zone via configuration.
=> CMR-4152: Request logs are still logging the incorrect time in NGAP.

access-control-app/int_test/cmr/access_control/int_test/acl_search_test.clj, access-control-app/src/cmr/access_control/services/acl_search_service.clj
This pull request fixes ACL search by permitted user.  Originally it was returning ACLs with empty permission vectors.  This behavior is undesired.
=> CMR-4043 ACL search by user should not return ACLs for which the user has no permissions

common-lib/src/cmr/common/api/web_server.clj
This change is going to work as expected in Splunk. It has to...
=> CMR-4152: correct the request log time format to use 24 hour clock.

common-app-lib/resources/templates/structure.html
This is needed in order to manually submit our sitemap file for indexing. I'm only making this change on the current production release since this needs to be there for just https://cmr.earthdata.nasa.gov/search and only for a one-time verification. I've tested locally this change does not break the main page and the verification is present where needed.
=> CMR-4196: Needed to submit sitemap to Google for indexing

umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/echo10.clj
We have an additional ticket to deprecate the Orderable field in ECHO10 completely, but for now set it to false since defaulting to true causes problems in EDSC.
=> CMR-4195 ECHO10 orderable flag should be false

search-app/src/cmr/search/services/query_execution.clj, search-app/src/cmr/search/services/query_execution/facets/facets_v2_helper.clj, search-app/src/cmr/search/services/query_execution/facets/facets_v2_results_feature.clj, system-int-test/test/cmr/system_int_test/search/facets/collection_facets_v2_search_test.clj
This PR is to add example service facets in the V2 facets response to demo how EDSC can expect to retrieve service options from the CMR.
We will perform the actual integration where we can search against UMM-S records with CMR-4086.
The service options facets should only be returned in the SIT environment for now, so by default they will not be returned, but we will override that in the SIT configuration.
=> CMR-4191: Add dummy service facets to V2 facets response

ingest-app/src/cmr/ingest/api/routes.clj, ingest-app/src/cmr/ingest/api/variables.clj, ingest-app/src/cmr/ingest/services/ingest_service.clj, system-int-test/test/cmr/system_int_test/ingest/variable_ingest_test.clj
This adds delete support to UMM-Vars (ingest API).
This is based upon the branch that added update support to UMM-Vars; once that branch is merged, I will rebase this branch so that it's easier to read the diff.
=> CMR-4168 variable deletes

search-app/src/cmr/search/site/data.clj, system-int-test/test/cmr/system_int_test/search/collection_directory_pages_test.clj
This provides a fix for all deployments where the directory pages were only ever listing 10 collections. Directory page data now pulls in all collection data for each provider.
=> CMR-4216 - Make the collection data for the "search directory" unlimited in number

common-lib/project.clj, common-lib/src/cmr/common/test/runners/default.clj, common-lib/src/cmr/common/test/runners/ltest.clj, common-lib/src/cmr/common/test/runners/util.clj, common-lib/src/cmr/common/test/test_runner.clj, dev-system/dev/user.clj
This change adds support for another test runner, without affecting the current/default test runner's behaviour. A convenience function has been provided in dev-system's `user.clj` file, allowing a developer to simple call `(run-suites)` from the REPL in order to use the new test runner (note that unit tests and integration tests are put into separate suites).
These changes also will make it easier to add more (well-behaved`*`)  test runners in the future.
This PR also made the following changes:
* Moved code from the existing namespace `cmr.common.test.test-runner` to the new, more general `cmr.common.test.runners.default`. To support backwards compatibility, `cmr.common.test.test-runner` was recreated, but with aliases for all the vars it used to have.
* Moved common test runner …
=> IP Feature - Provide support for an additional test runner

search-app/src/cmr/search/api/routes.clj
In order to help troubleshoot an issue with searching collections by granules that were added within a date-range, I'd like to add some logging to make debugging other environments easier.
=> CMR-4226: Add logging to verify distinct collection-ids

metadata-db-app/src/migrations/054_catalog_item_acl_fix.clj, metadata-db-app/src/migrations/055_remove_provider_services_tables.clj, metadata-db-app/src/migrations/056_setup_services_table.clj, metadata-db-app/src/migrations/057_update_variable_name_length.clj
This PR is to fix catalog item acls with granule-applicable true but collection-applicable false, before these were being skipped in the dbmigrations 53 and 52.  Also reorders dbmigrations.
=> CMR-4252 CMR Failing to properly report collection_ids for LARC_ASDC Selected Collections Granule ACLs.

search-app/src/cmr/search/data/complex_to_simple_converters/temporal.clj, system-int-test/test/cmr/system_int_test/search/collection_temporal_search_test.clj
CMR-4103 added nested index for granule and collection search. In order to make it work, we need to re-index all the granules, which takes a long time.  So we need to break this into two parts and fix them in two different sprints.:
1. Add nested index.
2. Modify the search to make use of the new index.
CMR-4220 addresses the first part, CMR-4284 will address the second part.
=> CMR-4220: Back out the search using the new index created by CMR-4103;

access-control-app/int_test/cmr/access_control/int_test/acl_crud_test.clj, access-control-app/src/cmr/access_control/services/acl_service.clj, access-control-app/src/cmr/access_control/services/acl_util.clj, access-control-app/src/cmr/access_control/services/event_handler.clj, metadata-db-app/src/migrations/052_add_coll_ids_catalog_acls.clj, metadata-db-app/src/migrations/054_catalog_item_acl_fix.clj, system-int-test/test/cmr/system_int_test/ingest/collection_ingest_test.clj
This PR addresses:
CMR-4292 fixes pump interop, CMR-4293 fixes permitted group ids in collection index, CMR-4163 syncs entry-titles and concept-ids on acl create and update
=> CMR-4292 CMR-4293 CMR-4163

ingest-app/src/cmr/ingest/api/bulk.clj, ingest-app/src/cmr/ingest/api/collections.clj, ingest-app/src/cmr/ingest/api/core.clj, ingest-app/src/cmr/ingest/api/granules.clj, ingest-app/src/cmr/ingest/api/routes.clj, ingest-app/src/cmr/ingest/api/services.clj, ingest-app/src/cmr/ingest/api/variables.clj, ingest-app/src/cmr/ingest/services/ingest_service.clj, ingest-app/src/cmr/ingest/validation/validation.clj, system-int-test/src/cmr/system_int_test/utils/variable_util.clj, system-int-test/test/cmr/system_int_test/ingest/collection_ingest_test.clj, system-int-test/test/cmr/system_int_test/ingest/granule_ingest_test.clj, system-int-test/test/cmr/system_int_test/ingest/variable_ingest_test.clj
This added JSON schema validation to variable ingest API. Since we are moving the variable ingest API to provider routes and the create and update routes will be combined as documented in CMR-4239, I left the code refactoring that I want to do out of this PR. This simply added the ability to validate against UMM-Var JSON schema without touching the existing structure of the code.
I also filed CMR-4301 for adding the similar validation for services ingest API rather than just fixing it in this PR, as the UMM-Services schema is still in flux.
The existing UMM-Var schema clearly needs some work as it does not match the sample JSON that is provided by Simon. I have brought that to Simon's attention and it will be addressed separately. For now, I just updated our sample JSON to match the …
=> CMR-4214: Add JSON schema validation to variable ingest API

search-app/src/cmr/search/api/routes.clj
This issue is fixed, so we don't need logging anymore - I'm just removing it
=> CMR-4226 Remove logging

collection-renderer-lib/resources/collection_preview/bootstrap.rb, collection-renderer-lib/src/cmr/collection_renderer/services/collection_renderer.clj, dev-system/project.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso19115_2.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso_shared/project_element.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso_smap.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso19115_2.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_shared/project_element.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_smap.clj
1. Remove Jetty debug logging by default
2. Improve REPL startup time by preventing JRuby runtime startup from blocking (one minute 20 seconds for me)
3. Fix warnings from lein modules tasks due to project.clj named files that are not Leiningen project files.
=> IP sprint cleanup

ingest-app/docs/api.md, ingest-app/resources/bulk_update_schema.json, ingest-app/src/cmr/ingest/services/bulk_update_service.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_endpoint_test.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj, umm-spec-lib/src/cmr/umm_spec/field_update.clj, umm-spec-lib/test/cmr/umm_spec/test/field_update.clj
This PR alters bulk update.
It moves the current implementation of find-and-replace to find-and-update
It changes find-and-replace to completely replace matched values with the update value instead of merging the original value and the updated value
=> CMR-4285 Incorrect results on Find&Replace of Science Keywords when not all levels of hierarchy are specified in Find term

metadata-db-app/src/cmr/metadata_db/services/concept_service.clj
This ticket failed verification in UAT. We will need to backport to 1.75.x.
=> CMR-4169: Require the services namespace to ensure services multi-methods are loaded

system-int-test/src/cmr/system_int_test/data2/umm_spec_collection.clj, system-int-test/test/cmr/system_int_test/ingest/collection_umm_spec_validation_test.clj, umm-spec-lib/src/cmr/umm_spec/validation/umm_spec_validation_core.clj
The additional attribute parsed values were not being added for collection validation (they were being added for granule parent validation) so the parsed values were always nil and certain validations were not running because of that.
=> CMR-4045 Fix additional attribute validation for collections

system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj, umm-spec-lib/src/cmr/umm_spec/field_update.clj
This PR purpose is to fix find-and-replace and find-and-update to no longer leave duplicates in the umm it updates.
=> CMR-4285 removes dupes after find and replace and find and update

search-app/src/cmr/search/api/routes.clj, search-app/src/cmr/search/services/query_service.clj, system-int-test/test/cmr/system_int_test/search/collection_with_new_granule_search_test.clj
Standard queries were exceeding paging limits because there was the potential to return more than 100k granules within a given temporal range. Because all the initial query needs to get is a list of `collection-concept-ids`, I'm using an aggregation on that field, which allows a page size of 0 for the main query itself which will hopefully side-step this problem.
=> CMR-4330 Use aggregation search to address granule page size issue

search-app/src/cmr/search/api/routes.clj, search-app/src/cmr/search/services/query_service.clj, system-int-test/test/cmr/system_int_test/search/collection_with_new_granule_search_test.clj
I forgot to do this in my last PR. This just changes the `has-granules-created-at` parameter to be `has_granules_created_at`, which is what it should have been in the first place
=> CMR-4330 - -> _

common-lib/src/cmr/common/api/web_server.clj
from 5MB to 50MB so that large humanizer reports can be saved in cubby.
There is already a test which verifies we can successfully process a body of exactly 50MB and we reject a request with 50MB + 1 byte (cmr.common.test.api.web-server/test-max-post-size).
The only reason we have this limit is so that we can prevent invalid requests from causing OOM errors on our apps. Every app has at least a 1GB heap size so a 50MB request is not likely to cause any problems.
=> CMR-4363: Increase max request size we can accept in Jetty 

indexer-app/src/cmr/indexer/data/concepts/collection.clj, indexer-app/src/cmr/indexer/data/index_set.clj, indexer-app/test/cmr/indexer/test/data/concepts/collection.clj, search-app/src/cmr/search/data/query_to_elastic.clj, search-relevancy-test/src/search_relevancy_test/relevancy_test.clj, search-relevancy-test/src/search_relevancy_test/result_logger.clj, system-int-test/test/cmr/system_int_test/search/collection_keyword_search_test.clj
We are already sorting by version for keyword search, but have run across an issue in a few cases where the version formats are mismatched (i.e. 5 vs 006) which would result in the versions not sorting correctly. I added a parsed-version-id that tries to parse to int to normalize the versions if possible.
=> Cmr 4230 - Sort by version

dev-system/dev/user.clj
When we call refresh we call stop on every component for every app
I'm guessing that `(qs/shutdown qz-scheduler true)` blocks when a job is still running?
The humanizer-report-job would run for 20 minutes if you do not have any collections in your system so your REPL would be blocked for 20 minutes.
=> CMR-4373: Fix REPL refresh

search-app/docs/api.md, search-app/src/cmr/search/api/routes.clj, system-int-test/test/cmr/system_int_test/search/variable/concept_retrieval_test.clj
The second phase of the CMR-4369 ticket ended up being less that we had originally planned, mostly because we're going to tackle the metadata-transformer issue we ran into (with versioning the content type) when we add versioning support.
This change simply adds the `mt/umm-json` content type, adds some tests for that, and does a little cleanup.
=> CMR-4369 var concept mime type support

bootstrap-app/README.md, bootstrap-app/src/cmr/bootstrap/api/routes.clj, bootstrap-app/src/cmr/bootstrap/data/bulk_index.clj, bootstrap-app/src/cmr/bootstrap/data/bulk_migration.clj, bootstrap-app/src/cmr/bootstrap/data/migration_utils.clj, bootstrap-app/src/cmr/bootstrap/data/virtual_products.clj, bootstrap-app/src/cmr/bootstrap/services/bootstrap_service.clj, bootstrap-app/src/cmr/bootstrap/services/dispatch/core_async_dispatch.clj, bootstrap-app/src/cmr/bootstrap/services/dispatch/dispatch_protocol.clj, bootstrap-app/src/cmr/bootstrap/services/dispatch/synchronous_dispatch.clj, bootstrap-app/src/cmr/bootstrap/system.clj, bootstrap-app/src/cmr/db.clj, bootstrap-app/src/config/migrate_config.clj, dev-system/README.md
This is the first of a few pull requests for CMR-4343. There is no change in functionality as a result of this PR.
Currently we use core.async channels for queueing up work for the bootstrap application. Unfortunately this does not allow for scaling up because the queue is local to a single instance.
My goal for CMR-4343 is to at a minimum change our bulk indexing of providers to put messages on a message queue so that operations can spin up additional bootstrap instances whenever they need to reindex all the granules in the system.
So back to this PR - the purpose of this was to refactor the way we handle dispatching bootstrap work to make it easy to add a new implementation (the message queue) without worrying about breaking existing functionality.
Our integration tests always request …
=> CMR-4343: Refactor dispatching logic in bootstrap-app

mock-echo-app/src/cmr/mock_echo/client/echo_util.clj, system-int-test/src/cmr/system_int_test/utils/ingest_util.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index_test.clj
This PR fixes bulk index tests that were trying to save acls, while in external db mode
=> CMR-4336 Bulk index tests failing when saving ACLs and using Oracle

search-app/resources/public/robots.txt
under /search/concepts route.
We cannot verify this ticket in SIT or UAT because we only submit our production site for indexing in Google (obviously we don't want to direct science users looking for data to our SIT our UAT environments).
I tested with Google's robots testing tools to verify that removing the one line from robots.txt fixed the problem with loading the landing pages.
=> CMR-4379: Allow crawlers to index our collection landing pages

common-lib/src/cmr/common/api/web_server.clj, common-lib/test/cmr/common/test/api/web_server.clj
Every request submitted to any CMR application was causing a 50MB buffer to be allocated in order to validate the size of the request body was less than 50MB.
(We recently increased the max request body size from 5MB to 50MB in SIT and UAT, but that change has not made it to production). So in production we are allocating a 5MB buffer on every request.
We started seeing Java heap space errors for some apps in SIT in UAT, which can easily happen when many requests are actively validating the size of the request body in parallel.
This change is to use buffers of 512 bytes to validate the request body. If a request is larger than 512 bytes we will continue allocating additional buffers until we've read the entire body or hit 50MB and we reject the request.
I've done some performance testing …
=> CMR-4386: Use a small buffer when verifying request body sizes

README.md, common-lib/src/cmr/common/util.clj, common-lib/src/cmr/common/validations/core.clj, common-lib/src/cmr/common/validations/messages.clj, dev-system/README.md, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/collection_save_test.clj, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/variable_save_test.clj, metadata-db-app/int_test/cmr/metadata_db/int_test/utility.clj, metadata-db-app/src/cmr/metadata_db/data/concepts.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts.clj, metadata-db-app/src/cmr/metadata_db/services/concept_constraints.clj, metadata-db-app/src/cmr/metadata_db/services/messages.clj, metadata-db-app/src/migrations/062_add_variable_constraint.clj, search-app/test/cmr/search/test/services/tagging/tag_validation.clj, system-int-test/test/cmr/system_int_test/ingest/collection_ingest_test.clj, system-int-test/test/cmr/system_int_test/ingest/granule_ingest_test.clj, system-int-test/test/cmr/system_int_test/ingest/variable_ingest_test.clj
The primary purpose of the changes in this PR is to add a constraint that will improve fine-grained permissions on variables. In particular, we previously had no check in place for attempting to create a variable with the same variable name and provider id but different native-id from one that already exists in the db.
Additionally, this PR has:
* made updates for better organization of various messages into the proper namespace(s)
* added another variable integration test
* updated testing sections of a couple README files
=> CMR-4350 fine tune var perms

bootstrap-app/src/cmr/bootstrap/config.clj, bootstrap-app/src/cmr/bootstrap/data/message_queue.clj, bootstrap-app/src/cmr/bootstrap/services/bootstrap_service.clj, bootstrap-app/src/cmr/bootstrap/services/dispatch/core.clj, bootstrap-app/src/cmr/bootstrap/services/dispatch/impl/async.clj, bootstrap-app/src/cmr/bootstrap/services/dispatch/impl/message_queue.clj, bootstrap-app/src/cmr/bootstrap/services/dispatch/impl/sync.clj, bootstrap-app/src/cmr/bootstrap/services/dispatch/message_queue_dispatch.clj, bootstrap-app/src/cmr/bootstrap/system.clj, dev-system/src/cmr/dev_system/system.clj, ingest-app/src/cmr/ingest/config.clj, ingest-app/src/cmr/ingest/data/ingest_events.clj, message-queue-lib/src/cmr/message_queue/config.clj, message-queue-lib/src/cmr/message_queue/queue/sqs.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index_test.clj
This pull request moves the bootstrapping of providers to a message queue.
The message queue is configured to allow messages to take up to 12 hours before considering them failed and to not ever retry a message. This will effectively allow operations to distribute messages for indexing providers across several nodes. Even if a message takes several days to process (like indexing all the granules for LPDAAC_ECS), the node that is processing that message will not attempt to pick up any other messages (listener count is set to 1). By not retrying we ensure that after 12 hours we don't have another bootstrap node kick off indexing for LPDAAC_ECS. The only downsides are that long messages will eventually move to the dead letter queue and the number of in flight messages on the message queue …
=> CMR-4343: Change provider bootstrapping to use message queue

collection-renderer-lib/project.clj
This corresponds to the changes for schema.org DownloadUrl tags
0ad880b09ce
=> CMR-4389 - updated version of preview gem

indexer-app/src/cmr/indexer/data/concepts/granule.clj, indexer-app/src/cmr/indexer/data/index_set.clj, search-app/src/cmr/search/data/complex_to_simple_converters/temporal.clj, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/query_execution/temporal_conditions_results_feature.clj
No longer index to temporals for granules, update temporal search to have conditions for granules. This fixes granule performance issues.
=> CMR-4397 don't use :temporals for granule search

metadata-db-app/int_test/cmr/metadata_db/int_test/delete_provider_cascading_test.clj, metadata-db-app/src/cmr/metadata_db/data/memory_db.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/providers.clj
We are cleaning up variables as part of the `reset` endpoint, just not in the `reset-providers` function call. MMT local dev is using the `reset-providers` function to help with the cleanup. This just added the two lines already in concept reset to the `reset-providers` function. I don't think it is worth a test, so none included.
=> CMR-4418: Clean up all variables as part of resetting providers function

bootstrap-app/README.md, common-lib/src/cmr/common/concepts.clj, search-app/src/cmr/search/api/routes.clj, search-app/src/cmr/search/api/tags.clj, search-app/src/cmr/search/api/variables.clj, search-app/src/cmr/search/services/query_walkers/provider_id_extractor.clj, system-int-test/src/cmr/system_int_test/utils/variable_util.clj, system-int-test/test/cmr/system_int_test/ingest/provider_ingest_permissions_test.clj, system-int-test/test/cmr/system_int_test/search/acls/collection.clj, system-int-test/test/cmr/system_int_test/search/acls/granule.clj, system-int-test/test/cmr/system_int_test/search/acls/temporal_collection_granule.clj, system-int-test/test/cmr/system_int_test/search/acls/variable_association.clj
We're moving from system-based to provider-based, just like we did for variables themselves. We didn't do this originally, since variable associations aren't directly linked to providers, but the difference of permissions has been difficult for OPS and MMT.
~~Note that no system integration tests existed specifically for the `system-object` ACL for variables associations, so this change didn't cause any tests to fail. Liu and I have chatted about some tests we can add -- I'm working on that now and will push to this branch when something's in place.~~
Tests for variable association ACLs are now in place.
=> CMR-4370 Change variable association provider ACL

umm-spec-lib/src/cmr/umm_spec/migration/version_migration.clj, umm-spec-lib/src/cmr/umm_spec/test/dif10_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/echo10_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/iso19115_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/iso_smap_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/characteristics_data_type_normalization.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/dif10.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/echo10.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_shared/characteristics_and_operationalmodes.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version_migration.clj
This is doing some cleanup after the merge for CMR-3366 
1. Moved the characteristics_data_type_normalization.clj from migration folder to xml_to_umm_mappings directory.
2. Removed the when-let [datatype (:DataType characteristics}] guard and clean up the code so that it won't produce any nil characteristics in the characteristics array.
=> Cmr 3366 change string to enum for data type cleanup

umm-spec-lib/resources/json-schemas/collection/umm/v1.10/umm-cmn-json-schema.json, umm-spec-lib/src/cmr/umm_spec/migration/version_migration.clj, umm-spec-lib/src/cmr/umm_spec/spatial_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/dif10_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/echo10_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/iso19115_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/iso_smap_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/dif10/spatial.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/echo10/spatial.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso19115_2/spatial.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso_smap.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/dif10/spatial.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/echo10/spatial.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso19115_2/spatial.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_smap.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_smap/spatial.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version_migration.clj
There is still some cleanup that needs to be done (mostly just moving stuff into an iso-shared/spatial.clj file), as well as a rebase but I wanted the chance to get eyes on this
=> CMR-3365 Convert VerticalSpatialDomainType to an enum

common-lib/src/cmr/common/util.clj, umm-spec-lib/resources/json-schemas/service/umm/v1.0/umm-cmn-json-schema.json, umm-spec-lib/resources/json-schemas/variable/umm/v1.0/umm-cmn-json-schema.json, umm-spec-lib/src/cmr/umm_spec/migration/version_migration.clj, umm-spec-lib/src/cmr/umm_spec/spatial_conversion.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version_migration.clj
This adds the TilingIdentificationSystem and VerticalSpatialDomain Enums to the UMM Var and Service common schema, as well as validate incoming data insensitive to case
=> CMR-3365 update var and service schemas, add case insensitivity

access-control-app/dev/user.clj, access-control-app/int_test/cmr/access_control/int_test/fixtures.clj, common-lib/project.clj, common-lib/src/cmr/common/test/runners/ltest.clj, common-lib/src/cmr/common/util.clj, common-lib/test/cmr/common/test/config.clj, dev-system/README.md, dev-system/dev/user.clj, dev-system/project.clj, dev-system/src/cmr/dev_system/config.clj, dev-system/src/cmr/dev_system/system.clj, dev-system/support/start-local-sqs-sns.sh, dev-system/support/stop-local-sqs-sns.sh, message-queue-lib/project.clj, message-queue-lib/src/cmr/message_queue/config.clj, message-queue-lib/src/cmr/message_queue/queue/sqs.clj, message-queue-lib/src/cmr/message_queue/services/queue.clj, message-queue-lib/src/cmr/message_queue/test/queue_broker_wrapper.clj, message-queue-lib/test/cmr/message_queue/test/queue/sqs.clj, metadata-db-app/src/cmr/metadata_db/services/util.clj, project.clj, system-int-test/test/cmr/system_int_test/search/collection_humanized_search_test.clj
This adds support to CMR for optionally running a local SQS/SNS clone (requires Docker). New features/capabilities include:
* `lein` commands to start. stop, and restart an SQS/SNS container
* configuration options that support the use of local SQS/SNS
* updates to the messaging client to support custom endpoints
* Updated docs (README) with instructions on using
Additionally:
* utility functions for examining the system environment variables
* refactoring dev system to match other services (with dedicated config ns)
* commented out two assertions in a test that was intermittently failing and opened a ticket for these
=> PI6 Hackfest: Add support for local, Docker-based SQS/SNS to CMR

umm-spec-lib/src/cmr/umm_spec/test/dif9_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/dif9/spatial_extent.clj, umm-spec-lib/test/cmr/umm_spec/test/xml_to_umm_mappings/dif9/spatial_extent.clj
SpatialCoverageType change where we should determine the SpatailCoverageType based on Horizontal, Vertical, or both types of mappings.
=> Fixing CMR-4515 intermittent test failure and fixing the DIF 9

indexer-app/src/cmr/indexer/services/index_service.clj, system-int-test/src/cmr/system_int_test/utils/variable_util.clj, system-int-test/test/cmr/system_int_test/search/variable/variable_revisions_search_test.clj
MMT found a bug that we do not update the variables all revisions index when creating a new variable to collection association.
The change is to make sure we index to both variables indexes whenever we process a variable association event.
=> CMR-4520: Fix to index variable to collection associations

dev-system/src/cmr/dev_system/control.clj, search-app/src/cmr/search/api/keyword.clj, transmit-lib/src/cmr/transmit/kms.clj
This is a potential fix for a problem MMT has been seeing with the keywords endpoints (CMR-4426). I can't reproduce CMR-4426, so I have no idea if this will change anything, but it does make sense to do regardless.
=> CMR-4527: Set UTF-8 charset in content-type header returned by keywords endpoints

ingest-app/src/cmr/ingest/services/ingest_service/service.clj
This hostfix is part of CMR-4467 (see PR #283). As soon as the tests pass, this can be merged, as it is an update to the already-merged PR.
=> CMR-4467 - Add a workaround for provider-id in services ingest until CMR-4468

system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj, umm-spec-lib/src/cmr/umm_spec/field_update.clj
FIND_AND_REMOVE should be able to remove all the found Platforms/Instruments/DataCenters/ScienceKeywords/LocationKeywords. unless it's required.
Before the fix, if you try to remove all of the platforms, it will give error saying the array is too short because it's empty. After the fix, it will just say that the Platforms is required.
Instruments and LocationKeywords are not required, so now we are able to remove all of the instruments and LocationKeywords.
=> CMR-4517: Fixed FIND_AND_REMOVE for bulkupdate.

metadata-db-app/src/migrations/065_add_service_associations_table.clj
This is simply adding a table to Metadata DB to introduce the concept of Service Associations, based off of Leo's Variable Association schema
=> CMR-4471 add Service Association migration

metadata-db-app/src/migrations/065_add_service_associations_table.clj
The migration from the previous PR created indexes that should not have been there. This simply deletes them.
=> CMR-4471: Deleted indexes that were causing migration to fail

common-lib/src/cmr/common/api/web_server.clj, indexer-app/src/cmr/indexer/services/index_service.clj
This is to prevent deleting all data in Elasticsearch from the Cubby application on deployment of the indexer application. I traced through the source code to when the clear cache calls were first added, and I don't see any reason why caches need to be cleared before and after updating the indexes.
=> CMR-4524: Do not clear out the caches when updating indexes

acl-lib/src/cmr/acl/acl_fetcher.clj, common-app-lib/src/cmr/common_app/cache/consistent_cache.clj, common-app-lib/src/cmr/common_app/cache/cubby_cache.clj, common-lib/src/cmr/common/cache/cache_spec.clj, indexer-app/src/cmr/indexer/data/collection_granule_aggregation_cache.clj, indexer-app/src/cmr/indexer/system.clj, system-int-test/test/cmr/system_int_test/common_app_cache_test.clj
I found that the previous change I made was still resulting in data being deleted from cubby because the one cache that it cleared was a consistent cache which uses cubby underneath to store a hash code. As a result I changed the design of cubby so that data can only be explicitly deleted from cubby by registering a list of keys that the caller wants to be deleted from cubby on any calls to reset on that cache.
=> CMR-4524: Fix to only delete specific keys from cubby on calls to reset

collection-renderer-lib/resources/collection_preview/collection_preview.erb, collection-renderer-lib/test/cmr/collection_renderer/test/services/collection_renderer.clj
HTML collection preview now uses the entry title of a collection for the title of the HTML page
=> CMR-4432 HTML preview title should be Entry Title

dev-system/dev/user.clj, dev-system/project.clj, search-app/project.clj, search-app/src/cmr/search/api/routes.clj
This is done in support of the EDSC team's need to develop against an API that won't be completed for several more weeks, but which they need access to sooner for their own development and testing.
The following endpoints offer an option of stubbed data:
* https://CMR-HOST/search/collections
* https://CMR-HOST/search/collections?concept_id=XXX
* https://CMR-HOST/search/concepts/XXX
Additionally:
* The responses from each are currently only in UMM-JSON format.
* The concept ID parameter may be either single-valued or multi-valued (usage for this is the same as the non-prototype API searches)
* The collection responses will always return the same collection, no matter how it is called (there is only one stubbed collection)
* The collection responses contain the new boolean fields …
=> CMR-4508 - Add stubbed collection and associated variables/services data

dev-system/project.clj, search-app/project.clj
I also removed the references in dev-system since we only need to pull them in from one place (the search application).
I deployed this branch to SIT and verified that the connection issues are fixed.
=> CMR-4508: Fix AWS SNS connection issue in by excluding clj-http versions pulled in from external libraries

metadata-db-app/src/cmr/metadata_db/config.clj
I tested `cmr.system-int-test.ingest.deleted-granules-index-test` with local SNS and SQS. The test failed before the change and passed after the change when using SNS and SQS.
=> CMR-4555: Make sure metadata-db can publish messages to the deleted tombstones granule exchange

search-app/src/cmr/search/api/concepts_lookup.clj, search-app/src/cmr/search/services/acl_service.clj, system-int-test/src/cmr/system_int_test/utils/service_util.clj, system-int-test/src/cmr/system_int_test/utils/variable_util.clj, system-int-test/test/cmr/system_int_test/ingest/service_ingest_test.clj, system-int-test/test/cmr/system_int_test/ingest/variable_ingest_test.clj, system-int-test/test/cmr/system_int_test/search/service/concept_retrieval_test.clj
Summary:
This adds the service concept as a valid type when querying the `/search/concepts` CMR resource.
Previous comment, during the WIP PR for this branch:
@ygliuvt I'm getting a null exception when running the new tests against the `/search/concepts` resource with a service concept it. I haven't been able to track down where the error is coming from. I'm wondering if something is missing from our service work for this to be supported? (i.e., another ticket) or if there's some part of the CMR that needs to be updated that produces this sort of side effect (e.g., an ACL update somewhere ... I seem to remember we did something like that with UMM-Vars ...).
=> CMR-4479 Add support for concept-id service lookup

ingest-app/docs/api.md, ingest-app/resources/bulk_update_schema.json, ingest-app/src/cmr/ingest/api/bulk.clj, ingest-app/src/cmr/ingest/data/bulk_update.clj, ingest-app/src/cmr/ingest/data/memory_db.clj, ingest-app/src/migrations/007_update_bulk_update_tables.clj, ingest-app/src/migrations/008_add_name_column_bulk_update_status.clj, system-int-test/src/cmr/system_int_test/utils/ingest_util.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_endpoint_test.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_flow_test.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj
This PR adds a name column to the bulk update status table.  That name is displayed for each task-id when status is queried.
Also, any task already in the database is migrated to have the name be the task-id.
=> CMR-4455 As a client, I would like to specify and retrieve a name identifier for bulk updates

search-app/project.clj
Total changes in other repos for this:
* PRs:
* https://github.com/cmr-exchange/sample-data/pull/4/files
* https://github.com/cmr-exchange/edsc-stubs/pull/2/files
* Additional individual commits:
* https://github.com/cmr-exchange/sample-data/commit/1c821489a1564e080cb9609f3a232327aaaae9f3
* https://github.com/cmr-exchange/edsc-stubs/commit/2a7dc0877231d907928468a36413b01061f20e0c
All of thees have been pushed to Clojars, using a version increment
=> CMR-4579 - Use the latest EDSC stubbed data with new concept-id.

search-app/project.clj, search-app/src/cmr/search/api/concepts_lookup.clj, search-app/src/cmr/search/api/concepts_search.clj
Also:
* Added explicit check for true value (now "false" header will bypass stubs).
* Forced result type for concept-lookup to be umm-json
* Forced result type for concept search to be json
* Arbitrarily set CMR-Hits and CMR-Took headers for concept search
=> CMR-4578 - Update response to provide correct data for computing cotent type

ingest-app/src/cmr/ingest/data/bulk_update.clj, ingest-app/src/migrations/009_update_bulk_status_message.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj
This PR modifies bulk update to allow for larger status messages by removing the truncation, and migrating the database column to 4000 (a size that is subject to change).  Before status messages were limited to 255 characters.
=> CMR-4553 Status detail message for Bulk Update is truncated

umm-lib/src/cmr/umm/related_url_helper.clj, umm-lib/test/cmr/umm/test/related_url_helper.clj
This PR implements case-insensitivity for granule documentation urls in OnlineResource field.
=> CMR-4549 Granule links need to search document mime-types case insensitively.

common-app-lib/resources/templates/structure.html, search-app/resources/templates/search-provider-tag-landing-links.html
Addresses issue with CMR directory pages not being mobile-friendly. I tried to avoid using bootstrap, but this is significantly cleaner/easier
=> CMR-4401: add bootstrap and make tables responsive

system-int-test/test/cmr/system_int_test/ingest/service_ingest_test.clj
This change was for an issue that was created to be sure we had our bases covered for different validation edge cases. As it turned out, we'd already added tests for two of the three in the acceptance criteria, so just one more was needed.
=> CMR-4478 service validation

system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj, umm-spec-lib/src/cmr/umm_spec/field_update.clj, umm-spec-lib/test/cmr/umm_spec/test/field_update.clj
This PR removes any duplicate values on bulk update :add-to-existing for location keywords and science keywords.
=> CMR-4570 Bulk Update 'Add to Existing' should not duplicate an existing Science or Location keyword

search-app/docs/api.md
Ran some tests and turns out the ticket is a non-issue(see my comments in the ticket https://bugs.earthdata.nasa.gov/browse/CMR-4576)The reason the "issue" was reported was the mis-interpretation of the api.  In this PR, we are attempting to clarify the case when no format is passed in, what the search response should be expected.
=> CMR-4567: Clarify Search API DOC.

umm-spec-lib/src/cmr/umm_spec/dif_util.clj, umm-spec-lib/src/cmr/umm_spec/util.clj, umm-spec-lib/src/cmr/umm_spec/validation/related_url.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/echo10/related_url.clj, umm-spec-lib/test/cmr/umm_spec/test/validation/related_url.clj
This PR address multiple validation bugs regarding RelatedURLs
SubType should be referred to as Subtype in error message
A RelatedURL of:
{ "Description": "Guide Document for this product at NSIDC-wrong1", "URLContentType": "PublicationURL", "Type": "GET RELATED VISUALIZATION", "Subtype": "THREDDS DATA", "URL": "http://nsidc.org/data/docs/daac/ae_swe_ease-grids.gd.html" }
While the ContentURLType and Type message is correct, the SubType of null is not correct. 
a RelatedURL of: 
{ "Description": "Guide Document for this product at NSIDC-wrong1", "URLContentType": "PublicationURL", "Type": "VIEW RELATED INFORMATION", "Subtype": "THREDDS DATA", "URL": "http://nsidc.org/data/docs/daac/ae_swe_ease-grids.gd.html" }
Doesn't give any warning messages - THREDDS DATA is not a valid subtype for …
=> CMR-4565 Fix the RelatedURL validation

common-app-lib/resources/public/site/css/cmr.css, common-app-lib/resources/templates/structure.html, search-app/resources/templates/search-provider-tag-landing-links.html
Bootstrap had a bunch of conflicting styles that messed with margins and positioning - this just fixes that while keeping tables relatively mobile-friendly. Behavior is the same as with bootstrap, but it's conflict free
=> CMR-4401: Remove bootstrap, force responsive tables

metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/force_delete_test.clj, metadata-db-app/int_test/cmr/metadata_db/int_test/utility.clj, metadata-db-app/src/cmr/metadata_db/api/concepts.clj, metadata-db-app/src/cmr/metadata_db/api/provider.clj, metadata-db-app/src/cmr/metadata_db/api/route_helpers.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, system-int-test/test/cmr/system_int_test/search/service/force_delete_test.clj
This adds a check to cascading deletes for service concepts as well as some more metadata-db integration tests.
I will updates services to do something similar (also adding missing tests) once this PR is reviewed.
=> CMR-4495 service force delete

common-lib/src/cmr/common/util.clj, common-lib/test/cmr/common/test/util.clj, indexer-app/src/cmr/indexer/data/concepts/collection/platform.clj, search-app/docs/api.md
1. The index error is caused by platform's short name being nil in an old collection C179003298-ORNL_DAAC revision 27.
2. Verified that the bad collection couldn't be ingested by the current code because of the nil platform short name.
3. Modified safe-lowercase, safe-uppercase because they don't work on the case when the parameter is boolean false.  Added unit tests for it.
4. Modified the search api doc to correct a grammar mistake from an earlier ticket.
=> CMR-4593: Platform parsing error during index.

message-queue-lib/src/cmr/message_queue/test/queue_broker_wrapper.clj
Matthew and I found that there was an MMT test that was creating some invalid bulk update requests for CMR that resulted in a message on the CMR message queue that could not be processed. Found a bug in our local test broker that we weren't marking a request as failed after it had failed all retries. With this change the MMT tests went from:
Before:
```
Finished in 69 minutes 45 seconds (files took 4.31 seconds to load)
1550 examples, 0 failures
```
After:
```
Finished in 22 minutes 7 seconds (files took 4.08 seconds to load)
1550 examples, 0 failures
```
Now they only spend 11 seconds total in their calls to waiting for CMR indexing to complete:
```
|    11.370s |   0.025s |   0.147s |   452 | Helpers::CmrHelper#wait_for_cmr 
```
=> CMR-4621: Make MMT tests faster

common-app-lib/src/cmr/common_app/services/search/params.clj, common-lib/src/cmr/common/util.clj, common-lib/test/cmr/common/test/util.clj, search-app/src/cmr/search/routes.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, search-app/src/cmr/search/services/query_service.clj, search-app/test/cmr/search/test/routes.clj, system-int-test/test/cmr/system_int_test/search/collection_temporal_search_test.clj, system-int-test/test/cmr/system_int_test/search/facets/collection_facets_search_test.clj, system-int-test/test/cmr/system_int_test/search/granule_search_test.clj
Acceptance Criteria for search parameter validation :
1) invalid_parameter returns a 400
2) invalid_parameter= returns a 400
3) invalid_parameter&include_facets=v2 returns 400
4) invalid_parameter=&include_facets=v2 returns 400
5) valid_parameter pretends that parameter wasn't passed in (whatever the existing behavior is)
6) valid_parameter= pretends that parameter wasn't passed in (whatever the existing behavior is)
7) valid_parameter&include_facets=v2 pretends that parameter wasn't passed in
8) valid_parameter=&include_facets=v2 pretends that parameter wasn't passed in
=> Cmr 4580 fix parameter validation new

ingest-app/src/cmr/ingest/api/bulk.clj, ingest-app/src/cmr/ingest/api/core.clj, ingest-app/src/cmr/ingest/data/ingest_events.clj, ingest-app/src/cmr/ingest/services/bulk_update_service.clj, ingest-app/src/cmr/ingest/services/event_handler.clj, system-int-test/src/cmr/system_int_test/utils/ingest_util.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj, transmit-lib/src/cmr/transmit/config.clj
Turns out bulk update and regular ingest/update are not going through the same ingest-collection function, in which the user-id is set.  
Bulk update doesn't contain the functionality to set the user id. It just makes use of the user-id from the previous revision.  This is why the regular update will set the user-id, while the bulk update just carries  on whatever the user-id is from the previous revision.
=> CMR-4622:  Added functionality to set user-id in bulk update.

common-app-lib/src/cmr/common_app/services/kms_lookup.clj, common-app-lib/test/cmr/common_app/test/services/kms_lookup.clj, dev-system/resources/kms_examples/platforms/platforms.csv, system-int-test/test/cmr/system_int_test/ingest/collection_keyword_validation_test.clj, system-int-test/test/cmr/system_int_test/search/keyword_endpoint_test.clj
In this PR, we want to prevent KMS validation on Platform LongName when the LongName is nil due to some restrictions with ECHO-10.  We still want to validate ShortName in that case.  If both LongName and ShortName are present, then the validation should work as before.
=> CMR-4400 changes platform longname and shortname validation

system-int-test/src/cmr/system_int_test/data2/umm_spec_collection.clj, umm-spec-lib/src/cmr/umm_spec/validation/umm_spec_collection_validation.clj, umm-spec-lib/test/cmr/umm_spec/test/validation/umm_spec_collection_validation_tests.clj
This PR adds validation on DOI formatting, the DOI should have a normal format of prefix/suffix where the prefix normally is dd.dddd, where d is a digit and the suffix is a string .
=> CMR-4533 implements DOI warning validation for DOI formatting

collection-renderer-lib/project.clj
This is adds the http://schema.org/identifier property to collection pages where applicable
=> CMR-4561: Update Metadata Preview gem

indexer-app/src/cmr/indexer/data/concepts/service.clj, indexer-app/src/cmr/indexer/data/index_set.clj, search-app/docs/api.md, search-app/src/cmr/search/data/query_to_elastic.clj, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, system-int-test/src/cmr/system_int_test/utils/ingest_util.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj, system-int-test/test/cmr/system_int_test/search/service/collection_service_search_test.clj
As a client, I want to search collections by its associated services through the service unique identifier.
Fixed bulk-update-science-keywords test which fails intermittently in CI and local dev env.
=> CMR-4279, CMR-4674

search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, search-app/src/cmr/search/services/query_execution.clj, search-app/src/cmr/search/services/query_execution/facets/collection_v2_facets.clj, search-app/src/cmr/search/services/query_execution/facets/facets_v2_results_feature.clj, search-app/src/cmr/search/services/query_execution/facets/granule_v2_facets.clj, search-app/src/cmr/search/services/query_walkers/facet_condition_resolver.clj, search-app/src/cmr/search/validators/validation.clj, system-int-test/test/cmr/system_int_test/search/facets/collection_facets_search_test.clj, system-int-test/test/cmr/system_int_test/search/facets/collection_facets_v2_search_test.clj, system-int-test/test/cmr/system_int_test/search/facets/granule_facets_v2_search_test.clj
This is the first step to supporting granule facets. Returns an empty facets object for the JSON format, and a 400 error when requesting v2 facets in any other format.
Subsequent tickets CMR-4681 through CMR-4687 will add the remaining functionality.
In addition to adding support for the parameter for granule searches, this PR separated out collection and granule specific logic from the main V2 facets capability so that we can reuse as much as possible from the collection V2 facets implementation when adding similar support for granules.
=> CMR-4680: Add initial support for the include_facets=v2 parameter

search-app/project.clj, search-app/src/cmr/search/api/concepts_lookup.clj, search-app/src/cmr/search/api/concepts_search.clj
This is also blocking some changes we want to make to support the local nexus jar repo in CI/CD (it can't currently handle SNAPSHOTS from Clojars).
=> CMR-4583: Removed EDSC stubbed data support for previous PI testing tasks

ingest-app/docs/api.md, ingest-app/resources/bulk_update_schema.json, ingest-app/src/cmr/ingest/services/bulk_update_service.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_endpoint_test.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj
In bulk update body, pass in :concept-ids ["ALL"] to indicate all the collections for the provider will be updated, rather than not passing any concept-ids in the previous implementation.
=> CMR-4630: Modified the indication of all collection update.

ingest-app/src/cmr/ingest/services/bulk_update_service.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_endpoint_test.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj
1. Verified that all the collections that failed the bulkupdate are the deleted collections. 
2. The error happens at spec-core/parse-metadata (xpath/context metadata) 
3. Since the deleted collections  are already excluded in the update "ALL" case, we should exclude them in individual concept-id case as well, which will get rid of the error.  Still don't understand why the error only happens on the deleted collections.
=> CMR-4708: Exclude deleted collections for bulk update.

common-app-lib/src/cmr/common_app/services/search/parameter_validation.clj, common-app-lib/src/cmr/common_app/services/search/parameters/converters/nested_field.clj, search-app/src/cmr/search/services/json_parameters/conversion.clj, search-app/src/cmr/search/services/messages/common_messages.clj, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/parameters/converters/temporal_facet.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, search-app/src/cmr/search/services/query_execution/facets/hierarchical_v2_facets.clj, search-app/src/cmr/search/services/query_execution/facets/temporal_facets.clj, search-app/src/cmr/search/services/query_service.clj, search-app/test/cmr/search/test/services/parameter_validation.clj, system-int-test/test/cmr/system_int_test/search/collection_science_keyword_search_test.clj, system-int-test/test/cmr/system_int_test/search/granule_temporal_facet_search_test.clj, system-int-test/test/cmr/system_int_test/search/variable/collection_variable_search_test.clj
`"http://localhost:3003/granules?temporal_facet[0][year]=1924&temporal_facet[1][year]=1946"` will return any granules which have starting date temporal values in the years 1924 or 1946. That's what this PR adds. I will have a subsequent PR for this ticket to construct and provide the appropriate links for temporal facets within the granule facets.
I did not update the API docs to document this search parameter because it is not intended to be used outside of facet links. For v2 facet links we explicitly state that the links are treated as opaque strings and the parameters used in those links are not guaranteed to stay from release to release.
=> CMR-4683: Add support for temporal_facet[0][year]... search parameter

dev-system/support/build.sh
This is to fix an issue that Chris as seen in the Heritage build.
=> CMR-4720: Don't use alias for building Ruby gems.

search-app/src/cmr/search/data/keywords_to_elastic.clj, search-relevancy-test/README.md, search-relevancy-test/src/search_relevancy_test/anomaly_analyzer.clj, search-relevancy-test/src/search_relevancy_test/anomaly_fetcher.clj, search-relevancy-test/src/search_relevancy_test/relevancy_test.clj, search-relevancy-test/src/search_relevancy_test/runner.clj, system-int-test/test/cmr/system_int_test/search/collection_relevancy/collection_usage_relevancy.clj
1. Added a comment to the ticket to explain why the keyword score is higher for TOMS products over OMI products: https://bugs.earthdata.nasa.gov/browse/CMR-4679
2. Added analyze-test task and modify the existing code to make it work so that we could use it to help analyzing the test failures.
3. Changed the default boost value of project to 1.0.  This change will make 2 more tests pass, including the one in this ticket, without failing any of the tests that passed previously.
=> CMR-4679: Added analyze-test task.

search-app/src/cmr/search/services/query_execution/facets/facets_v2_results_feature.clj, search-app/src/cmr/search/services/query_execution/facets/granule_v2_facets.clj, search-app/src/cmr/search/services/query_execution/facets/hierarchical_v2_facets.clj, search-app/src/cmr/search/services/query_execution/facets/temporal_facets.clj, system-int-test/test/cmr/system_int_test/search/facets/granule_v2_facets_search_test.clj
The facet response after this pull request includes links to add or remove years from the granule search. It looks like:
```
"facets" : {
"title" : "Browse Granules",
"has_children" : true,
"children" : [ {
"title" : "Temporal",
"type" : "group",
"applied" : false,
"has_children" : true,
"children" : [ {
"title" : "Year",
"type" : "group",
"applied" : false,
"has_children" : true,
"children" : [ {
"title" : "2012",
"type" : "filter",
"applied" : false,
"count" : 1,
"links" : {
"apply" : "http://localhost:3003/granules.json?page_size=0&include_facets=v2&collection_concept_id=C1-PROV1&pretty=true&temporal_facet%5B0%5D%5Byear%5D=2012"
},
"has_children" : false
}, {
"title" : "2011",
"type" : "filter",
"applied" : false,
"count" : 1,
"links" : {
"apply" : …
```
=> CMR-4683: Add navigation links to granule year facets

search-app/src/cmr/search/api/concepts_search.clj, search-app/src/cmr/search/api/core.clj, system-int-test/test/cmr/system_int_test/search/scrolling_search_test.clj
1. Issue:
If you do the following granule scroll search:
curl -i "http://localhost:3003/granules?provider=PROV&page_size=1&scroll=true"
and then do a subsequent granule scroll search using the scroll-id returned:
curl -i -H "CMR-Scroll-Id: -1261131662" "http://localhost:3003/granules?scroll=true"
The search-params with the provider=PROV info is lost for the subsequent scroll search, which results in the query search against all the indexes.  
2. Solution:
Cache the search-params together with the scroll-id in the cache and use the cached search-params if it's not nil.
3. Integration test issue:
Since the search-params doesn't affect the subsequent scroll search result, only impacts the performance, not sure how to test this. The only thing I could think of is to add the search-params to …
=> CMR-4404: Cache the search-params to improve granule scroll search performance.

umm-spec-lib/src/cmr/umm_spec/test/dif9_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/dif9.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/dif9/data_center.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/dif9.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/dif9/data_center.clj
1. The ticket asked for the removal of Originating_Center translation between UMM and DIF9, DIF10.
Turns out only there's no such translation for DIF10, so only need to remove it for DIF9.
2. We have the Originating_Center in the example_data under DIF9 and DIF10. I removed the "ORIGINATOR" DataCenter from the expected. With all that, the generate_and_parse.clj should cover all the necessary testings.
=> CMR-4648. Remove Originating_Center Translation between DIF and UMM.

common-app-lib/src/cmr/common_app/static.clj, search-app/docs/api.md
1. s/granules?/granules?collection_concept_id=%CMR-EXAMPLE-COLLECTION-ID%\&/g
2. Excluded the following cases:
a. provider search
b. short name search
c. entry title search.
d. cases where generic collection_concept_id doesn't make sense.
3. Modified static.clj to customize the collection_concept_id for each environment.
=> CMR-4705: Add constraint to all granule queries in the api doc.

common-app-lib/src/cmr/common_app/services/search/parameters/converters/nested_field.clj, common-lib/src/cmr/common/util.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, search-app/src/cmr/search/services/query_execution/facets/facets_v2_results_feature.clj, search-app/src/cmr/search/services/query_execution/facets/granule_v2_facets.clj, search-app/src/cmr/search/services/query_execution/facets/hierarchical_v2_facets.clj, search-app/src/cmr/search/services/query_execution/facets/temporal_facets.clj, search-app/test/cmr/search/test/services/parameter_validation.clj, search-app/test/cmr/search/test/services/query_execution/facets/hierarchical_v2_facets.clj, search-app/test/cmr/search/test/services/query_execution/facets/temporal_facets.clj, system-int-test/test/cmr/system_int_test/search/facets/granule_v2_facets_search_test.clj, system-int-test/test/cmr/system_int_test/search/granule_temporal_facet_search_test.clj
The facets structure now includes months after selecting a year.
```
"facets" : {
"title" : "Browse Granules",
"type" : "group",
"has_children" : true,
"children" : [ {
"title" : "Temporal",
"type" : "group",
"applied" : true,
"has_children" : true,
"children" : [ {
"title" : "Year",
"type" : "group",
"applied" : true,
"has_children" : true,
"children" : [ {
"title" : "2010",
"type" : "filter",
"applied" : true,
"count" : 2,
"links" : {
"remove" : "http://localhost:3003/granules.json?include_facets=v2&collection_concept_id=C1-PROV1&page_size=0&pretty=true"
},
"has_children" : true,
"children" : [ {
"title" : "Month",
"type" : "group",
"applied" : false,
"has_children" : true,
"children" : [ {
"title" : "05",
"type" : "filter",
"applied" : false,
"count" : 1,
"links" : {
"apply" : …
```
=> CMR-4686: Add months to temporal facets within granule V2 facets

indexer-app/src/cmr/indexer/data/elasticsearch.clj, indexer-app/src/cmr/indexer/services/index_service.clj, message-queue-lib/src/cmr/message_queue/services/queue.clj, message-queue-lib/src/cmr/message_queue/test/queue_broker_wrapper.clj, search-app/src/cmr/search/data/elastic_results_to_query_results.clj, transmit-lib/src/cmr/transmit/metadata_db.clj
Since services have associations we need to use the transaction ID when specifying the version for the Elasticsearch document that gets created. We do the same for collections, variables, and tags.
We had existing tests which failed when switching to transaction ID in one place, and then succeeded when switching to use transaction IDs everywhere.
=> CMR-4746: Fix services to use transaction ID instead of revision ID when creating and deleting services.

common-app-lib/src/cmr/common_app/services/search/parameters/converters/nested_field.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, search-app/src/cmr/search/services/query_execution/facets/granule_v2_facets.clj, search-app/src/cmr/search/services/query_execution/facets/temporal_facets.clj, search-app/test/cmr/search/test/services/parameter_validation.clj, search-app/test/cmr/search/test/services/query_execution/facets/hierarchical_v2_facets.clj, search-app/test/cmr/search/test/services/query_execution/facets/temporal_facets.clj, system-int-test/test/cmr/system_int_test/search/facets/granule_v2_facets_search_test.clj, system-int-test/test/cmr/system_int_test/search/granule_temporal_facet_search_test.clj
CMR-4685: Add has_children field to granule facets
CMR-4687: Add days to granule facets
These are the last two tickets to finish off the granule faceting capability by temporal. This adds support for days below months and makes sure the has_children field is always correctly set.
=> CMR-4685 and CMR-4687

search-app/src/cmr/search/services/query_service.clj
Testing with wget (which doesn't set a client-id):
`Found 0 collections in 6 ms from client unknown in format :xml with params {:provider "PROV1", :result-format :xml}`.
Curl with a custom header -H "Client-id: abc":
`Found 0 granules in 12 ms from client abc in format :xml with params {:provider "PROV1", :result-format :xml}`
Curl default:
`Found 0 granules in 10 ms from client curl in format :xml with params {:provider "PROV1", :result-format :xml}`
=> CMR-4745: Log the client-id in the line where we log query performance.

system-int-test/test/cmr/system_int_test/ingest/collection_misc_validation_test.clj, umm-spec-lib/src/cmr/umm_spec/validation/related_url.clj, umm-spec-lib/test/cmr/umm_spec/test/validation/related_url.clj
This PR adds validation for RelatedUrls, when the URL is present but there is no description, there should be a warning returned.
=> CMR-4620 Add validation for RelatedURL/description when it doesn't exist.

indexer-app/src/cmr/indexer/data/concepts/service.clj, indexer-app/src/cmr/indexer/data/index_set.clj, ingest-app/src/cmr/ingest/services/ingest_service/service.clj, search-app/docs/api.md, search-app/src/cmr/search/data/query_to_elastic.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, system-int-test/test/cmr/system_int_test/search/service/service_search_test.clj
1. Looks like the code change works for the sorting purpose. Not sure if I should add the service association index for the LongName for collections, just to be consistent with other sorting parameters.
2. The baseline code failed on the two tests: 
FAIL in (render-edsc-link) (collection_renderer.clj:48)
FAIL in (retrieve-collection-by-cmr-concept-id) (collection_concept_retrieval_test.clj:167)
=> CMR-4656: Allow client to search services sorted by their LongNames.

access-control-app/int-test/cmr/access_control/int_test/acl_crud_test.clj, access-control-app/src/cmr/access_control/services/acl_util.clj, access-control-app/src/cmr/access_control/services/acl_validation.clj
This PR is to address an ACL in UAT that has collections that do not exist anymore in metadata-db by have somehow been left in the ACL(the delete didn't cascade).  I haven't been able to find when the collections were deleted in splunk, my guess is that they were deleted a long ago and the tombstones are just now decaying off after 356 days. The ACL in question was last successfully modified on 2017-11-29 17:44:13.082 
The event queue logic that handles cascading collection deletions to ACLs looks solid. So it is unclear how the ACL got to this state.
I think the simplest solution is to just remove the validation.  The entry-title/concept-id sync works when updating/creating an ACL prevents any collection that doesn't exist in the provider from being added to the ACL.  We do lose the …
=> CMR-4753 Unable to update GES_DISC ACL due to unknown concept id

collection-renderer-lib/project.clj
This turned out to be so much simpler than I thought once I started reading the content of the project.clj. Basically whatever you call from the CMR root, the same command will propagate to all the subdirectories, so `lein install!` at CMR root will trigger `lein clean` `lein install` and `lein clean` in all the subdirectories... 
* Fixed `lein install!` in project.clj under collection-renderer-lib by changing the syntax of the tasks.
* Added "install" alias in project.clj under collection-render-lib so that when `lein install!` is run under CMR root, gems can be installed for collection-render-lib.  The default install task for collection-renderer-lib subdirectory does not install the gems - this is actually true for the old branch too, it only creates empty gems directory if it doesn't …
=> CMR-4768: Fixed gem install issue for collection-renderer-lib.

collection-renderer-lib/test/cmr/collection_renderer/test/services/collection_renderer.clj, indexer-app/int-test/cmr/indexer/test/services/index_fields/services.clj, indexer-app/src/cmr/indexer/data/concepts/service.clj, indexer-app/src/cmr/indexer/data/index_set.clj, search-app/docs/api.md, search-app/src/cmr/search/data/elastic_search_index.clj, search-app/src/cmr/search/data/query_to_elastic.clj, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, system-int-test/src/cmr/system_int_test/utils/service_util.clj, system-int-test/test/cmr/system_int_test/search/service/service_revisions_search_test.clj
This is the third and final PR for this ticket. Summary so far: 
1) Preparation and cleanup (see PR #455)
2) Indexing (see PR #457)
3) Search (this PR)
This PR worked on the following:
I'll push an update when the docs have been updated; it's ready for review now, though.
=> CMR-4657: Support all-revisions for services in search

search-app/docs/api.md, search-app/src/cmr/search/api/concepts_search.clj, search-app/src/cmr/search/validators/all_granule_validation.clj, system-int-test/test/cmr/system_int_test/search/all_granule_search_test.clj
For the most part, this has been reviewed and approved by Chris. Started a new branch for the following reasons:
1. Reorganized the code into smaller modules.
2. Added a validation step to reject queries with concept_id not being a granule or collection concept id.
This is an existing bug that will result in a true all granule query.
3. Added code and tests to handle the situations when parameter is passed in with a equal sign but missing a value, in both the single parameter case, and array of same parameter case.
4. Pulled the integration test out of the granule_spatial_test and created its own test.
5. Merge conflict.
Below is the original changes for the ticket:
1. Added defconfig allow-all-granule-params-flag, when set to true, all granule queries are allowed. The default value is …
=> Cmr 4752 reject all granule parameters

umm-spec-lib/resources/json-schemas/collection/umm/v1.10/umm-cmn-json-schema.json, umm-spec-lib/src/cmr/umm_spec/json_schema.clj, umm-spec-lib/src/cmr/umm_spec/models/umm_common_models.clj, umm-spec-lib/src/cmr/umm_spec/record_generator.clj, umm-spec-lib/src/cmr/umm_spec/test/echo10_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/expected_conversion_util.clj, umm-spec-lib/src/cmr/umm_spec/test/iso19115_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/iso_shared.clj, umm-spec-lib/src/cmr/umm_spec/test/iso_smap_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/umm_generators.clj, umm-spec-lib/src/cmr/umm_spec/umm_json.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso19115_2.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso_smap.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/dif9.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/echo10.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso19115_2.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_shared/doi.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_smap.clj, umm-spec-lib/test/cmr/umm_spec/test/generate_and_parse.clj
This change allows the UMM for the DOI field to be either DOI and Authority or MissingReason and Explanation. We needed to add support for field level oneOf definitions in JSON schema in order to make this work.
=> CMR-4650: Change JSON schema for DOI to support two different definitions

metadata-db-app/src/cmr/metadata_db/data/concepts.clj, metadata-db-app/src/cmr/metadata_db/data/memory_db.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/collection_table.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concept_tables.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/granule_table.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/providers.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/search.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/sql_helper.clj, metadata-db-app/src/cmr/metadata_db/services/provider_service.clj
There will be several branches/PRs for this work, so this is the first in a series of what might be 3 or 4 PRs.
Tasks completed so far:
* Evaluate current implementation of metadata-cmr API
* Document proposed changes to the API and update development tasks here
* Implement non-breaking changes, test in workload, and merge
* Convert all extend-* to just extend
* Separate methods out from records into independent functions
* Update implicit contextual references to record fields to explicit record field lookups
* Do this for in-memory DB:
* cmr.metadata-db.data.memory-db)
* Do this for Oracle:
* cmr.metadata-db.data.oracle.concepts
* cmr.metadata-db.data.oracle.providers
* cmr.metadata-db.data.oracle.search
A little more explanation about the motivation here:
There are several ways in …
=> CMR-4785: Prelinimary refactoring for Metadata-DB API cleanup

search-app/src/cmr/search/api/concepts_search.clj, system-int-test/test/cmr/system_int_test/search/all_granule_search_test.clj
=> CMR-4752: Fix issue with not being able to configure the all granules allowed header to contain capital letters.

metadata-db-app/src/cmr/metadata_db/services/jobs.clj
=> CMR-4821: Move up tag association and other system concepts cleanup ahead of provider concept table cleanup.

transmit-lib/src/cmr/transmit/metadata_db.clj
The error happens when the parsing of the html response body fails. We should catch the exception and log the first 255 characters of the body when it occurs. 
Note: This fix only involves logging, so there won't be testing for it.  Have tried to manually introduce an error and ran a demo to verify the code worked.
=> CMR-4841: Log the first 255 characters of the response body.

indexer-app/src/cmr/indexer/data/concepts/granule.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/granule_table.clj, metadata-db-app/src/migrations/066_add_default_to_created_at_in_granule_tables.clj
1. Added the migration to add the DEFAULT SYSTIMESTAMP to created_at column in granule tables. This will allow the newly ingested granules to have the created_at populated, more importantly it will be populated with the same SYSTIMESTAMP as revision_date, which is important.  Note: it allows null, so we don't have to worry about the existing rows with null values.
2. Modified the code to index on revision_date when created_at is null. This is to allow the existing granules with null created_at values to be searchable through created_at constraint.
3. Modified the granule_table.clj to remove the "not null" constraint so that the newly created tables will have the same constraint as the existing tables - Leo preferred not to change this. 
4. Testing - Not sure how to do it yet because the …
=> CMR-4824: Fixed the code that caused the search on created_at to fail.

indexer-app/src/cmr/indexer/data/concepts/keyword_util.clj, indexer-app/src/cmr/indexer/data/concepts/service.clj, indexer-app/test/cmr/indexer/test/data/concepts/keyword_util.clj, ingest-app/src/cmr/ingest/config.clj, system-int-test/src/cmr/system_int_test/data2/umm_spec_service.clj, system-int-test/test/cmr/system_int_test/search/service/service_search_test.clj, umm-spec-lib/resources/json-schemas/service/umm/v1.1/umm-cmn-json-schema.json, umm-spec-lib/resources/json-schemas/service/umm/v1.1/umm-s-json-schema.json, umm-spec-lib/resources/json-schemas/service/umm/v1.1/umm-s-search-results-json-schema.json, umm-spec-lib/src/cmr/umm_spec/migration/version/core.clj, umm-spec-lib/src/cmr/umm_spec/migration/version/interface.clj, umm-spec-lib/src/cmr/umm_spec/migration/version/service.clj, umm-spec-lib/src/cmr/umm_spec/models/umm_service_models.clj, umm-spec-lib/src/cmr/umm_spec/versioning.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version/service.clj
UMM-S Service/Access Constraints should not be repeatable as there is only one set of access constraints per collection record. Leave as plural and should be object and not array
UMM-S Service/Access Constraints: Increase Field length to 4,000 characters
UMM-S Service/Use Constraints: Increase Field Length to 20,000 characters
UMM-S Service/Use Constraints: Field Should be set as an object and not an array (not repeatable) in the schema
UMM-S Service/ServiceQuality/Lineage: Increase Field Length to 4,000 characters
MM-S Service/RelatedURL: Field Should Be Repeatable (make multiple) in schema
UMM-S Service/RelatedURL/GetService: Sub-Field Should Not Be Required
Add "TOOL" just after "THREDDS DIRECTORY" to the list of valid RelatedURLSubTypeEnum. Depending if we use the same validation as …
=> CMR-4808 adds umm s version 1.1

metadata-db-app/src/cmr/metadata_db/services/concept_service.clj
Modifies cleanup job to prevent an overlong while loop when deletion of concepts is constantly being added to by an ongoing volume of ingests.
=> CMR-4806 OldRevisionConceptCleanupJob taking multiple weeks to complete

common-app-lib/src/cmr/common_app/api/health.clj
health care in all apps are calling the cmr.common-app.api.health to do the job so I'm modifying this central place.
=> CMR-4850: Added CORS support for health checks.

search-app/src/cmr/search/services/acls/granule_acls.clj, system-int-test/test/cmr/system_int_test/search/granule_search_test.clj
This PR is to address bug in granule search code where entry titles with preceding white space were being properly matched against the corresponding ACLs.  The access control app having trimmed the entry titles before saving the ACL.
=> CMR-4913 EDSC shows 0 granules for public collection when user isn't logged in

ingest-app/src/cmr/ingest/api/provider.clj, ingest-app/src/cmr/ingest/services/provider_service.clj, system-int-test/test/cmr/system_int_test/ingest/provider_ingest_test.clj
This PR adds check for provider delete preventing non empty providers from being deleted
=> CMR-4879 As an operator, I should not be able to delete a CMR provider if it contains one or more collections

ingest-app/resources/CMR-4902/4902_smap_iso_collection.xml, ingest-app/resources/CMR-4902/4902_smap_iso_granule.xml, system-int-test/test/cmr/system_int_test/search/granule_search_format_test.clj, umm-lib/src/cmr/umm/iso_smap/granule.clj
Notes based on playing with the EDSC interface and the behaviors observed:
1. Ingest a smap granule with transferSize, retrieve it as echo10 and verify that the echo10 granule contains the SizeMBDataGranule with the same value. This is what needs to be fixed for this ticket.
2. Ingest a smap granule with transferSize, retrieve it as iso19115 is not supported. (existing behavior)
No need to fix for this ticket.
3. Ingest an echo10 granule with SizeMBDataGranule, retrieve it as iso19115, it should contain the transferSize (existing behavior). Make sure it continues to work after the fix.
4. Ingest an echo10 granule with SizeMBDataGranule, retrieve it as iso smap is not supported.(existing behavior). No need to fix for this ticket. So converting size in umm-granule to iso smap element is not …
=> CMR-4902: Read granule size from ISO SMAP.

search-app/src/cmr/search/services/query_execution.clj, system-int-test/test/cmr/system_int_test/search/facets/collection_facets_v2_search_test.clj, system-int-test/test/cmr/system_int_test/search/facets/facet_responses.clj
Currently, when a selected facet is outside of the facet size range, the count is assigned 0. 
As the facets_size increases, this count could change, we need to fix the inconsistency.
1. For each selected facet, say platform, instrument,   If the returned facet-result includes any 0 counts,
and the facets_size for the field is not 10000, then send the query to ES again, with facets_size increased to 10000 for the field, to insure all facets are returned for that field.
2. Update the original facet-result using the counts in the new facet-result.
=> CMR-4948: Return correct facet count when outside of facet size range.

access-control-app/int-test/cmr/access_control/int_test/fixtures.clj, access-control-app/src/cmr/access_control/services/acl_authorization.clj, access-control-app/src/cmr/access_control/services/acl_service.clj, access-control-app/src/cmr/access_control/services/auth_util.clj, acl-lib/src/cmr/acl/acl_fetcher.clj, acl-lib/src/cmr/acl/core.clj, common-app-lib/src/cmr/common_app/services/search/datetime_helper.clj, indexer-app/int-test/cmr/indexer/test/data/concepts/collection_acls.clj, indexer-app/src/cmr/indexer/data/concepts/collection.clj, mock-echo-app/src/cmr/mock_echo/client/echo_util.clj, search-app/src/cmr/search/services/acls/granule_acls.clj, search-app/test/cmr/search/test/services/acls/granule_acls.clj, system-int-test/test/cmr/system_int_test/search/acls/collection.clj, system-int-test/test/cmr/system_int_test/search/acls/granule.clj, system-int-test/test/cmr/system_int_test/search/acls/temporal_collection_granule.clj, system-int-test/test/cmr/system_int_test/virtual_product/translation_test.clj, transmit-lib/src/cmr/transmit/access_control.clj, transmit-lib/src/cmr/transmit/echo/acls.clj, umm-lib/src/cmr/umm/acl_matchers.clj, umm-spec-lib/src/cmr/umm_spec/acl_matchers.clj, umm-spec-lib/test/cmr/umm_spec/test/acl_matchers.clj
Remove logic relying on echo acls from CMR, instead rely on CMR acls.
=> CMR-4954 decouple access-control from echo in dev-system

umm-spec-lib/resources/example_data/iso19115/artificial_test_data1.xml, umm-spec-lib/src/cmr/umm_spec/iso19115_2_util.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso19115_2.clj
Note: The sample iso19115 xml file @eereiter provided in the ticket failed some validations that's not related to the ShortName parsing. So I created my own artificial data file that's the same as the existing artificial_test_data.xml except that the ShortName path is changed to the alternative path.
By adding this data file(see line 144), the testing is covered by generate-and-parse.clj
=> CMR-4876: Added alternative path for ISOMends ShortName.

bootstrap-app/README.md, bootstrap-app/src/cmr/bootstrap/api/rebalancing.clj, bootstrap-app/src/cmr/bootstrap/services/bootstrap_service.clj, bootstrap-app/src/cmr/bootstrap/services/dispatch/impl/message_queue.clj, common-lib/src/cmr/common/rebalancing_collections.clj, index-set-app/README.md, index-set-app/int-test/cmr/index_set/int_test/invalid_data_crud_tests.clj, index-set-app/int-test/cmr/index_set/int_test/utility.clj, index-set-app/int-test/cmr/index_set/int_test/valid_data_crud_tests.clj, index-set-app/src/cmr/index_set/api/routes.clj, index-set-app/src/cmr/index_set/data/elasticsearch.clj, index-set-app/src/cmr/index_set/services/index_service.clj, search-app/src/cmr/search/data/elastic_search_index.clj, system-int-test/src/cmr/system_int_test/utils/bootstrap_util.clj, system-int-test/src/cmr/system_int_test/utils/index_util.clj, system-int-test/test/cmr/system_int_test/bootstrap/rebalance_collections_test.clj, transmit-lib/src/cmr/transmit/index_set.clj
There are almost 70 collections that have 0 or a small number of granules today that currently have their own granule indexes. This happens when a collection that previously had a large (> 300,000) number of granules is deleted, or the majority of the granules within the collection have been deleted.
The reason we want to clean this up is that there is overhead with managing the shards in Elasticsearch, and when there are almost empty shards the nodes can become imbalanced. After this PR we'll be able to clean up almost 700 of the 3200 shards in Elasticsearch today.
=> CMR-4992: Update rebalancing-collections to support moving from a separate index to a the small collections index.

umm-lib/resources/data/iso_smap/granule_with_multiple_extents.xml, umm-lib/resources/data/iso_smap/sample_smap_iso_granule.xml, umm-lib/src/cmr/umm/iso_smap/granule/temporal.clj, umm-lib/test/cmr/umm/test/iso_smap/granule.clj
This PR is for changing the granule iso smap -> umm mapping such that when multiple extents are provided, it will map the first temporal it finds, instead of the only the first extent.  
Before, if there was no temporal extent in the first element of extents, the temporal mapping would be nil even if the subsequent extents included a temporal extent.
=> CMR-5031 Temporal extents not getting picked up for 2 SMAP datasets

access-control-app/int-test/cmr/access_control/int_test/acl_crud_test.clj, access-control-app/int-test/cmr/access_control/int_test/enable_disable_test.clj, access-control-app/src/cmr/access_control/services/acl_validation.clj
Group-ids that are invalid can cause internal errors, so we want to prevent any non CMR concept-id from populating that field in :group_permissions
=> CMR-4971 Adds validation on acl group-permissions group-id

system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj, umm-spec-lib/src/cmr/umm_spec/field_update.clj
When changing UMM-C version from 1.9 to 1.10 for the ingest, bulk update started to add empty instruments to the platforms that don't have instruments after the FIND_AND_UPDATE and FIND_AND_REPLACE. This PR fixed that issue.
=> CMR-4956: Fixed the bulkupdate so that it won't add empty instruments.

ingest-app/src/cmr/ingest/services/ingest_service/granule.clj, ingest-app/src/cmr/ingest/validation/validation.clj
After investigating the performance ticket locally, we've decided to add deft-timed for the validations inside the validate-granule function so that we could catch more information in the future workload testings.
=> CMR-5018: Added defn-timed for the validation functions.

ingest-app/resources/CMR-5007/dif10_Collection_C1239966837-GES_DISC.xml, ingest-app/resources/CMR-5007/echo10_Granlue_G1278223734-GES_DISC.xml, orbits-lib/resources/orbits/geometry_backtracking.rb, system-int-test/test/cmr/system_int_test/search/granule_orbit_search_test.clj
This PR fixed the 500 error when searching for orbit granule using polygon constraint with |altitude| > 86.52. The exact error being fixed is:  NoMethodError: undefined method `each' for #<Orbits::LongitudeCoverage:0x4b57ce0d>
web.c93f97e  |   areaCrossingRange at uri:classloader:/orbits/echo_orbits_impl.rb:91
=> CMR-5007: Fixed the 500 error.

umm-spec-lib/resources/example-data/iso19115/ISOExample-NOAA-Instrument-XPath.xml, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso19115_2.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_shared/instrument.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_shared/platform.clj, umm-spec-lib/test/cmr/umm_spec/test/noaa_instrument_xpath_test.clj
Note: I made a mistake in CMR-4885 when adding alternative xpath for ISOMends Instruments. I did it for both ISOMends and ISOSmap, which made ISOSmap parsing inefficient. I included the fix in this PR.
=> CMR-4884: Added alternative xpath for ISOMends Platforms.

bootstrap-app/src/cmr/bootstrap/services/bootstrap_service.clj, system-int-test/test/cmr/system_int_test/bootstrap/rebalance_collections_test.clj
When a collection has been deleted, along with its tombstone the index rebalancing for that collection would fail on the collection validation not finding a collection.  This would prevent removal of old unused indices.
=> CMR-5098 Fixes index rebalancing for old deleted collections.

access-control-app/docs/api.md, access-control-app/int-test/cmr/access_control/int_test/permission_check_test.clj, access-control-app/src/cmr/access_control/api/routes.clj, access-control-app/src/cmr/access_control/services/acl_service.clj, access-control-app/src/cmr/access_control/services/messages.clj, transmit-lib/src/cmr/transmit/config.clj, transmit-lib/src/cmr/transmit/http_helper.clj
Will need to add tests. Demo worked. Not sure where to add the tests. Looks like the current ACL related tests are just some ingest tests that test some ACL indirectly?
=> CMR-4906: Added Cmr-Revision-Id header for ACL update.

access-control-app/docs/api.md, system-int-test/src/cmr/system_int_test/utils/ingest_util.clj
Some ingest tests are currently testing against cmr.common-app.config/collection-umm-version, which is the accepted collection ingest umm version.  We should make our ingest tests testing against the latest umm version, which is cmr.umm-spec.versioning/current-collection-version. 
1. Set the collection-umm-version to current-collection-version in the ingest/reset-fixture, which is used in most of the ingest tests. 
Most of the collection ingest tests are not specifying the umm version, so it makes use of the collection-umm-version. By setting it to current-collection-version in the test environment, these ingest tests will test against the current-collection-version. Note: during the test, I changed the default value of cmr.common-app.config/collection-umm-version to "1.11", which doesn't …
=> CMR-4955: Make collection ingest tests to test against the latest umm version

ingest-app/project.clj, ingest-app/src/cmr/ingest/api/core.clj
I picked `metadata->concept` because it is used in all ingest functions. It can be moved easily
=> CMR-5080: log size of metadata to be ingested

bootstrap-app/src/cmr/bootstrap/api/bulk_index.clj, bootstrap-app/src/cmr/bootstrap/services/bootstrap_service.clj, system-int-test/test/cmr/system_int_test/bootstrap/rebalance_collections_test.clj
This also fixes the test which attempted to delete revisions from the database as part of the setup.
=> CMR-5098: Ensure we can remove collection indexes for collections which do not exist in Oracle

common-lib/src/cmr/common/test/url_util.clj, search-app/src/cmr/search/results_handlers/opendata_results_handler.clj, system-int-test/resources/cmr-5136-opendata-related-urls.xml, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj, umm-lib/src/cmr/umm/related_url_helper.clj, umm-lib/test/cmr/umm/test/related_url_helper.clj
* Check if related url is already encoded
* If so, skip. If not, encode it.
* Encode only the query '?' portion of the URL.
=> CMR-5136: Encode references for opendata format.

ingest-app/src/cmr/ingest/api/collections.clj, ingest-app/src/cmr/ingest/api/core.clj, ingest-app/src/cmr/ingest/api/granules.clj, ingest-app/src/cmr/ingest/api/services.clj, ingest-app/src/cmr/ingest/api/variables.clj
This PR is addressing  three issues:
1. Logging other concept info together with the metadata-size-bytes, specifically provider info so that Catalino could get all the metadata size ingested for a given provider.
2. Logging the metadata size only after successful ingest.
3. Make sure we log both the attempt and the success of ingest. The difference is at the attempt, the metadata-size-bytes is not logged. Currently granule ingest is logged at the attempt, collection ingest is logged at the success, service and variable ingest are not logged.  These all need to be changed.
The log will look sth like:
[a83aa11a-281a-48c0-b2fe-f232231074f7] INFO [cmr.ingest.api.core] - Successfully ingested concept {:format "application/echo10+xml", :native-id …
=> CMR-5080: Log metadata-size-bytes with provider info, after successful ingest

indexer-app/src/cmr/indexer/data/concepts/collection.clj, indexer-app/src/cmr/indexer/data/concepts/collection/opendata.clj, indexer-app/src/cmr/indexer/data/index_set.clj, search-app/src/cmr/search/results_handlers/opendata_results_handler.clj, system-int-test/src/cmr/system_int_test/data2/opendata.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj
Made changes to no longer export a MIME-type for access URLs since only download URLs are supposed to have a MIME-type. Added the description field to all of the distributions. Changed the references field to only include DOIs from Publication References instead of duplicating the list of distributions.
Before:
```
"references" : [ "https://docserver.gesdisc.eosdis.nasa.gov/public/project/Images/AIRX3STD_006.png", "https://acdisc.gesdisc.eosdis.nasa.gov/data/Aqua_AIRS_Level3/AIRX3STD.006/", "https://acdisc.gesdisc.eosdis.nasa.gov/opendap/Aqua_AIRS_Level3/AIRX3STD.006/contents.html", "https://disc.gsfc.nasa.gov/SSW/#keywords=AIRX3STD%20006", "https://search.earthdata.nasa.gov/search?q=AIRX3STD+006", "https://disc1.gsfc.nasa.gov/daac-bin/wms_airs?service=WMS&version=1.1.1&request=GetCapabili …
```
=> CMR-5135: Improvements to the distribution and references fields in opendata response.

cubby-app/src/cmr/cubby/api/routes.clj, system-int-test/src/cmr/system_int_test/system.clj, system-int-test/src/cmr/system_int_test/utils/url_helper.clj, system-int-test/test/cmr/system_int_test/admin/admin_permissions_test.clj, transmit-lib/src/cmr/transmit/cubby.clj
This PR puts potentially destructive cubby endpoints behind the ingest management acl for extra security.  These functions are behind the VPN in any case.
=> CMR-5122 Running cubby cache operations should require a token

collection-renderer-lib/project.clj, collection-renderer-lib/resources/collection_preview/collection_preview.erb, collection-renderer-lib/src/cmr/collection_renderer/services/collection_renderer.clj, collection-renderer-lib/test/cmr/collection_renderer/test/services/collection_renderer.clj
Collections without granules should not render the _SEARCH FOR GRANULES FROM THIS COLLECTION_ button. This results in:
**Without granules:**
**With granules:**
=> CMR-5081: collection render without granule change

indexer-app/src/cmr/indexer/data/concepts/granule.clj, spatial-lib/src/cmr/spatial/encoding/gmd.clj, umm-lib/src/cmr/umm/iso_smap/spatial.clj
Also removed the default implementation of decode-geo-content since we never expect it to be called. An exception will now be thrown if a definition is missing making it much easier to debug.
=> CMR-5129: Fixes issue with missing orbit information for granules

search-app/src/cmr/search/services/acls/granule_acls.clj, system-int-test/test/cmr/system_int_test/search/acls/granule.clj
This fixes granule searching, the prior PR only fixed collection searches.
=> CMR-5106 Changing Entry Title of a collection causes it to disappear from searches until the ACL is re-created

indexer-app/src/cmr/indexer/data/collection_granule_aggregation_cache.clj, indexer-app/src/cmr/indexer/data/concepts/collection.clj, indexer-app/src/cmr/indexer/data/index_set.clj, indexer-app/test/cmr/indexer/test/data/collection_granule_aggregation_cache.clj, search-app/src/cmr/search/results_handlers/opendata_results_handler.clj, system-int-test/resources/CMR-5138-DIF10-DataDates-Equal-NotProvided.xml, system-int-test/resources/CMR-5138-DIF10-DataDates-Provided.xml, system-int-test/resources/CMR-5138-DIF9-DataDates-Not-Exist.xml, system-int-test/src/cmr/system_int_test/data2/opendata.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj
For opendata collection search, when the collection's Creation Date and Last Modified Date are not present, or when they are equal to the default 1970 date, use collection's earliest granule's start date and latest granule's end date. If the collection has no granules, we should leave Creation Date blank and Last Modified Date blank(but since it's a required field, we are adding a default currently, which is different from the 1970 date).  This is what the ticket asked.
In this PR:
1. We always use granule-start-date and granule-end-date regardless of if the collection has granules. When collection doesn't have granules, these dates contain the earliest and the latest of the collection's TemporalExtent data. @chris-durbin thinks we might just want to do it this way. If we decide we want …
=> CMR-5138: Use Granule's start/end date for issued/modified in opendata.

search-app/src/cmr/search/results_handlers/opendata_results_handler.clj, system-int-test/resources/CMR-5138-DIF10-No-DataDates-No-Temporal-Coverage.xml, system-int-test/src/cmr/system_int_test/data2/opendata.clj, system-int-test/test/cmr/system_int_test/search/acls/collection.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj
This PR addressed the following:
1. If "issued" value is the default 1970 value, make it nil.
2. If "modified" value is nil, don't use default, use collection's revision-date.
=> CMR-5217: Use collection revision-date as default "modified" field for opendata.

indexer-app/src/cmr/indexer/data/collection_granule_aggregation_cache.clj, indexer-app/src/cmr/indexer/data/concepts/collection.clj, indexer-app/src/cmr/indexer/data/index_set.clj, indexer-app/test/cmr/indexer/test/data/collection_granule_aggregation_cache.clj, search-app/src/cmr/search/data/query_to_elastic.clj, search-app/src/cmr/search/results_handlers/opendata_results_handler.clj, system-int-test/src/cmr/system_int_test/data2/opendata.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj
Refactor so that the Elasticsearch index field-names aren't exposed outside of the indexer and query-to-elastic namespaces.
=> CMR-5217: Refactor granule-start-date-stored and granule-end-date-stored

common-lib/src/cmr/common/doi.clj, common-lib/test/cmr/common/test/doi.clj, indexer-app/src/cmr/indexer/data/concepts/collection/opendata.clj, search-app/src/cmr/search/data/query_to_elastic.clj, search-app/src/cmr/search/results_handlers/opendata_results_handler.clj, search-app/src/cmr/search/site/data.clj, search-app/test/cmr/search/test/site/data.clj, system-int-test/resources/CMR-5138-DIF10-DataDates-Provided.xml, system-int-test/src/cmr/system_int_test/data2/opendata.clj, system-int-test/test/cmr/system_int_test/search/collection_directory_pages_test.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj
Otherwise they use the collection HTML response for the landing page.
=> CMR-5137: Landing pages in opendata response use DOI if present

common-lib/src/cmr/common/util.clj, indexer-app/src/cmr/indexer/data/concepts/collection/opendata.clj, search-app/src/cmr/search/results_handlers/opendata_results_handler.clj, search-app/test/cmr/search/test/results_handlers/opendata_results_handler.clj, system-int-test/src/cmr/system_int_test/data2/opendata.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj
* Get browse images from RelatedUrls.
* Add graphic-preview-file from browse image URL.
* Add graphic-preview-description from browse image description.
* Add graphic-preview-type from either the RelatedUrl/GetData/Format or RelatedUrl/GetData/MimeType.
On data.gov the Additional Metadata will now display the fields as:
The image will show as such:
=> CMT-5139: Add graphic to opendata response.

search-app/src/cmr/search/results_handlers/opendata_results_handler.clj, search-app/test/cmr/search/test/results_handlers/opendata_results_handler.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj
This PR constructs a distribution for a google scholar search url, and adds it to the distribution field in the opendata result.
=> CMR-5144 As a user browsing data.gov, I want the relevant Google Scholar link to appear on the page, so I can easily reference these listings.

search-app/src/cmr/search/results_handlers/opendata_results_handler.clj, search-app/test/cmr/search/test/results_handlers/opendata_results_handler.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj, umm-lib/src/cmr/umm/related_url_helper.clj, umm-lib/test/cmr/umm/test/related_url_helper.clj
* Decide whether to use accessURL or downloadURL for distributions.
* Infer mime type based off file extension if one is not provided.
* Determine if URL is downloadable based off the type being "GET DATA" and the ability to figure out the mime type.
=> CMR-5236: Opendata downloadURL vs accessURL.

search-app/src/cmr/search/results_handlers/opendata_results_handler.clj, search-app/test/cmr/search/test/results_handlers/opendata_results_handler.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj, umm-lib/src/cmr/umm/related_url_helper.clj, umm-lib/test/cmr/umm/test/related_url_helper.clj
* Change downloadURL criteria to now be based solely off the mime-type.
* Any mimetype other than text/*, with the exception of text/csv, is downloadable.
=> CMR-5236: Change downloadURL criteria.

indexer-app/src/cmr/indexer/data/concepts/granule.clj, indexer-app/src/cmr/indexer/data/index_set.clj, system-int-test/resources/index_set_granule_mapping.clj
This is the part 1 of supporting granule search in UMM JSON format. We separate the indexer change from the search-app change to allow clean backport of indexing changes to UAT and PROD to reindex all granules before we deploy the search changes that depend on the new granule elasticsearch fields.
=> CMR-5272: Updated granule elastic mapping to support granule UMM JSON search

search-app/docs/api.md, search-app/src/cmr/search/api/routes.clj, search-app/src/cmr/search/data/metadata_retrieval/metadata_cache.clj, search-app/src/cmr/search/data/query_to_elastic.clj, search-app/src/cmr/search/results_handlers/granules_umm_json_results_handler.clj, search-app/src/cmr/search/results_handlers/variables_umm_json_results_handler.clj, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/validators/validation.clj, system-int-test/src/cmr/system_int_test/data2/umm_json.clj, system-int-test/test/cmr/system_int_test/search/facets/granule_v2_facets_search_test.clj, system-int-test/test/cmr/system_int_test/search/granule_search_format_test.clj, system-int-test/test/cmr/system_int_test/search/granule_umm_json_search_test.clj, system-int-test/test/cmr/system_int_test/search/umm_json_search_test.clj, umm-spec-lib/resources/json-schemas/granule/umm/v1.4/umm-g-search-results-json-schema.json, umm-spec-lib/src/cmr/umm_spec/json_schema.clj
This is the second part of CMR-5272 to add in the search support to return granule search in UMM JSON format. e.g. 
```
{
"hits" : 2,
"took" : 58,
"items" : [ {
"meta" : {
"concept-type" : "granule",
"concept-id" : "G1200000007-PROV1",
"revision-id" : 1,
"native-id" : "echo1o-granule",
"provider-id" : "PROV1",
"format" : "application/echo10+xml",
"revision-date" : "2018-11-09T03:48:38Z"
},
"umm" : {
"TemporalExtent" : {
"RangeDateTime" : {
"BeginningDateTime" : "2013-08-09T00:00:00.000Z",
"EndingDateTime" : "2013-08-09T00:00:00.000Z"
}
},
"GranuleUR" : "8046d7eb-0ce7-48f5-921a-a1600f41c5b2",
.......
}
}
.......]
}
```
=> CMR-5272: Added support to search granules in UMM JSON format.

common-app-lib/src/cmr/common_app/services/search/validators/max_number_of_conditions.clj, system-int-test/test/cmr/system_int_test/search/collection_identifier_search_test.clj, system-int-test/test/cmr/system_int_test/search/granule_search_readable_granule_name_test.clj
The query condition limit was added in CMR-3069 to fix the 500 error, it's supposed to also support 2000 granule-id search.
We set the limit to 2050 thinking it's more than enough to support that, but forgot we query two fields for each granule-id.
in order to support that, we need to bump the limit up to more than 4001..
=> CMR 4645 can not search for 2000 granules

common-lib/src/cmr/common/api/web_server.clj, elastic-utils-lib/src/cmr/elastic_utils/connect.clj, transmit-lib/src/cmr/transmit/connection.clj
=> CMR-5359: Make number of Jetty threads configurable and default to 1024.

search-app/src/cmr/search/api/concepts_search.clj, search-app/src/cmr/search/api/routes.clj
Added a data.json endpoint in order to test the connector feature for data.nasa.gov. The connector feature requires an endpoint ending in /data.json to be able to harvest opendata and hopefully sync with data.nasa.gov's data.json response. 
Only testing 20 collections from production for now. If successful will change to harvest all publicly available collections from cmr.
=> CMR-5360: Add data.json endpoint to test data.nasa.gov.

search-app/src/cmr/search/api/concepts_search.clj, search-app/src/cmr/search/services/query_service.clj, system-int-test/src/cmr/system_int_test/utils/search_util.clj, system-int-test/src/cmr/system_int_test/utils/url_helper.clj, system-int-test/test/cmr/system_int_test/search/data_json_search_test.clj
* data.json endpoint at search/socrata/data.json.
* Move def to defn.
* Return all public collections with gov.nasa.eosdis tag.
* Use query functions instead of http calls.
=> CMR-5374: Complete data.json response.

access-control-app/project.clj, access-control-app/src/cmr/access_control/site/data.clj, common-app-lib/resources/public/site/css/eui.css, common-app-lib/src/cmr/common_app/config.clj, ingest-app/project.clj, ingest-app/src/cmr/ingest/site/data.clj, search-app/project.clj, search-app/src/cmr/search/site/data.clj, search-app/test/cmr/search/test/site/routes.clj, site-templates/project.clj, site-templates/resources/templates/base.html
At deployment environment variable CMR_RELEASE_VERSION is set to the release version.  This is done through bamboo adding this env variable to .env, which is sourced when CMR starts up.
=> CMR-5378: Add the release version to the footer for the CMR core landing pages.

common-lib/project.clj, common-lib/src/cmr/common/xml/xslt.clj
This is to guarantee that xslt 2.0 processor is used for xslt translation.
=> CMR-5387: Fixed common-lib xslt translation to explicitly use Saxon lib.

search-app/README.md, search-app/src/cmr/search/api/concepts_search.clj, system-int-test/test/cmr/system_int_test/search/data_json_search_test.clj
no longer need data.json endpoint to be configurable.
=> CMR-5423: remove data.json config option.

cmr-exchange/metadata-proxy/project.clj, cmr-exchange/metadata-proxy/src/cmr/metadata/proxy/concepts/variable.clj, cmr-exchange/ous-plugin/project.clj, cmr-exchange/ous-plugin/src/cmr/ous/config.clj, cmr-exchange/service-bridge/project.clj, cmr-exchange/service-bridge/src/cmr/opendap/config.clj, cmr-exchange/ses-plugin/project.clj, cmr-exchange/ses-plugin/src/cmr/sizing/formats.clj
This ticket only addresses the existing compression formats: ASCII and NetCDF-4.  Since we don't use compression rate for ASCII estimate anymore, it only affects NetCDF-4.
=> CMR-5489: Fixed SES compression rate retrieval for Var1.4

mock-echo-app/src/cmr/mock_echo/client/echo_util.clj, mock-echo-app/src/cmr/mock_echo/client/mock_urs_client.clj
=> CMR-5497: Fix mock-echo URS endpoint so that calls to create users work if the URS_RELATIVE_ROOT_URL is empty or /urs

umm-spec-lib/resources/example-data/iso19115/artificial_test_data_2.xml, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso19115_2.clj
The ISO 19115-2 MENDS metadata is not correctly generating the ShortName identifier section.
The generated output generates the following:
{noformat}
<gmd:identifier>
<gmd:MD_Identifier>
<gmd:code>
<gco:CharacterString>AIRX3STD</gco:CharacterString>
</gmd:code>
<gmd:version>
<gco:CharacterString>006</gco:CharacterString>
</gmd:version>
</gmd:MD_Identifier>
</gmd:identifier>
{noformat}
But 
{noformat}
<gmd:version>
<gco:CharacterString>006</gco:CharacterString>
</gmd:version>
{noformat}
is not valid ISO 19115-2. Instead this section should contain:
{noformat}
<gmd:codeSpace>
<gco:CharacterString>gov.nasa.esdis.umm.shortname</gco:CharacterString>
</gmd:codeSpace>
<gmd:description>
<gco:CharacterString>Short Name</gco:CharacterString>
</gmd:description>
{noformat}
=> The ISO 19115-2 MENDS metadata is not correctly generating the ShortName identifier section.

cmr-exchange/ous-plugin/project.clj, cmr-exchange/ous-plugin/src/cmr/ous/config.clj, cmr-exchange/service-bridge/project.clj, cmr-exchange/service-bridge/src/cmr/opendap/config.clj, cmr-exchange/ses-plugin/project.clj
1. The deployment to SIT failed because the code could not take the value from environment variable
CMR_SERVICE_BRIDGE_PORT, and was listening on the default port 3013.
2. When service-bridge was brought under cmr repo, metadata-proxy was at 0.2.1-SNAPSHOT.  This version removed the part that gets the env setting from the config.clj and moved it to exchange-common. Both this metadata-proxy version and the exchange-common version were not used by ous and service-bridge. They were still referencing the old clojars so it was deployed successfully.
3. CMR-5489 needed to create a new metadata-proxy snapshot to account for the new UMM-Var version, now both ous and service-bridge had to bump from metadata proxy snapshot of 0.2.0 to 0.2.2. 
Since 0.2.1 removed the env setting in the config.clj, I …
=> CMR-5489: Fixed the service-bridge deployment introduced by CMR-5489

common-app-lib/src/cmr/common_app/services/search/parameters/converters/nested_field.clj, common-app-lib/src/cmr/common_app/services/search/params.clj, indexer-app/src/cmr/indexer/data/concepts/granule.clj, indexer-app/src/cmr/indexer/data/concepts/track.clj, indexer-app/src/cmr/indexer/data/index_set.clj, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/parameters/converters/pass.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, search-app/src/cmr/search/services/query_service.clj, system-int-test/resources/index_set_granule_mapping.clj, system-int-test/src/cmr/system_int_test/data2/granule.clj, system-int-test/test/cmr/system_int_test/search/granule_search_by_track_test.clj
This is the first cut of supporting granule search with track info. 
I filed CMR-5524 to add the various validation rules to make this feature complete. The search api doc will be updated once CMR-5524 is complete. This way we don't let people to try this before it is ready.
An example of searching granules with track info is:
curl -g  "http://localhost:3003/granules?cycle=3&passes[0][pass]=1&passes[0][tiles]=1L,2R"
=> CMR-5433: As a SWOT user I want to search for granules based on the spatial extent string values of cycle, pass, and tile.

search-app/src/cmr/search/services/query_execution/multi_part_query_feature_common.clj, system-int-test/src/cmr/system_int_test/utils/search_util.clj, system-int-test/test/cmr/system_int_test/search/collection_with_new_granule_search_test.clj
collection-pre-query result format needs to be standard in order to extract concept ids in cmr.search.services.query-execution.has-granules-created-at-feature.
Otherwise the call to (map :concept-id collection-results) may return (nil) in the case of say umm_json which would require (map #(get-in % [:meta :concept-id]) collection-results).
=> CMR-5520: Standardize collection-pre-query fmt.

collection-renderer-lib/resources/security/suppression.xml, orbits-lib/resources/security/suppression.xml
collection-renderer-lib and orbits-lib suppressions.
Suppressed:
JRuby OpenSSL Vulnerabilities.
- Reason: Not used in collection-renderer-lib or orbits-lib.
JRuby Hash Flood Vulnerabilities. 
-Reason: Affected earlier versions of JRuby. 
- Evidence: https://www.jruby.org/2012/12/03/jruby-1-7-1.html
JRuby Regex Vulnerability. 
- Reason: Affected earlier versions of JRuby. 
- Evidence: https://www.jruby.org/2010/04/26/jruby-1-4-1-xss-vulnerability.html
Elasticsearch Vulnerabilities. 
- Reason: Affected earlier versions of elastic. 
- Evidence. Followed guidance on: https://www.elastic.co/community/security
math-z Git Vulnerabilities. 
- Reason: Not applicable to the CMR.
mintToken Vulnerability. 
- Reason: Not applicable to the CMR.
=> CMR-5309 CMR-5323

README.md, indexer-app/src/cmr/indexer/data/concepts/collection/opendata.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj
Contact email address can now be found when no contact person or contact group is provided but contact information exists at the top level of the data center. Example:
```
"DataCenters" : [ {
"Roles" : [ "<role>" ],
"ShortName" : "<shortname>",
"ContactInformation" : {
"ContactMechanisms" : [ {
"Type" : "Email",
"Value" : "<email-address>"
} ],
...
```
=> CMR-5647: Search for email address at top level.

collection-renderer-lib/project.clj
* updated RelatedUrl enums for UMM-C update to v1.12
=> MMT-1490: update preview gem for UMM-C update to v1.12

cmr-exchange/metadata-proxy/project.clj, cmr-exchange/metadata-proxy/src/cmr/metadata/proxy/concepts/variable.clj, cmr-exchange/ous-plugin/project.clj, cmr-exchange/service-bridge/project.clj, cmr-exchange/service-bridge/test/cmr/opendap/tests/system/app/sizing/netcdf4.clj, cmr-exchange/ses-plugin/project.clj
This is to account for:
1. Fix the group node wildcard case, where (count [/a/b/* /a/b]) is obviously not right for the page_size.
2. For normal variable concept-id case, where page_size = (count variable-info) is correct, but it can't be more than 2000. 
Tried to implement scrolling in the event when the returning number of variables > 2000, but the response in the code doesn't return any header info where CMR-Scroll-Id can be used for subsequent calls. I think some changes need to be made in the http code but it doesn't look intuitive to me.  Since the existing code before this ticket used (count variable-info) for page_size, where it didn't take into account of 2000+ case either. So, it's an existing bug. I think perhaps I could just file a new ticket to fix it using scrolling, …
=> CMR-5526: Changed the page_size to 2000.

bootstrap-app/resources/security/suppression.xml, dev-system/resources/security/suppression.xml, search-app/resources/security/suppression.xml
Vulnerability fixes for: bootstrap, dev-system, search-app:
* Suppressed everything in dev-system.
* suppressed guava vulnerability. Only used for validation of ip addresses in a subdependency of swagger.
=> CMR-5308,CMR-5313,CMR-5324: Fix vulnerabilities.

access-control-app/int-test/cmr/access_control/int_test/access_control_group_acl_test.clj, common-lib/src/cmr/common/api/errors.clj, common-lib/test/cmr/common/test/api/errors.clj, system-int-test/src/cmr/system_int_test/utils/site_util.clj, system-int-test/test/cmr/system_int_test/search/acls/collection.clj, system-int-test/test/cmr/system_int_test/search/humanizer/community_usage_metrics_test.clj, system-int-test/test/cmr/system_int_test/search/humanizer/humanizer_test.clj, system-int-test/test/cmr/system_int_test/search/tagging/tag_crud_test.clj, transmit-lib/src/cmr/transmit/echo/rest.clj, transmit-lib/test/cmr/transmit/test/echo/rest.clj
Proposed changes:
* Mask token in error messages in transmit echo rest
* Mask token in common API errors module
TODOs:
=> Mask tokens in error messages

search-app/src/cmr/search/results_handlers/opendata_results_handler.clj, system-int-test/src/cmr/system_int_test/data2/umm_spec_collection.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj
When OtherCitationDetails is the only key provided in the collection citation, assume that is the full citation.
=> CMR-5663: Only construct citation when needed.

cmr-exchange/service-bridge/project.clj, cmr-exchange/service-bridge/test/cmr/opendap/tests/system/app/sizing/native.clj, cmr-exchange/service-bridge/test/cmr/opendap/tests/system/app/sizing/netcdf4.clj, cmr-exchange/service-bridge/test/cmr/opendap/tests/system/app/sizing/shapefile.clj, cmr-exchange/ses-plugin/project.clj, cmr-exchange/ses-plugin/src/cmr/sizing/formats.clj
Marty's study shows that a simple (total-bytes * avg-compression-rate) is more accurate than Bob's approach of using (total-bytes * arg-compression-rate * ((total-bytes/gran-count)/AverageSizeOfGrnaulesSamples))).
=> CMR-5665: Remove the use of AverageSizeOfGranulesSampled in SES.

dev-system/dev/user.clj, dev-system/src/cmr/dev_system/system.clj, message-queue-lib/src/cmr/message_queue/queue/memory_queue.clj, message-queue-lib/src/cmr/message_queue/queue/queue_protocol.clj, message-queue-lib/src/cmr/message_queue/queue/sqs.clj, message-queue-lib/src/cmr/message_queue/services/queue.clj, message-queue-lib/src/cmr/message_queue/test/queue_broker_wrapper.clj, message-queue-lib/test/cmr/message_queue/test/queue/sqs.clj
This PR makes changes our SNS and SQS client connections to be atoms so that if they encounter an unrecoverable error, we will recreate the client and all future requests will use the new client.
I made some changes to our dev-system setup so that testing with :aws as the :messaging component will work. I reproduced the same problem we saw in operations and verified that the connection was recreated successfully and all subsequent ingests worked correctly (messages made it to the SNS exchange and were picked up and indexed successfully).
The way I reproduced the problem was running the following in the REPL:
```(-> user/system :apps :metadata-db :queue-broker :sns-client-atom deref .shutdown)```
I'm also going to run a workload run before merging this PR in.
=> CMR-5695: Recreate SNS and SQS clients when they encounter an error

common-app-lib/src/cmr/common_app/api/routes.clj, common-app-lib/src/cmr/common_app/services/search.clj, search-app/src/cmr/search/api/concepts_search.clj, search-app/src/cmr/search/results_handlers/timeline_results_handler.clj, search-app/src/cmr/search/services/query_service.clj, system-int-test/src/cmr/system_int_test/utils/search_util.clj, system-int-test/test/cmr/system_int_test/search/granule_timeline_test.clj
Headers now look like:
```
Date: Mon, 20 May 2019 13:22:49 GMT
Content-Type: application/json;charset=utf-8
Access-Control-Expose-Headers: CMR-Hits, CMR-Request-Id, CMR-Scroll-Id
Access-Control-Allow-Origin: *
CMR-Took: 9
CMR-Request-Id: d9b1a6ac-ffdf-409d-8191-bf23ad5a5a47
Vary: Accept-Encoding, User-Agent
Content-Length: 171
```
=> CMR-5723: Add Access-Control-Expose-Headers to a few search routes

cmr-exchange/metadata-proxy/project.clj, cmr-exchange/ous-plugin/project.clj, cmr-exchange/ous-plugin/src/cmr/ous/common.clj, cmr-exchange/service-bridge/project.clj, cmr-exchange/service-bridge/test/cmr/opendap/tests/system/app/ous/core.clj, cmr-exchange/ses-plugin/project.clj
It might be desirable to allow multiple tag replacements. I will create another ticket if the team thinks we should do it.
=> CMR-5726: Removed the trailing .html from the granule's urls.

access-control-app/src/cmr/access_control/config.clj
This is needed by the NGAP 2.0 deployments to allow access-control to create the queues if they don't exist when it tries to start.
=> Add additional queues to access-control config to create them if necessary

cmr-exchange/service-bridge/Dockerfile, cmr-exchange/service-bridge/project.clj
Will also fix builds that have been failing due to outdated versions.
=> CMR-5628 Dockerfile and project.clj updates for NGAP 2.0 deployment

indexer-app/src/cmr/indexer/api/routes.clj, system-int-test/src/cmr/system_int_test/utils/index_util.clj, system-int-test/src/cmr/system_int_test/utils/url_helper.clj, system-int-test/test/cmr/system_int_test/ingest/collection_ingest_test.clj
This has been tested in SIT. Basically what gets selected in index-svc/index-concept-by-concept-id-revision-id is :ignore-conflict.
=> CMR-5747: Fixed ignore_conflict parameter.

ingest-app/src/cmr/ingest/api/routes.clj
Missed this change on the last PR
=> Use proper config namespace for ingest migrations

access-control-app/int-test/cmr/access_control/int_test/acl_crud_test.clj, access-control-app/int-test/cmr/access_control/int_test/permission_check_test.clj, access-control-app/src/cmr/access_control/data/acl_schema.clj, access-control-app/src/cmr/access_control/services/acl_validation.clj
Adds a new target to provider object acls to allow mmt to manage non nasa draft mmt users.
=> CMR-5797 Add "Non-NASA" user all for draft MMT

collection-renderer-lib/resources/collection_preview/collection_preview.erb, collection-renderer-lib/src/cmr/collection_renderer/services/collection_renderer.clj
On Chrome it complained about http(instead of https) access to the css files because it's using relative paths. Changed them to absolute paths.
=> CMR-5743: Fixed the relative path for css files.

access-control-app/docs/acl-schema.md, access-control-app/docs/api.md, search-app/docs/api.md
In general, the max character limit restriction on URLs could be affected by the browser type and server config. We have done test on CMR endpoint before and the answer is ~6000 characters, but if you go through browsers, the general guideline is ~2000.
Our recommendation is for clients to use the POST endpoint when submitting queries with long query parameters
=> CMR-5832 CMR Search API Documentation Maximum URL Length does not provide reasonable guidance.

metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/cleanup_test.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, metadata-db-app/src/cmr/metadata_db/services/jobs.clj
For testing:
Deployed to SIT.
Created an ACL with 20 revisions - ACL1200360718-CMR
Checked splunk:
2019-08-16 03:17:29.032 ip-10-5-33-36.ec2.internal [OldRevisionConceptCleanupJob] INFO [cmr.metadata-db.services.concept-service] - Starting deletion of old acls for provider CMR host =	 splunk_hec_serverssource =	 http:NGAP_Event_Collectorsourcetype =	 httpevent
  
Verified in SIT database that revisions 1 through 10 were removed and revisions 11 to 20 are remaining.
=> CMR-5834: Limit ACL revisions to 10.

browse-scaler/src/index.js, browse-scaler/src/resize.js, browse-scaler/src/util.js
The issue was we set request timeout to be 3 seconds. When the image was not found, the time it took to get to that point was already very close to 3 seconds(through withTimeout function). so it didn't have enough time to complete notFound function before the request timed out, which threw 502.
1. Shortened the default timeoutInterval to be 1000, instead of 2000ms. 
2. Added withTimeout to getImageUrlFromConcept, just in case it takes too long.
3. Modified withTimeout function to handle the case when the promise is rejected.
=> Cmr 5873 browse scaler throws 502

common-app-lib/src/cmr/common_app/services/search/elastic_search_index.clj, elastic-utils-lib/src/cmr/elastic_utils/config.clj
James and I add this retry to resolve the 503 error related to search encounters UnknownHostException when talking to ES cluster via DNS name. We are planning to backport this fix to PROD.
=> CMR-6020: Added retries to execute ES query on UnknownHostException

.gitignore, common-app-lib/src/cmr/common_app/services/search/elastic_search_index.clj, elastic-utils-lib/src/cmr/elastic_utils/config.clj, search-app/docs/api.md
This adds a timeout to the Elasticsearch queries to avoid 504 errors from CloudFront. This does not cause an error if the query times out - it simply returns whatever results are available when the timeout occurs.
Note that there are no additional (automated) tests for this as it is not possible to force a query timeout in Elasticsearch.
=> CMR-6016: Add timeout to Elasticsearch queries

common-app-lib/src/cmr/common_app/api/routes.clj, common-app-lib/src/cmr/common_app/services/search.clj, common-app-lib/src/cmr/common_app/services/search/elastic_results_to_query_results.clj, common-app-lib/src/cmr/common_app/services/search/elastic_search_index.clj, common-app-lib/src/cmr/common_app/services/search/results_model.clj, search-app/docs/api.md, search-app/src/cmr/search/results_handlers/atom_results_handler.clj, search-app/src/cmr/search/results_handlers/kml_results_handler.clj, search-app/src/cmr/search/results_handlers/metadata_results_handler.clj, search-app/src/cmr/search/results_handlers/timeline_results_handler.clj, search-app/src/cmr/search/results_handlers/umm_json_results_helper.clj, system-int-test/test/cmr/system_int_test/search/granule_timeline_test.clj
Adds a CMR-Timed-Out header to indicate an Elasticsearch query timeout occurred.
=> Cmr 6016 add timed out header

collection-renderer-lib/resources/collection_preview/bootstrap.rb, collection-renderer-lib/src/cmr/collection_renderer/api/routes.clj
Added gems/cmr_metadata_preview-<version> / to resource-paths to avoid needing to explicitly reference the version number. This makes updating the preview gem version easier.
=> CMR-6049: Remove reference to preview gem version.

dev-system/src/cmr/dev_system/control.clj, redis-utils-lib/src/cmr/redis_utils/config.clj, redis-utils-lib/src/cmr/redis_utils/redis.clj, redis-utils-lib/src/cmr/redis_utils/redis_cache.clj, redis-utils-lib/test/cmr/redis_utils/test/test_redis_cache.clj, system-int-test/test/cmr/system_int_test/search/acls/collection.clj
Remove redis query with KEYS * in favor of SCAN.
=> CMR-6059: Fix intermittent test failure.

metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/delete_test.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/search/variable_association_search_test.clj, metadata-db-app/src/cmr/metadata_db/data/memory_db.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, search-app/docs/api.md, search-app/src/cmr/search/api/association.clj, search-app/src/cmr/search/services/association_service.clj, system-int-test/src/cmr/system_int_test/utils/variable_util.clj, system-int-test/test/cmr/system_int_test/search/facets/collection_facets_v2_search_test.clj, system-int-test/test/cmr/system_int_test/search/facets/facet_responses.clj, system-int-test/test/cmr/system_int_test/search/variable/collection_variable_search_test.clj, system-int-test/test/cmr/system_int_test/search/variable/variable_association_test.clj, system-int-test/test/cmr/system_int_test/search/variable/variable_search_test.clj
Implemented:
CMR-5969: Multiple variables with the same name can't be associated with one collection.
CMR-5970: Each variable can only be associated with one collection.
CMR-5971: variable and collection can only be associated if they belong to the same provider.
=> Cmr 5969 cmr 5970 cmr 5971 variable association restrictions

access-control-app/src/cmr/access_control/api/routes.clj, access-control-app/src/cmr/access_control/system.clj, access-control-app/src/cmr/db.clj, bootstrap-app/src/cmr/bootstrap/data/rebalance_util.clj, bootstrap-app/src/cmr/bootstrap/system.clj, common-app-lib/src/cmr/common_app/config.clj, common-app-lib/src/cmr/common_app/services/search/elastic_search_index.clj, elastic-utils-lib/src/cmr/elastic_utils/config.clj, elastic-utils-lib/src/cmr/elastic_utils/es_helper.clj, elastic-utils-lib/src/cmr/elastic_utils/es_index_helper.clj, elastic-utils-lib/src/cmr/elastic_utils/index_util.clj, indexer-app/int-test/cmr/indexer/test/services/index_fields.clj, indexer-app/int-test/cmr/indexer/test/valid_data_crud_tests.clj, indexer-app/src/cmr/indexer/data/collection_granule_aggregation_cache.clj, indexer-app/src/cmr/indexer/data/elasticsearch.clj, indexer-app/src/cmr/indexer/data/index_set_elasticsearch.clj, indexer-app/src/cmr/indexer/system.clj, search-app/src/cmr/search/data/elastic_search_index.clj, search-app/src/cmr/search/services/query_service.clj, search-app/src/cmr/search/system.clj
This is the initial setup of making CMR Backend Search Engine configurable. 
Two new config parameter are added: CMR_INDEX_ES_ENGINE and CMR_SEARCH_ES_ENGINE. CMR_INDEX_ES_ENGINE can have values of `old`, `new` and `both`, where `old` means the current ES 1.6.2 version; `new` means the latest ES version we want to upgrade to; `both` means that both the old and new ES clusters would be running as the backend engines for indexer. CMR_SEARCH_ES_ENGINE can have values of `old` and `new` only, as we only want to search one ES cluster at a time (this can be changed later if we want to search both and do comparison, but I don't see it happening for now).
I put in some helper functions (in `cmr.elastic-utils.es-helper` and `cmr.elastic-utils.es-index-helper`) that wrap the calls to ES directly so …
=> Cmr 6132 1

elastic-utils-lib/.gitignore, elastic-utils-lib/project.clj, elastic-utils-lib/resources/docker/docker-compose.yml, elastic-utils-lib/src/cmr/elastic_utils/connect.clj, elastic-utils-lib/src/cmr/elastic_utils/es_helper.clj, elastic-utils-lib/src/cmr/elastic_utils/es_index_helper.clj, elastic-utils-lib/src/cmr/elastic_utils/index_util.clj, indexer-app/src/cmr/indexer/data/index_set_elasticsearch.clj
This PR runs dev-system against the external Elasticsearch 7.5.2 that is running locally via docker. The ES can be started by running `docker-compose up` in the `resources/docker` directory under `elastic-utils-lib`. The dev-system can be started successfully and most of the search integration tests can also run successfully with the code changes in this PR. 
I tried `https://github.com/spandex-project/spandex`, but found it too low level and is too big a departure from our existing code base. On the other end, the Elastisch 5.0.0-beta1 release fixed most of upgrade issues for us and aligns well with our existing code base. So I decided to continue using the Elastisch library and add in fixes in the helper namespaces in `elastic-utils-lib` when necessary.
This PR will not run in CI …
=> CMR-6222: As a CMR Developer, I Want to Run Dev-system on Top of ES 7.5.2

collection-renderer-lib/project.clj
MMT just updated one of their dependencies. Nothing needs to be specially tested for CMR.
=> CMR-6237: Updated collection preview gem

search-app/docs/api.md, search-app/src/cmr/search/api/autocomplete.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, system-int-test/src/cmr/system_int_test/utils/search_util.clj, system-int-test/src/cmr/system_int_test/utils/url_helper.clj, system-int-test/test/cmr/system_int_test/search/autocomplete_collection_facet_search_test.clj
Autocomplete parameters have been updated to follow CMR standard parameter format.
Response has been modified to follow standard CMR responses.
<h2>Changes</h2>
- _types_ has been removed and no longer accepts CSV values
- _types_ has been replaced by an optional list of _type[]_
* e.g.  `&type[]=instrument&type[]=platform`
- CMR-Hits value now included in response header denoting total number of hits found
* may be different than total returned in response if using paging options
- response format now follows standard CMR response structure
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
CMR-Hits: 1
{
"feed": {
"entry": [
{
"score": 88.00000,
"type": "instrument",
"value": "flux capacitor"
}
]
}
}
```
=> CMR-6235 Updated autocomplete parameters and response to follow CMR standards

common-app-lib/src/cmr/common_app/services/search/query_model.clj, common-app-lib/src/cmr/common_app/services/search/query_to_elastic.clj, search-app/src/cmr/search/data/query_to_elastic.clj, search-app/src/cmr/search/models/query.clj, search-app/src/cmr/search/services/autocomplete_service.clj, system-int-test/test/cmr/system_int_test/search/autocomplete_collection_facet_search_test.clj
recreating #911 PR
Updated autocomplete to use scoring feature from Elasticsearch to provide better relevancy scoring of returned values
=> CMR-6221 Autocomplete functionality with scoring determining suggestion return order

search-app/docs/api.md, search-app/src/cmr/search/api/association.clj, search-app/test/cmr/search/test/api/association.clj, system-int-test/src/cmr/system_int_test/utils/service_util.clj, system-int-test/src/cmr/system_int_test/utils/variable_util.clj, system-int-test/test/cmr/system_int_test/search/acls/variable_association.clj, system-int-test/test/cmr/system_int_test/search/service/service_association_test.clj, system-int-test/test/cmr/system_int_test/search/variable/variable_association_test.clj
Associations will now return 400 on error during processing. The error is contained in the response body.
=> CMR-6219 updated response code for association actions

indexer-app/src/cmr/indexer/data/elasticsearch.clj, indexer-app/src/cmr/indexer/services/event_handler.clj, indexer-app/src/cmr/indexer/services/index_service.clj, ingest-app/src/cmr/ingest/data/ingest_events.clj, ingest-app/src/cmr/ingest/services/jobs.clj, metadata-db-app/src/cmr/metadata_db/data/ingest_events.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, system-int-test/src/cmr/system_int_test/utils/metadata_db_util.clj, system-int-test/src/cmr/system_int_test/utils/url_helper.clj, system-int-test/test/cmr/system_int_test/ingest/granule_ingest_test.clj
Collections seems to work already with how mdb saves concepts, but for granules we needed a TTL solution.  I opted for adding a message when the cleanup job is run that tells indexer to un-index the expired granule.
=> CMR-6239 Investigate and Implement a Solution For 'Time To Live (TTL)' For Elasticsearch 7.5.2 Upgrade

collection-renderer-lib/project.clj
Installing reference to the latest version of the Preview Gem which incorporates:
MMT-2135 -- Fixed an alignment problem in the collection-title display.
MMT-1726   -- support UMM-C v1.15.
=> CMR-6270 -- updated references to latest  Preview Gem

access-control-app/int-test/cmr/access_control/int_test/access_control_group_crud_test.clj, access-control-app/src/cmr/access_control/services/group_service.clj
Preventing non-unique named groups during updates. This enforces the same behavior that is already implemented on creation.
=> CMR-6217 Enforcing group name uniqueness rule when updating groups

indexer-app/src/cmr/indexer/services/index_service.clj, system-int-test/test/cmr/system_int_test/search/autocomplete/suggestion_reindex_test.clj
Updated autocomplete indexing to be more resilient to parsing errors for badly formatted data. This will prevent the autocomplete from failing midway through a re-index operation.
The root issue is badly formatted data that was attempted to be parsed.
=> CMR-6295 catching parsing exceptions during autocomplete suggestion reindexing

resources/shell/cmr-bash-autocomplete
To test configure your shell to use zsh, source the `cmr` shell resource and verify cmr commands still work.
=> CMR-6117 updated cmr-bash-autocomplete to be compatible with zsh

common-app-lib/src/cmr/common_app/services/search/query_model.clj, common-app-lib/src/cmr/common_app/services/search/query_to_elastic.clj, elastic-utils-lib/src/cmr/elastic_utils/index_util.clj, indexer-app/src/cmr/indexer/data/index_set.clj, search-app/src/cmr/search/data/query_to_elastic.clj, search-app/src/cmr/search/models/query.clj, search-app/src/cmr/search/results_handlers/autocomplete_results_handler.clj, search-app/src/cmr/search/services/autocomplete_service.clj, system-int-test/src/cmr/system_int_test/utils/search_util.clj, system-int-test/test/cmr/system_int_test/search/autocomplete_collection_facet_search_test.clj
Autocomplete tests and code updated to be compatible with the updated version of elasticsearch
=> CMR-6318 updates for autocomplete for ES migration

ingest-app/src/cmr/ingest/services/jobs.clj
Was not correctly publishing events to the event queue. This fix changes how autocomplete trigger events are published.
=> CMR-6283 fixed event publishing for autocomplete indexing job

acl-lib/src/cmr/acl/core.clj, system-int-test/test/cmr/system_int_test/ingest/provider_ingest_permissions_test.clj, system-int-test/test/cmr/system_int_test/ingest/subscription_ingest_test.clj
Currently, the cache key is [token permission] in the cache. So for a given user, if it has permission on one provider, this user could get hits in the cache for other providers that the user is not granted permission. Also, this can potentially make the user wait for a long time for the correct permission to take effect - as long as there are hits(has permission) in the cache, regardless which provider(s) they are for, the user can't be taken away the permission using the ACL for the right provider.
=> CMR-6489: Add provider-id to ACL cache so that the permission given to the user can be provider dependent in the cache.

common-app-lib/src/cmr/common_app/api/routes.clj, ingest-app/src/cmr/ingest/routes.clj, search-app/src/cmr/search/routes.clj, system-int-test/test/cmr/system_int_test/header_test.clj
This rolls back @daniel-zamora's commits for CMR-5806 to fix the API doc page issue so that we can create a new release for UAT deployment. The code fix in these commits is good, but because it exposed some other issues on the api doc page and caused api doc page not loading correctly. We will roll this back so that we can create a release with the rest of fixes in Sprint 20.3.1 for UAT deployment.
=> CMR-5806 roll back

ingest-app/docs/api.md, ingest-app/src/cmr/ingest/api/core.clj, ingest-app/src/cmr/ingest/api/routes.clj, ingest-app/src/cmr/ingest/api/variables.clj, ingest-app/src/cmr/ingest/services/ingest_service/variable.clj, ingest-app/src/cmr/ingest/validation/validation.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/variable_save_test.clj, metadata-db-app/src/cmr/metadata_db/api/concepts.clj, metadata-db-app/src/cmr/metadata_db/services/concept_constraints.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, metadata-db-app/src/cmr/metadata_db/services/messages.clj, metadata-db-app/src/cmr/metadata_db/services/variable_association_validation.clj, metadata-db-app/src/cmr/metadata_db/system.clj, metadata-db-app/test/cmr/metadata_db/test/services/concept_service.clj, system-int-test/src/cmr/system_int_test/utils/ingest_util.clj, system-int-test/src/cmr/system_int_test/utils/url_helper.clj, system-int-test/src/cmr/system_int_test/utils/variable_util.clj, system-int-test/test/cmr/system_int_test/ingest/variable_ingest_test.clj, system-int-test/test/cmr/system_int_test/ingest/variable_ingest_with_association_test.clj, system-int-test/test/cmr/system_int_test/search/variable/variable_association_test.clj, system-int-test/test/cmr/system_int_test/search/variable/variable_search_test.clj, transmit-lib/src/cmr/transmit/search.clj
This PR is Part1 of several parts of the feature: Variable can not exist without association.
It covers the part that ingest the association at variable ingest time.  No update of the association, and no cascading delete of variables when associations are deleted.  
1. Copied/modified variable association related functions from search-app to metadata-db-app.
This is because we will retire the existing variable association endpoint.
2. Added :search-index component in metadata-db-app to allow execute-query when doing association validation.
3. Added perform-post-commit-association in try-to-save function. so that if the association fails, it'll rollback
the variable insert.
4. Modified the variable response to include variable-association and association-item, on top of concept-id and …
=> CMR-6597 Added feature to ingest association at variable ingest.

common-lib/src/cmr/common/test/runners/default.clj
This provides the ability to run unit test in parallel in CI and should cut down a little bit on the build time.
=> Make unit test run mode configurable.

cmr-exchange/exchange-query/project.clj, cmr-exchange/exchange-query/src/cmr/exchange/query/impl/cmr.clj, cmr-exchange/exchange-query/test/cmr/exchange/query/tests/unit/core.clj, cmr-exchange/exchange-query/test/cmr/exchange/query/tests/unit/util.clj, cmr-exchange/metadata-proxy/src/cmr/metadata/proxy/concepts/variable.clj, cmr-exchange/ous-plugin/src/cmr/ous/common.clj, cmr-exchange/ous-plugin/test/cmr/ous/tests/unit/util/query.clj
This PR:
removes any reference to variable alias as a search parameter to cmr, this parameter is no longer support due to 1.7 changes
updates failing tests and modifies current tests to interact with alias changes.
updates cmr-exchange query dependencies in order to do local builds but doesn't seem to affect CI, which I left in but can remove, we should open a ticket to update all of cmr-exchange dependencies
I couldn't find any instance in splunk where alias was actually used as a parameter to a query made to ous in prod, uat, or sit in the past 30 days, so I don't think this change is going to break any clients.
=> CMR-6458 Remove alias support and update var version to 1.7 in OUS

indexer-app/src/cmr/indexer/services/index_service.clj, search-app/src/cmr/search/services/autocomplete_service.clj, system-int-test/test/cmr/system_int_test/search/autocomplete/suggestion_reindex_test.clj
Suggestions are not being found when an autocomplete suggestion is not public but belongs to multiple groups. Updated the test to put the expected items into multiple groups and update the field to support patterned searches
=> CMR-6451: fix autocomplete ACL group id filtering

indexer-app/src/cmr/indexer/services/index_service.clj, indexer-app/test/cmr/indexer/test/services/index_service.clj
Failed nil-check assertions have been replaced by return values. Additionally catching empty-strings as anti-values.
=> CMR-6685 improved anti-value detection and error handling while re-indexing autocomplete suggestions

common-app-lib/src/cmr/common_app/services/search/parameter_validation.clj, search-app/docs/api.md, search-app/src/cmr/search/api/community_usage_metrics.clj, search-app/src/cmr/search/services/community_usage_metrics/metrics_service.clj, system-int-test/test/cmr/system_int_test/search/humanizer/community_usage_metrics_test.clj
This PR attempts to aggregate the varied values found in the community metrics humanizer.  There are entries where the Product value can be either a collections ShortName, EntryTitle or "ProductId" which is just EntryTitle + version, but they should all be under ShortName.  Version and Provider columns also have inaccurate values so the only column used to try to identify collections will be the Product column.  Introduces new parameter to either do the lookup on every entry, or to try and short cut by using ShortNames currently in the humanizer already.
=> CMR-6624 As the CMR, I want the community usage file we take from EMS to use collection shortname as the collection identifier

bootstrap-app/src/cmr/bootstrap/data/bulk_index.clj, indexer-app/src/cmr/indexer/services/index_service.clj
Fixed bulk indexing of deleted granules that are also expired.
Fixed bulk indexing of granules/tags to not try to index into all revisions index.
=> CMR-6731, CMR-6732

search-app/src/cmr/search/services/autocomplete_service.clj, search-app/test/cmr/search/test/services/autocomplete_service.clj
Authenticated requests to autocomplete are creating very large elasticsearch queries which are causing errors in UAT. This drastically reduced query size in SIT, and should alleviate the issues found in UAT
=> CMR-6727: dedupe group-ids in autocomplete requests

elastic-utils-lib/project.clj, elastic-utils-lib/src/cmr/elastic_utils/embedded_elastic_server.clj
Updated library version to use fix contained in https://github.com/testcontainers/testcontainers-java/pull/3159
=> CMR-6792 updated library to address docker breaking change

metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/cleanup_test.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/concept_delete_spec.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/delete_test.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/force_delete_test.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/search/variable_association_search_test.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/search/variable_search_test.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/utils/interface.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/utility.clj
Given the number of tests that need to be fixed before we retire the old variable and association endpoints, we're dividing up the task into several parts to show incremental progress.
=> CMR-6603: Fix tests using old variable(association) endpoints part 1.

metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/concept_save_spec.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/force_delete_test.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/variable_association_save_test.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/variable_save_test.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/utility.clj
This PR fixed more tests(from using old endpoint to using new endpoint) in CMR-6603, which will be closed. The remaining tests will be fixed as maintenance task through new tickets.
=> CMR-6603: Modified more tests from using old variable endpoint to new endpoint

search-app/src/cmr/search/services/community_usage_metrics/metrics_service.clj, system-int-test/test/cmr/system_int_test/search/humanizer/community_usage_metrics_test.clj
this PR attempts to address some product ids that weren't being processed in the csv file properly.  Some lines have values that take the form entry-title:version-id, so we split on : and take the entry-title for searching.
=> CMR-6747 Fixes product ids csv lines in usage metrics

collection-renderer-lib/project.clj
Includes changes to the service tab in how it renders service urls from the metadata
Includes changes to how the JS is compiled from MMT.  
Erich ran the changes in his build plan in Bamboo (green).
Verified the preview gem behaviors in local CMR repl.
=> CMR-6751 Updating preview gem commit ref

search-app/src/cmr/search/results_handlers/opendata_results_handler.clj, search-app/test/cmr/search/test/results_handlers/opendata_results_handler.clj
Changed the rules on how NGDA tags are added to the opendata output. This change adds instrument data to the metadata used by the open data results handler. These values are then used to drive the inclusion of the NGDA tags. Instruments are not included in the opendata output.
=> CMR-6257 - NGDA Tags

indexer-app/src/cmr/indexer/data/concepts/collection.clj, system-int-test/test/cmr/system_int_test/search/tool/collection_tool_search_test.clj
Collection's has-formats flag should only be used  to specify if the associated services can do re formatting.
=> CMR-6873: Removed tool's has-formats impact.

README.md, common-app-lib/src/cmr/common_app/site/data.clj
A `grep` shows that the old link is contained in many various apps in HTML files, but my gut says that those should be rectified by this change.
* updated partner-url in common-app-lib
* updated main README
=> CMR-6719: Updated client partner user guide link

search-app/docs/api.md, search-app/src/cmr/search/results_handlers/atom_results_handler.clj
xmlns:dc="http://purl.org/dc/elements"
As per page 17 of the CEOS OpenSearch Best Practices: 
http://ceos.org/document_management/Working_Groups/WGISS/Interest_Groups/OpenSearch/CEOS-OPENSEARCH-BP-V1.2.pdf
* Updated the namespace
This PR is in tandem with https://github.com/nasa/cmr-opensearch/pull/51
=> CMR-6764: Updated dc namespace to reflect CEOS OpenSearch best practices

search-app/test/cmr/search/test/services/humanizers/humanizer_range_facet_service.clj
When I merged CMR-6783 a test failed in Bamboo - so I commented it out.  Since then it failed once, but passed twice and I don't know why.  I moved the test up in the file so that it would be run first thinking that maybe its a caching thing in Bamboo.  I am running a full build one more time to see if it will build correctly. The last three additional builds that I did all tests passed. The test itself hasn't changed and it is passing so I want to add it back in.
=> CMR-6890 moved a test up.

common-lib/project.clj
This PR updates the quartzite library to my own version.  The current release of quartzite uses an older library of quartz, whose version needs updating per CMR-6759.  However, the maintainer of the https://github.com/michaelklishin/quartzite repo has not updated the underlying quartz library and seems to indicate in a response to this issue, https://github.com/michaelklishin/quartzite/issues/26, that he will not in the future.
In order to resolve this, I cloned the repo cited in this PR https://github.com/michaelklishin/quartzite/pull/39, which updates the quartz version to 2.3.1 and fixes any broken code,  to my own project https://github.com/daniel-zamora/quartzite.  I updated to quartz to version 2.3.2 then deployed my own jar to clojars. 
I have asked for the PR, cited above, to be …
=> CMR-6749 updates quartzite library

ingest-app/src/cmr/ingest/api/subscriptions.clj, system-int-test/test/cmr/system_int_test/ingest/subscription_ingest_test.clj
Bypass ACLs if the requesting user is the same as the one the subscription is for
=> CMR-6623 - bypassing ACLs

search-app/docs/api.md, search-app/src/cmr/search/results_handlers/atom_results_handler.clj
It was updated to http://purl.org/dc/elements/, but should have been updated to http://purl.org/dc/elements/1.1
=> CMR-6764: Fixed DC namespace to accurately reflect CEOS best practices

system-int-test/test/cmr/system_int_test/search/tool/tool_search_test.clj
The two RevisionDate sorting tests used to fail ONLY when running them locally in the test suites. Now the failures can no longer be reproduced.  So the two tests are uncommented out. If it fails again locally in the future, we might want to introduce some delays in between the Tool ingests so that their RevisionDate can be more distinguished.
=> CMR-6444: Uncommented out the 2 RevisionDate sort tests.

ingest-app/src/cmr/ingest/validation/validation.clj, system-int-test/test/cmr/system_int_test/ingest/collection_keyword_validation_test.clj
When GetData is missing from RelatedUrl, common-app lib couldn't handle the nil case when lookup kms keyword. Fixed the 500 error by making sure we don't pass a nil value to the common-app normalize-for-lookup function.
=> CMR-6901: Fixed the 500 error when GetData component is missing in RelatedUrl

access-control-app/tests.edn, acl-lib/tests.edn, bootstrap-app/tests.edn, collection-renderer-lib/tests.edn, common-app-lib/tests.edn, common-lib/tests.edn, dev-system/tests.edn, elastic-utils-lib/tests.edn, es-spatial-plugin/tests.edn, indexer-app/tests.edn, ingest-app/tests.edn, message-queue-lib/tests.edn, metadata-db-app/tests.edn, mock-echo-app/tests.edn, oracle-lib/tests.edn, orbits-lib/tests.edn, redis-utils-lib/tests.edn, schema-validation-lib/tests.edn, search-app/tests.edn, search-relevancy-test/tests.edn, spatial-lib/tests.edn, system-int-test/tests.edn, transmit-lib/tests.edn, umm-lib/tests.edn, umm-spec-lib/tests.edn, virtual-product-app/tests.edn
Generate codecov.json reports to use with CI buidls instead of HTML reports during CI builds.
Also set reporter to be documentation for all builds for consistency.
=> CMR-7042 Generate codecov reports

indexer-app/src/cmr/indexer/services/event_handler.clj, metadata-db-app/src/cmr/metadata_db/data/ingest_events.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/search.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj
1.  Publishing all associations in one event, rather than one event for each association.
2. Got rid of the nested query when searching for service associations. (backed it out because not enough testing time in UAT to conclude it's faster even though it's supposed to be)
3. The code is done in a way that could make use of the existing publishing code with minimal code change. i.e. still use the :action, :concept-id and :revision-id in the event, which is used by a lot of places during publishing, and put the rest of the associations in :more-concepts which don't need to be touched until the event handler handles it.
4. Existing tests already covered the functionality in collection_service_search_test.clj. If the associations are not published correctly, the tests will fail.
=> CMR-7030: Tried to further improve the service ingest performance

search-app/src/cmr/search/services/query_execution/granule_counts_results_feature.clj, search-app/src/cmr/search/site/data.clj, system-int-test/test/cmr/system_int_test/site/holdings_provider_test.clj
Here are changes from both Yiduo (mostly her actually) and some changes by me to get two tests to pass. If you reviewed the pull request from her github fork, what is different here is at line 103 in the file search-app/src/cmr/search/site/data.clj where changes were made to handle the flow when no collections are found. A corresponding changes is at line 140 of the same file. Together these changes allowed existing changes to pass.
=> Cmr-7050 Provider Holding Dir - Display just online_only granule count

ingest-app/docs/api.md, ingest-app/src/cmr/ingest/api/subscriptions.clj, ingest-app/src/cmr/ingest/system.clj, mock-echo-app/src/cmr/mock_echo/api/urs.clj, system-int-test/test/cmr/system_int_test/ingest/subscription_ingest_test.clj, transmit-lib/src/cmr/transmit/urs.clj, umm-spec-lib/resources/json-schemas/subscription/umm/v1.0/umm-sub-json-schema.json
* SubscriberID is now an optional subscription field
* If no SubscriberID is supplied, the user associated with the token will be used
* EmailAddress is now an optional subscription field
* If no EmailAddress is supplied, the email associated with the user in URS (Earthdata Login) will be used
* Added tests for these optional cases
=> CMR-6931: SubscriberID and EmailAddress are now optional subscription fields

metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/subscription.clj, system-int-test/test/cmr/system_int_test/ingest/subscription_processing_test.clj
* Added after-save function to check if the subscription was just tombstoned, and deleted the sub-notification if so
* Added test case for this functionality
=> CMR-6633: Purge Sub-Notification from Metadata DB after Subscription is tombstoned

ingest-app/src/cmr/ingest/api/bulk.clj, ingest-app/src/cmr/ingest/api/routes.clj, ingest-app/src/cmr/ingest/data/bulk_update.clj, ingest-app/src/cmr/ingest/data/granule_bulk_update.clj, ingest-app/src/cmr/ingest/data/memory_db.clj, ingest-app/src/cmr/ingest/migrations/012_update_index_bulk_update_gran_status.clj, ingest-app/src/cmr/ingest/services/granule_bulk_update_service.clj, system-int-test/src/cmr/system_int_test/utils/ingest_util.clj, system-int-test/src/cmr/system_int_test/utils/url_helper.clj, system-int-test/test/cmr/system_int_test/ingest/granule_bulk_update/granule_bulk_update_flow_test.clj, system-int-test/test/cmr/system_int_test/ingest/granule_bulk_update/granule_bulk_update_test.clj
This PR adds support to retrieve granule bulk update task status and detailed task status for a given task. This also completes the granule bulk update integration tests with the full granule level verification and error handling.
See PR: https://github.com/nasa/Common-Metadata-Repository/pull/1196 for the API description, sample requests and responses.
=> CMR-7092, CMR-7210

common-app-lib/src/cmr/common_app/services/search/query_model.clj
Resolves an issue in access-control where a multi-method has no definition for sorting collections. The definition for collections is defined in search-app, but access control does not have search as a dependency.
=> CMR-7080 default sorting keys

common-app-lib/src/cmr/common_app/config.clj, search-app/docs/api.md, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, system-int-test/test/cmr/system_int_test/search/granule_counts_search_test.clj
* Changed default configured tag for has_granules_or_cwic
* Also added has_granules_or_opensearch as aliased parameter
* Added new tests
* has_granules_or_cwic will be retired in the future
=> CMR-7216: Implemented has_granules_as_opensearch as alias of has_granules_or_cwic

search-app/resources/templates/stac-search-docs.html
Currently stac docs link and stac static catalog links are not decided yet. We want to remove them from CMR Search Landing Page before CMR-7086 goes to PROD.
=> CMR-7086: Remove the placeholder for not working stac links.

collection-renderer-lib/README.md, common-app-lib/src/cmr/common_app/api/launchpad_token_validation.clj, common-app-lib/test/cmr/common_app/test/api/launchpad_token_validation_tests.clj, system-int-test/test/cmr/system_int_test/admin/cache_api_test.clj
Improved the Launchpad test by adding checks for several of the different types of ECHO and EDL tokens.
Legacy Tokens: Old style ECHO tokens
Heritage Tokens: New tokens made to function like legacy tokens, but are identifiable.
JWT Tokens: Long, parsable tokens
=> CMR-6932 - JWT and Heritage token support

ingest-app/resources/granule_bulk_update_schema.json, ingest-app/src/cmr/ingest/services/granule_bulk_update/opendap/opendap_util.clj, ingest-app/src/cmr/ingest/services/granule_bulk_update_service.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_granule_update_schema_test.clj, system-int-test/test/cmr/system_int_test/ingest/granule_bulk_update/granule_bulk_update_schema_test.clj, system-int-test/test/cmr/system_int_test/ingest/granule_bulk_update/granule_bulk_update_test.clj
Would like some additional feedback about the format of the error messages returned by the JSON schema validation library. Specifically the "#/updates/2" referring to the instruction level schema. Should they be transformed into something more readable or fine as-is?
=> CMR-7191 update bulk granule update schema to have stricter rules

browse-scaler/src/docker-compose.test.yml
The report was being generated but was not available outside the docker container. This publishes the coverage directory to the CI agent when tests are run.
=> CMR-6975 Make the browse-scaler coverage report available to CI tools

common-lib/src/cmr/common/xml/simple_xpath.clj, common-lib/test/cmr/common/test/xml/simple_xpath.clj, umm-spec-lib/resources/example-data/special-case-files/CMR-7250-Mix-WMO-And-ScienceKeywords.xml, umm-spec-lib/src/cmr/umm_spec/iso_keywords.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_smap.clj, umm-spec-lib/test/cmr/umm_spec/test/iso_keywords.clj
Clarification:
1. This change applies to iso19115 only. isosmap shouldn't be impacted.
2. ScienceKeywords for iso19115 should be the descriptiveKeywords with "theme" keyword type (current behavior)
AND with gmd:thesaurusName's CharacterString value including "GCMD".  (new feature)  This is because NOAA uses the same type of theme for their Science keywords, as well as their WMO keywords.
3. We should get the values from both gco:CharacterString(current behavior) and gmx:Anchor (new feature)
=> Cmr 7250 index wrong gcmd science keywords

indexer-app/src/cmr/indexer/data/concepts/keyword_util.clj, indexer-app/test/cmr/indexer/test/data/concepts/keyword_util.clj, indexer-app/test/cmr/indexer/test/data/concepts/service_keyword_util.clj, system-int-test/test/cmr/system_int_test/search/collection_keyword_search_test.clj
This solves an issue where keywords such as `(TMPA-RT)` were decomposed into `["(TMPA-RT)", "tmpa", "rt"]` which prevents keyword searching for `TMPA-RT` since elasticsearch doesn't return inexact matches. To solve this, we add all existing keywords like before, but also as the contents of parens or brackets as well, if applicable - for example, in the above case, the new set of keywords would be `["(TMPA-RT)", "tmpa-rt", "tmpa", "rt"]`.
=> CMR-7214: Add support for additional keyword searching

common-lib/project.clj
The last bump turned out to be insufficient; another minor version bump is needed.
Thankfully, this one does not require any matching Legacy Services changes - the builds are already green.
=> CMR-7318: Minor Jetty version bump

.gitignore, indexer-app/src/cmr/indexer/data/concepts/collection.clj, indexer-app/src/cmr/indexer/data/concepts/tag.clj, indexer-app/src/cmr/indexer/data/index_set.clj, indexer-app/test/cmr/indexer/test/data/concepts/tag.clj, search-app/docs/api.md, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, system-int-test/test/cmr/system_int_test/search/collection_cloud_hosted_search_test.clj
Add a cloud_hosted search parameter to search_app to find records that have a DirectDistributionInformation URL or are still being tagged with the gov.nasa.earthdata.cloud.s3 URL.
=> CMR-7220: cloud_hosted search

indexer-app/src/cmr/indexer/data/concepts/tag.clj, indexer-app/test/cmr/indexer/test/data/concepts/tag.clj, search-app/docs/api.md
Production uses a different tag (dropping a period between data and cloud) then was used in development, so updating tag to match what production will be using. Also improving api documentation to match what similar parameters say.
=> cmr-7220 follow up: changed tag, updated api doc

access-control-app/int-test/cmr/access_control/int_test/acl_crud_test.clj, access-control-app/src/cmr/access_control/api/routes.clj
Clarification: Access code does validate json at ingest. If the json body is malformed, you will get Invalid Json error, if it misses required fields, you will get Validation error. However, in this ticket, the extra "," is not considered to be  the cases above. It's throwing com.fasterxml.jackson.core.JsonParseException during the parsing of the json body.
=> Cmr 6026 validate json at acl ingest

ingest-app/docs/api.md, ingest-app/resources/granule_bulk_update_schema.json, ingest-app/src/cmr/ingest/services/granule_bulk_update/opendap/echo10.clj, ingest-app/src/cmr/ingest/services/granule_bulk_update/opendap/opendap_util.clj, ingest-app/src/cmr/ingest/services/granule_bulk_update/opendap/umm_g.clj, ingest-app/src/cmr/ingest/services/granule_bulk_update/s3/echo10.clj, ingest-app/src/cmr/ingest/services/granule_bulk_update/s3/umm_g.clj, ingest-app/src/cmr/ingest/services/granule_bulk_update_service.clj, ingest-app/test/cmr/ingest/services/granule_bulk_update/opendap/echo10_test.clj, ingest-app/test/cmr/ingest/services/granule_bulk_update/opendap/umm_g_test.clj, ingest-app/test/cmr/ingest/services/granule_bulk_update/s3/echo10_test.clj, ingest-app/test/cmr/ingest/services/granule_bulk_update/s3/umm_g_test.clj, system-int-test/test/cmr/system_int_test/ingest/granule_bulk_update/granule_bulk_update_schema_test.clj, system-int-test/test/cmr/system_int_test/ingest/granule_bulk_update/granule_bulk_update_test.clj, system-int-test/test/cmr/system_int_test/ingest/granule_ingest_test.clj
New APPEND_TO_FIELD operation
* if no S3 link data exists creates and adds, (identical to UPDATE_FIELD)
* if new urls are unique, will add new S3 links, preserving existing
Because no more than 1 url of type cloud and 1 url of type on-prem may exist. behavior of APPEND_TO_FIELD is as follows
* if URL type is not present it will be added
* fails if existing type is present
=> CMR-7235 APPEND_TO_FIELD operator for bulk granule update

ingest-app/docs/api.md, ingest-app/src/cmr/ingest/api/bulk.clj, ingest-app/src/cmr/ingest/api/routes.clj, ingest-app/test/cmr/ingest/api/bulk.clj, ingest-app/test/cmr/ingest/api/bulk_test.clj, system-int-test/src/cmr/system_int_test/utils/ingest_util.clj, system-int-test/test/cmr/system_int_test/ingest/granule_bulk_update/granule_bulk_update_flow_test.clj, system-int-test/test/cmr/system_int_test/ingest/granule_bulk_update/granule_bulk_update_test.clj
Recognize three new query parameters on the `ingest/granule-bulk-update/status/:task-id` endpoint: `show_progress`, `show_request`, and `show_granules`. Details on these parameters effect are found in the updated `api.md`
=> CMR-7354: Allow requester to specify verbosity of bulk granule update task status

common-app-lib/src/cmr/common_app/services/search/query_to_elastic.clj, elastic-utils-lib/src/cmr/elastic_utils/index_util.clj, indexer-app/src/cmr/indexer/data/concepts/collection.clj, indexer-app/src/cmr/indexer/data/concepts/collection/keyword.clj, indexer-app/src/cmr/indexer/data/concepts/keyword_util.clj, indexer-app/src/cmr/indexer/data/index_set.clj, search-app/docs/api.md, search-app/src/cmr/search/data/query_to_elastic.clj, search-app/src/cmr/search/services/query_walkers/keywords_extractor.clj, system-int-test/test/cmr/system_int_test/search/collection_highlights_search_test.clj, system-int-test/test/cmr/system_int_test/search/collection_keyword_search_test.clj
For some reason I merged my fix for CMR-7380 to nasa:CMR-7380-keyword-search-on-phrase, instead of nasa:master.  There are some changes to the files since I merged. To avoid conflict and possible errors. I think it's safer to create another branch and go through PR again to merge to master
=> CMR-7380: Exact same changes as in CMR-7380-keyword-search-on-phrase

access-control-app/Dockerfile, access-control-app/src/cmr/access_control/test/bootstrap.clj, acl-lib/src/cmr/acl/acl_fetcher.clj, bootstrap-app/Dockerfile, bootstrap-app/src/cmr/db.clj, common-lib/src/cmr/common/jobs.clj, common-lib/src/cmr/common/system.clj, dev-system/Dockerfile, dev-system/README.md, indexer-app/Dockerfile, ingest-app/Dockerfile, ingest-app/src/cmr/db.clj, ingest-app/src/cmr/ingest/api/routes.clj, metadata-db-app/Dockerfile, metadata-db-app/src/cmr/db.clj, mock-echo-app/Dockerfile, search-app/Dockerfile, virtual-product-app/Dockerfile
Adding better error handling to initializing a clean system bootstrapping by catching certain errors that occur when first running a system. This allows systems to come up when the database has not been initialized yet.
=> CMR-7248 Not halting system when scheduler cannot start

virtual-product-app/src/cmr/virtual_product/data/source_to_virtual_mapping.clj
Due to a version-id mismatch between the source granule and the virtual granule, CMR was unable to properly translate the granule-urs.
=> CMR-7456 Fixes virtual granule to source granule ur translation for AST_L1T.031

common-app-lib/src/cmr/common_app/api/launchpad_token_validation.clj, common-app-lib/test/cmr/common_app/test/api/launchpad_token_validation_tests.clj, ingest-app/src/cmr/ingest/api/core.clj
This captures granules, collections, and more.
=> CMR-7448: Add token type to successful ingest logging

ingest-app/docs/api.md, ingest-app/resources/CMR-4722/OMSO2.003-granule-checksum.xml, ingest-app/resources/CMR-4722/OMSO2.003-granule-no-checksum.xml, ingest-app/resources/CMR-4722/OMSO2.003-granule-no-data-granule.xml, ingest-app/resources/granule_bulk_update_schema.json, ingest-app/src/cmr/ingest/services/granule_bulk_update/checksum/echo10.clj, ingest-app/src/cmr/ingest/services/granule_bulk_update_service.clj, ingest-app/test/cmr/ingest/services/granule_bulk_update/checksum/echo10_test.clj, system-int-test/test/cmr/system_int_test/ingest/granule_bulk_update/granule_bulk_update_test.clj
* Targets XML element at `Granule/DataGranule/Checksum/<Value/Algorithm>
* If one value is supplied, only value is updated. If two values are supplied, they are assigned to value and algorithm respectively
* If the granule has no `<DataGranule>` element, then the update fails.
=> CMR-7506: Bulk Granule Update for Checksum in ECHO10

ingest-app/docs/api.md, ingest-app/src/cmr/ingest/api/collections.clj, ingest-app/src/cmr/ingest/config.clj, ingest-app/src/cmr/ingest/services/ingest_service/collection.clj, ingest-app/src/cmr/ingest/validation/business_rule_validation.clj, ingest-app/src/cmr/ingest/validation/validation.clj, system-int-test/src/cmr/system_int_test/data2/core.clj, system-int-test/src/cmr/system_int_test/utils/ingest_util.clj, system-int-test/test/cmr/system_int_test/ingest/collection_progressive_update_test.clj
Ingest validations include 3 parts: 1. Schema validation, 2. umm-spec collection validation 3. Business rule validation.  Out of these 3 validations, we now allow the users to update a collection with #2 and #3 validation errors, if these errors exist in the previous revision collection. If new validation errors are introduced, the update will fail. Updates with schema validation errors, existing or new, will always fail.
=> Cmr 7489 progressive collection update

common-lib/src/cmr/common/util.clj, transmit-lib/src/cmr/transmit/echo/tokens.clj
For context - Legacy-Services used to emit the token into the logs outright, but those were redacted for security purposes. Due to the restrictive rails 3 build these were emitted under, a partially-redacted solution was unattainable. So, instead, we will log this info from the CMR side.
=> CMR-7450: As a CMR Operator, I need the logs to emit enough identifying token information to help with troubleshooting

transmit-lib/src/cmr/transmit/kms.clj, transmit-lib/test/cmr/transmit/test/kms.clj
Adding code to change the "version" parameter used when sending requests to KMS in SIT and UAT and preserving the old way for production.
=> ENV specific KMS URLs

common-app-lib/src/cmr/common_app/services/kms_fetcher.clj, system-int-test/test/cmr/system_int_test/search/keyword_endpoint_test.clj
The interface `http://localhost:3003/keywords/related_urls?pretty=true` now displays a three level keyword: `url_content_type->type->subtype`. url_content_type was added. A test was added as well to confirm this.
=> adding a third level to the keyword output of related urls

ingest-app/docs/api.md, ingest-app/src/cmr/ingest/data/granule_bulk_update.clj, system-int-test/test/cmr/system_int_test/ingest/granule_bulk_update/granule_bulk_update_flow_test.clj
task-id is a string that stores numbers.  We want the latest tasks to be returned on top, so we need add order by to the select statement to make sure it's in desc order, as a number.
=> Cmr 7221 tasks returned in desc order

ingest-app/resources/CMR-7636/iso19115_test_data.xml, system-int-test/test/cmr/system_int_test/ingest/collection_translation_test.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso19115_2/data_contact.clj
The original iso19115 collection ingests successfully even though it misses several required umm-json keys.
When translating from iso19115 to umm-json, all the missing required keys should be added because sanitize? is set to true. 
Testing showed all the missing required keys were added except for DataCenters. This is because there is a bug in the code when checking if DataCenters is missing from the original metadata. After the fix, DataCenters showed up and the resulted umm-json collection was ingested successfully.
=> CMR-7636: Fixed DataCenters translation from iso19115 to umm-json.

access-control-app/src/cmr/access_control/services/acl_service.clj, system-int-test/test/cmr/system_int_test/access_control/s3_bucket_route_test.clj
This PR attempts address issue where bucket lists in metadata are ingested as a single json string array.  We want the buckets/prefixes to be returned in a consistent manner even when this is the case.  It might be better to add validation to prevent these type of values in the metadata, or ask data providers to refrain from ingesting values in this way.  This howerver fixes how the data, that currently exists, is returned.
=> CMR-7416 fixes single string multi bucket lists, adds tests

indexer-app/src/cmr/indexer/data/concepts/collection.clj, indexer-app/src/cmr/indexer/data/concepts/collection/keyword.clj, indexer-app/src/cmr/indexer/data/concepts/keyword_util.clj, indexer-app/src/cmr/indexer/data/elasticsearch.clj, indexer-app/test/cmr/indexer/test/data/concepts/keyword_util.clj
Excessively long values in elasticsearch exceeded the maximum byte length supported by the text field type and could not be indexed. 
* Update how keywords are generated by changing the parsing of groups
* Split very long terms apart
* Truncate very long text values and warn when doing so
=> CMR-7841 fixing inability to index very long fields in elasticsearch for keyword field

ingest-app/src/cmr/ingest/api/subscriptions.clj, ingest-app/src/cmr/ingest/services/subscriptions_helper.clj, system-int-test/test/cmr/system_int_test/ingest/subscription_ingest_test.clj
This change limits the number subscriptions an individual user can create to 100 active subscriptions. If the user is already at the subscription limit, they will not be able to successfully create a new subscription. This will help prevent undue load or abuse. The tests validate a user can create subscriptions if they are below the limit and that they will be rejected if they are already at the limit.
=> CMR-6928 Subscription limit validation and tests

common-lib/src/cmr/common/cache/in_memory_cache.clj, common-lib/test/cmr/common/test/cache/in_memory_cache.clj
`clojure.lang.PesistentArrayVectors` and `clojure.lang.PersistentArrayMap` as cache keys were not being handled correctly in the job logging cache sizes. This PR corrects that problem.
=> CMR-7862 updates to handle other key types for cache info jobs

indexer-app/src/cmr/indexer/services/autocomplete.clj, indexer-app/src/cmr/indexer/services/index_service.clj, indexer-app/test/cmr/indexer/test/services/index_service.clj
and can change for a list of providers that have large records.
=> Cmr 8073 - Changing the autocomplete and reindexing batch size to be operationally configurable 

system-validation-test/Gemfile.lock, system-validation-test/README.md, system-validation-test/features/ingest_basic.feature, system-validation-test/features/step_definitions/data_comparison_steps.rb, system-validation-test/features/step_definitions/rest_steps.rb
This change creates new tests in system-validation-tests to test the ingest of a collection, searching for the collection, and then deleting the collection to help verify data flow in CMR so new changes do not break CMR.
=> CMR-8021 Create an ingest test to be part of the system-validation-tests

system-validation-test/features/ingest_basic.feature, system-validation-test/features/step_definitions/rest_steps.rb
This enhancement makes changes from CMR-8021 which fix the response requests to function properly both in SIT and local environments.
Parent:
[CMR-8021](https://github.com/nasa/Common-Metadata-Repository/pull/1487): [created new validation tests in system-validation-tests to perform an ingest operation to verify data-flow in CMR so new changes do not break CMR.](https://github.com/nasa/Common-Metadata-Repository/pull/1487)
=> CMR-8021-2 Enhancement to 8021: Create an ingest test to be part of the system-validation-tests

tea-config-generator/README.md, tea-config-generator/handler.py, tea-config-generator/run.sh, tea-config-generator/serverless-sandbox.yml, tea-config-generator/serverless.yml, tea-config-generator/tea/gen/get_acls.py
When trying to publish to sit, it was found that NGAP could not configure a path to point to an API Gatway application. serverless.yml was changed to instead publish to the CMR application load balancer. The path parameter code had to change as no way exists to setup a lambda path parameter in the load balancer.
To support sandbox which does not have a load balancer, a new configuration was created which should look like the old solution.
=> MMT-2813 - Changing TEA config gen. from API Gateway to Application Load Balancer

transmit-lib/src/cmr/transmit/kms.clj
updating log so that ops can observe and confirm the override setting without needed to ask for help
=> CMR-8093 - Update a KMS log

common-app-lib/project.clj, common-lib/project.clj, elastic-utils-lib/project.clj, schema-validation-lib/project.clj
This is to address the Snyk vulnerabilities reported at internal libraries.
=> CMR-8143: Removed jackson-databind dependency from common libs.

search-app/docs/api.md, search-app/src/cmr/search/api/concepts_search.clj, search-app/src/cmr/search/results_handlers/stac_results_handler.clj, search-app/src/cmr/search/services/url_helper.clj, search-app/test/cmr/search/test/results_handlers/stac_results_handler.clj, system-int-test/src/cmr/system_int_test/data2/stac.clj, system-int-test/test/cmr/system_int_test/search/granule_search_format_test.clj
This PR allows for search-app concept search endpoint returning a stac format to use POST requests with parameters that are equivalent to GET requests with the same parameters.  This does not include JSON queries.
=> CMR-8119 Adds POST/parameter search for stac format

search-app/src/cmr/search/services/community_usage_metrics/metrics_service.clj, system-int-test/test/cmr/system_int_test/search/collection_relevancy/collection_relevancy_test.clj, system-int-test/test/cmr/system_int_test/search/collection_relevancy/collection_usage_relevancy_test.clj, system-int-test/test/cmr/system_int_test/search/collection_sorting_search_test.clj, system-int-test/test/cmr/system_int_test/search/humanizer/community_usage_metrics_test.clj, system-int-test/test/cmr/system_int_test/search/humanizer/humanizer_community_usage_int_test.clj, transmit-lib/src/cmr/transmit/http_helper.clj
1. Current EMS usage data is reported with columns `Provider,Product,ProductVersion,Hosts` contrary to how the codebase and tests were using/anticipating `Provider,Product,Version,Hosts`.  This was changed sometime between 5 and 2 years ago.  The side-effect of this column renaming is that count-aggregations were done by short-name only.  Tests did not pick up this change because their dummy data still worked and there were no runtime errors because the endpoint was built in such a way as to handle a missing version column.
- All dummy data updated to reflect new column headers
- Reverted some changes in CMR-8138 that had removed references to the Version.
- Added an additional header validation to ensure that if the Version column changes in the future we'll be aware.
2. Version length …
=> CMR-8138-1: Update references to Version column to ProductVersion

system-int-test/src/cmr/system_int_test/data2/umm_spec_subscription.clj, system-int-test/src/cmr/system_int_test/utils/subscription_util.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/subscriptions_test.clj, system-int-test/test/cmr/system_int_test/ingest/subscription_ingest_test.clj, umm-spec-lib/resources/json-schemas/subscription/umm/v1.1/umm-sub-json-schema.json, umm-spec-lib/resources/json-schemas/subscription/umm/v1.1/umm-sub-search-results-json-schema.json, umm-spec-lib/src/cmr/umm_spec/metadata_specification.clj, umm-spec-lib/src/cmr/umm_spec/migration/version/subscription.clj, umm-spec-lib/src/cmr/umm_spec/models/umm_subscription_models.clj, umm-spec-lib/src/cmr/umm_spec/versioning.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version/subscription.clj
Update the UMM Subscription Schema in preparation for collection subscriptions.
1. Added the `Type` field.  Accepts values `granule` or `collection`
2. Removed the requirement for `CollectionConceptId` as it will be empty in `collection` subscriptions
3. Added `MetadataSpecification`
=> CMR-7215: Create UMM-Sub Schema v1.1, adding Type field

umm-spec-lib/src/cmr/umm_spec/migration/version/core.clj
Due to deployment differences between the dev and production systems, this import has been missing for some time (wasn't necessary due to only having 1 schema version).
=> CMR-8216: UMM-Sub items should be migrated based on Accept header

search-app/docs/api.md, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, system-int-test/test/cmr/system_int_test/search/collection_standard_product_search_test.clj, umm-spec-lib/resources/xml-schemas/echo10/Collection.xsd, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/echo10.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/echo10.clj
This PR included the fix for CMR-8132 because the ingest in this test needs to index the collection in echo10 format. If StandardProduct is not translated, it can't be indexed.
=> CMR-8129: Added StandardProduct search parameter.

system-int-test/test/cmr/system_int_test/ingest/subscription_ingest_test.clj
This change creates new tests to verify that a user with valid permissions can perform a delete on a collection subscription.
=> CMR-8170 Create tests to verify user can delete collection subscriptions with valid permissions

access-control-app/src/cmr/access_control/config.clj, access-control-app/src/cmr/access_control/services/acl_validation.clj, access-control-app/src/cmr/access_control/services/auth_util.clj, mock-echo-app/src/cmr/mock_echo/api/urs.clj, system-int-test/test/cmr/system_int_test/access_control/edl_group_test.clj, transmit-lib/src/cmr/transmit/http_helper.clj, transmit-lib/src/cmr/transmit/urs.clj
This PR allows user groups in EDL to be used as SIDs for CMR permissions.
=> CMR-7735 Adds EDL SIDs lookup

indexer-app/src/cmr/indexer/data/concepts/subscription.clj, search-app/docs/api.md
CMR-8279-2 is an enhancement to [CMR-8279](https://github.com/nasa/Common-Metadata-Repository/pull/1582) to fix the `type` field for deleted subscriptions and update the API docs to reflect the new field.
=> CMR-8279-2 Added subscription-type to be returned from JSON response enhancement

mock-echo-app/src/cmr/mock_echo/api/urs.clj, system-int-test/test/cmr/system_int_test/access_control/edl_group_test.clj, transmit-lib/src/cmr/transmit/urs.clj
Currently EDL groups are unique via the combination of name and tag, so when saving them to ACLs we need to concat both around a ":".   Grabbing SIDs therefore must also assume this convention.
=> CMR-8334 Updates CMR to take EDL group tags into account.

metadata-db-app/src/cmr/metadata_db/migrations/080_add_generic_document_table.clj
Adding the native-id back into the table.
If you have used the previous version of this migration, then you will need to run (down) function.
=> CMR-8379 - renaming migration file and restoring native id

search-app/src/cmr/search/services/community_usage_metrics/metrics_service.clj, system-int-test/test/cmr/system_int_test/search/humanizer/community_usage_metrics_test.clj
The access counts are now parsed as a long in the community metrics file, handling the scenario of the access counts being too large for an integer.
=> CMR-7857 Fix issue with community metrics CSV parsing

metadata-db-app/src/cmr/metadata_db/migrations/080_add_generic_document_table.clj
* CMR-8379 - this change is a copy of the database table used by the generic system. This pull request is to get the database in master before all the other code so that the development team does not have to keep renaming the migration file every time another team makes a database change. This table is also needed by other efforts such as at the effort to create a simplified association table.
This table is much like other concept tables. Document name is to be made unique by code and may have rules that change for each document type.
Native-id is assumed to be unique by provider.
=> CMR-8379 - Create the Generic Document Table

bootstrap-app/README.md, bootstrap-app/src/cmr/bootstrap/api/bulk_index.clj, bootstrap-app/src/cmr/bootstrap/data/bulk_index.clj, bootstrap-app/src/cmr/bootstrap/services/bootstrap_service.clj
This PR provides the ability to resume a prematurely terminated bulk index collection request from where it left off rather than have to always start from the very beginning.
=> CMR-8541: As a CMR operator, I would like to bulk index a collection with a start_index parameter.

common-lib/src/cmr/common/config.clj, common-lib/src/cmr/common/generics.clj
These changes include just the feature toggle from the new document pipeline prototype, which is set by an environment variable that also serves as the list of approved document types. Also in these changes is a log info line that is activated when the environment variable is set. (If not set, it should default to an empty string and thus not trigger the log.)
=> CMR-8376: Add feature toggle from new generic document pipeline

Generics.md, bin/cmr, bin/functions/setup.sh, dev-system/dev/user.clj, ingest-app/src/cmr/ingest/api/generic_documents.clj, schemas/DataQualitySummary/v1.0.0/metadata.json, schemas/DataQualitySummary/v1.0.0/schema.json, schemas/Grid/v0.0.1/index.json, schemas/Grid/v0.0.1/metadata.json, schemas/Index/v0.0.1/metadata.json, schemas/OrderOption/v1.0.0/metadata.json, schemas/OrderOption/v1.0.0/schema.json, schemas/README.md, schemas/ServiceEntry/v1.0.0/metadata.json, schemas/ServiceEntry/v1.0.0/schema.json, schemas/ServiceOption/v1.0.0/metadata.json, schemas/use-info.md, system-int-test/test/cmr/system_int_test/ingest/generics_test.clj
Changes to support automatic updates of EMFD schemas if these schemas have been populated in the schemas directory. Developers must still update this directory, but once updated, `cmr setup dev` or `(user/reset)` will copy these files to all applications that need them.
Schema changes are in a separate commit, code changes are in the other(s).
=> (Pipeline Feature Branch) CMR-8569 support distribution of EMFD Generic Document Schemas

graph-db/scripts/deploy-bamboo.sh
This forces the serverless deployment to take place when only libraries are updated.
=> CMR-8571: Add force deployment to deployment script.

cmr-exchange/service-bridge/resources/config/slate/layout.erb, cmr-exchange/service-bridge/resources/public/docs/service-bridge/docs/1.0.0/rest-api/index.html, cmr-exchange/service-bridge/resources/public/docs/service-bridge/docs/1.5.0/rest-api/index.html, cmr-exchange/service-bridge/resources/public/docs/service-bridge/docs/current/rest-api/index.html, site-templates/resources/templates/base.html
Removing remaining references to the CMR Client Developer Forum. The CMR Client Developer Forum was retired in 2021. As a result, links to this forum in the API docs should be removed.
=> CMR-8593: Removing references to Client Developer Forum

common-lib/src/cmr/common/config.clj
Removing an unused configuration and setting the default to all the known generic types.
=> cmr-8569 config

common-lib/project.clj, common-lib/src/cmr/common/concepts.clj, common-lib/src/cmr/common/generics.clj, indexer-app/src/cmr/indexer/data/index_set.clj, ingest-app/src/cmr/ingest/api/generic_documents.clj, metadata-db-app/src/cmr/metadata_db/api/routes.clj, metadata-db-app/src/cmr/metadata_db/data/memory_db.clj, system-int-test/test/cmr/system_int_test/ingest/generics_test.clj
both tickets deal with removing fixed lists of generic document types. Primary work was in common-lib/src/cmr/common/generics.clj to create some util functions and then use those functions in the ingest and metadata services to remove fixed lists.
=> CMR-8642 and CMR-8617 -  Removing fixed lists of generic document types

transmit-lib/src/cmr/transmit/http_helper.clj
This was used in the days of the "prototype" but we moved off this function, so it can be removed.
=> CMR-8622 - removing a function that is no longer needed

indexer-app/src/cmr/indexer/data/concepts/generic.clj
Since approval for generic documents is already being handled in the ingest application we should remove it from the indexer.
=> CMR-8616: Removing extra approval check

metadata-db-app/src/cmr/metadata_db/data/oracle/concepts.clj
CMR already supports putting a payload under the 'data' field as defined for tag association so no other code change were needed for this ticket. However this function was needed to prove the contents of the metadata column in the database. There is no easy way to read the metadata column from the SQL Query visualizer so this function gives us the ability to decode the compressed value.
=> CMR-8674 - Utility function for reading Service-Collection tag metadata out of the database

search-app/src/cmr/search/api/concepts_search.clj, search-app/test/cmr/search/test/api/concepts_search.clj
Generics were being hard-coded into the routes, changed so that they are being dynamically retrieved.
=> CMR-8619: Dynamically load generics

system-int-test/resources/CMR-8657/coll_invalid_kms_getdata_subtypes.xml, system-int-test/test/cmr/system_int_test/ingest/collection_ingest_test.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/echo10/related_url.clj
This ticket only address a specific case of nonconforming KMS keywords validations. It is our hope to fully enforce KMS keywords validation, but for certain cases (like this one), we will have to relax the enforcement and this kind of special cases will be dealt with case by case.
=> CMR-8657: Allow ingest of ECHO10 collections with nonconforming KMS subtypes for GET DATA type of RelatedUrls.

ingest-app/src/cmr/ingest/api/generic_documents.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/generic_documents.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/search.clj, metadata-db-app/src/cmr/metadata_db/migrations/086_remove_mimetype_generics_table.clj, schemas/resources/schemas/grid/v0.0.1/schema.json, system-int-test/test/cmr/system_int_test/ingest/generics_test.clj
This is to remove the mimetype from the SQL database with a migration as well as remove instances of the mime_type field being used in generics
=> CMR-8614: Remove the mime-type from the SQL database, have Generic code treat mime-types in a standard way

metadata-db-app/src/cmr/metadata_db/migrations/087_update_generic_document_name_length.clj
This change is needed for Legacy Services data migration as some of the legacy services generic documents (e.g. DataQualitySummary, ServiceEntry, etc) have names that can be 1020 characters long.
=> CMR-8766: Change CMR_GENERIC_DOCUMENTS DOCUMENT_NAME column size from 20 to 1020.

graph-db/README.md
* Removes references to the public graphdb endpoint which has since been removed, from the README
=> CMR-8759: Remove references to the graphDb public endpoint from README

common-lib/src/cmr/common/concepts.clj, common-lib/src/cmr/common/generics.clj, ingest-app/src/cmr/ingest/api/generic_documents.clj, ingest-app/src/cmr/ingest/api/routes.clj, ingest-app/test/cmr/ingest/test/api/generic_documents.clj, system-int-test/src/cmr/system_int_test/utils/url_helper.clj, system-int-test/test/cmr/system_int_test/ingest/generics_test.clj
move "provider=PROV1" back to the URL for CRUD events. 
NOTE: documentation of these URL changes is dependent on CMR-8649 and will be completed in a following ticket.
=> Feature CMR-8774 - move provider parameter back to the URL path for generic ingest CRUD events

ingest-app/docs/api.md, ingest-app/src/cmr/ingest/api/core.clj, ingest-app/test/cmr/ingest/api/core_test.clj
curl was not always being nice when trying to mix Variable metadata with new lines and "payload" data as different named URL parameters "content=<json-of-variable>&data=<payload-json>" so this change instead accepts values as one JSON block: '{"content": <content here>, "data": <data here>"}'
=> CMR-8694 - changing input from URL Form Parameters to JSON

other/cmr-exchange/authz/src/cmr/authz/token.clj
Currently, OUS will take token value from either the Authorization header or the Echo-Token header and pass it to CMR via the Authorization header. Since there is only one known client (EDSC) to OUS, it is not worth the effort to add a toggle configuration to not pass Echo-Token header value to CMR. Once ECHO Token generation is disabled in CMR, no one can get an Echo Token anyways. So the proposed solution is to simply log a message in OUS if the client is still using ECHO-Token header to pass in the token value and we can reach out to clients if any to tell them to use Authorization header instead. We can remove ECHO-Token header support from OUS all together once CMR completely retires ECHO token.
=> CMR-8764: Added logging when client still uses Echo-Token header.

search-app/docs/api.md
In [CMR-8650](https://bugs.earthdata.nasa.gov/browse/CMR-8650) we updated the search-after section to indicate that search results may be inconsistent between pages when ingest/delete occurs during the execution of the request. We should add the same clarification to the Paging section of the CMR API doc.
=> CMR-8768: Update CMR API doc to make it clear that paging requests do not maintain PIT order

metadata-db-app/src/cmr/metadata_db/services/concept_service.clj
researched this ticket, found tests to support the current behavior, decided to add a comment here to clearly define the behavior so that future tickets are not created and more time is spent on this because it took a lot of asking around to decide if this was expected behavior.
=> CMR-8564 - keeping tag associations is a feature not a bug

metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, system-int-test/test/cmr/system_int_test/search/generic_association_test.clj
Association delete events need to be published when collection is deleted.  Association delete events also need to be published when generic document is deleted.
=> CMR-8712: cascading index issue

indexer-app/src/cmr/indexer/data/concepts/generic.clj, search-app/docs/api.md, system-int-test/test/cmr/system_int_test/search/generics_test.clj
This is only a quick fix of the searching issue to unblock the Legacy migration work. It does not address the missing tests of searching generic concepts by other search parameters or attempt to refactor the existing tests which will be covered in CMR-8828.
=> CMR-8826: Fixed searching for generic concepts by native-id.

legacy-migration/README.md, legacy-migration/migrate.py
Updated migration script to ingest both OrderOptionDefinition and ServiceOptionDefinition as order-option concept in CMR.
Changed default to skip migration of existing order options.
Added -f option to force migration of existing order options.
=> CMR-8733: Update OrderOptionDefinition and ServiceOptionDefinition migration based on new requirement into order-options.

system-int-test/test/cmr/system_int_test/ingest/collection_keyword_validation_test.clj, umm-spec-lib/src/cmr/umm_spec/util.clj, umm-spec-lib/src/cmr/umm_spec/validation/related_url.clj, umm-spec-lib/test/cmr/umm_spec/test/validation/related_url.clj
removing the warning notice for related URL type/subtype checks based on a static allowing the existing kms based code to be the only source of messages.
=> CMR-7812 - Remove RelatedURL warning on validation

bootstrap-app/README.md, system-int-test/src/cmr/system_int_test/utils/association_util.clj, system-int-test/src/cmr/system_int_test/utils/bootstrap_util.clj, system-int-test/src/cmr/system_int_test/utils/index_util.clj, system-int-test/src/cmr/system_int_test/utils/url_helper.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/generics_test.clj, system-int-test/test/cmr/system_int_test/search/generic_association_test.clj
* Adds some test coverage for associations and bulk indexing of generics
* Ticket CMR-8831 written to address some issues with re-indexing associations of non-generics
* Fixes some other minor things seen in related files most was on `system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/generics_test.clj`
=> CMR-8800: Investigate re-indexing of old generic concept data to new indices

graph-db/README.md, graph-db/package-lock.json, graph-db/package.json, graph-db/serverless.yml, graph-db/serverless/src/bootstrapGremlinServer/handler.js, graph-db/serverless/src/indexCmrCollection/__test__/handler.test.js, graph-db/serverless/src/indexCmrCollection/handler.js, graph-db/serverless/src/testUtil/indexCollection.js, graph-db/serverless/src/utils/cmr/__test__/fetchCmrCollection.test.js, graph-db/serverless/src/utils/cmr/__test__/fetchCollectionPermittedGroups.test.js, graph-db/serverless/src/utils/cmr/__test__/fetchPageFromCmr.test.js, graph-db/serverless/src/utils/cmr/__test__/indexCollection.test.js, graph-db/serverless/src/utils/cmr/__test__/indexRelatedUrl.test.js, graph-db/serverless/src/utils/cmr/fetchCmrCollection.js, graph-db/serverless/src/utils/cmr/fetchCollectionPermittedGroups.js, graph-db/serverless/src/utils/cmr/fetchPageFromCMR.js, graph-db/serverless/src/utils/cmr/getEchoToken.js, graph-db/serverless/src/utils/cmr/indexCmrCollection.js, graph-db/serverless/src/utils/cmr/indexPlatform.js, graph-db/serverless/src/utils/cmr/indexProject.js, graph-db/serverless/src/utils/cmr/indexRelatedUrl.js, system-int-test/test/cmr/system_int_test/search/high_concept_number_test.clj
* Adds a retry policy for indexCmrCollections that reduces instances of concurrent modification errors
* Adds a retry policy using axios-retry for requests to the access-control app
* This does not seem to completely fix the concurrency issues however, there are now scripts to index missing collections into graphDb to compensate
* Update to package.json
* Minor updates to unrelated tests and SC
* Improves logs so that cloudwatch interpretation is easier
=> CMR-8727: Reducing access control Errors when indexing collections into graphDb

metadata-db-app/src/cmr/metadata_db/data/oracle/concepts.clj, system-int-test/test/cmr/system_int_test/ingest/generics_test.clj
Note: The fix covered both CMR-8834 and CMR-8832.
=> CMR-8834: Fixed the code and added tests to make sure native-id is only unique within the same provider and concept type.

search-app/src/cmr/search/validators/all_granule_validation.clj
Allows granules to be queried by entry_id without additional narrowing parameters.
=> CMR-8995 allows entry_id for granule searches

ingest-app/src/cmr/ingest/api/provider.clj, metadata-db-app/src/cmr/metadata_db/api/provider.clj, system-int-test/src/cmr/system_int_test/utils/ingest_util.clj, system-int-test/test/cmr/system_int_test/ingest/provider_ingest_test.clj
Restoring the legacy-services format for providers which does not have any metadata.
=> CMR-9049 - Making change to restore legacy-services format

search-app/src/cmr/search/services/json_parameters/conversion.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj
Requests to CMR Search App with an empty JSON should return a 422 `invalid-data` response rather than crashing with a 500 error.
=> CMR-8038: Fix CMR search app 500 error when searching with empty JSON

mock-echo-app/src/cmr/mock_echo/api/urs.clj, transmit-lib/src/cmr/transmit/urs.clj
This fixes the breaking change introduced by URSFOUR-1973
=> CMR-9043: fix URS launchpad validation url to send token in body instead of URL

transmit-lib/src/cmr/transmit/http_helper.clj
This quick fix will hopefully stop the recent spikes of 500 errors in search app.
=> CMR-9130: add handling 401 from invalid LP token to transmit lib

access-control-app/src/cmr/access_control/system.clj, common-lib/src/cmr/common/util.clj, ingest-app/src/cmr/ingest/system.clj, mock-echo-app/src/cmr/mock_echo/api/urs.clj, search-app/src/cmr/search/system.clj, system-int-test/src/cmr/system_int_test/utils/cache_util.clj, system-int-test/test/cmr/system_int_test/admin/cache_api_test.clj, system-int-test/test/cmr/system_int_test/ingest/collection_ingest_test.clj, system-int-test/test/cmr/system_int_test/misc/launchpad_user_cache.clj, system-int-test/test/cmr/system_int_test/search/scrolling_search_test.clj, transmit-lib/src/cmr/transmit/echo/tokens.clj, transmit-lib/src/cmr/transmit/launchpad_user_cache.clj, transmit-lib/src/cmr/transmit/urs.clj
This pull request implements a caching solution to prevent calls out to EDL to verify launchpad tokens every time CMR receives one.
=> CMR-9108 adds launchpad user caching

system-validation-test/features/healthchecks.feature, system-validation-test/features/ingest_basic.feature, system-validation-test/features/legacy_services.feature, system-validation-test/features/search_with_authorizations.feature
Legacy services is being retired, and echo-tokens are no more. Remove those tests from the suite and update with any relevant token tests.
=> CMR-9134: As a CMR developer I want the system-validation-tests to have up-to-date tests

mock-echo-app/src/cmr/mock_echo/api/urs.clj, system-int-test/test/cmr/system_int_test/misc/launchpad_user_cache.clj, transmit-lib/src/cmr/transmit/launchpad_user_cache.clj, transmit-lib/src/cmr/transmit/urs.clj
Fixes issue where we were using kebab instead of snake to retrieve expiration time of the token.
=> CMR-9108 encodes token as hash value, fixes default ttl

indexer-app/src/cmr/indexer/services/index_service.clj, metadata-db-app/src/cmr/metadata_db/data/memory_db.clj
The related tests already exist. It's just that they are run with real db, instead of in-memory db in bamboo and have always run successfully.  With this fix,  I could run the tests successfully locally using in-memory db.
=> CMR-8872: Fixed a in memory db issue for variable collection association

access-control-app/README.md, access-control-app/src/cmr/access_control/api/routes.clj, access-control-app/src/cmr/access_control/config.clj, system-int-test/test/cmr/system_int_test/access_control/edl_group_test.clj, transmit-lib/src/cmr/transmit/access_control.clj
Remove the token from the URL because it is showing up in /access-control/current-sids, by moving the API call from GET to POST and sending the token as data. Also added a configuration to disable the GET interface.
=> CMR-9154 - remove tokens from /access-control/current-sids logs

access-control-app/src/cmr/access_control/api/routes.clj
Some developer left in debug statements which negated the workings of the ticket.
=> CMR-9154 - left in debug statments which caused manual tests to fail

access-control-app/src/cmr/access_control/services/acl_service.clj, elastic-utils-lib/src/cmr/elastic_utils/embedded_elastic_server.clj, redis-utils-lib/src/cmr/redis_utils/embedded_redis_server.clj, umm-spec-lib/src/cmr/umm_spec/acl_matchers.clj
Small improvements to get-permissions code.
=> CMR-9266 refactors permission acl filtering

.gitignore, dev-system/resources/ordering_examples/api, dev-system/src/cmr/dev_system/control.clj, ingest-app/src/cmr/ingest/services/provider_service.clj, ingest-app/src/cmr/ingest/system.clj, message-queue-lib/src/cmr/message_queue/queue/memory_queue.clj, schemas/project.clj, site-templates/project.clj, transmit-lib/src/cmr/transmit/access_control.clj, transmit-lib/src/cmr/transmit/config.clj, transmit-lib/src/cmr/transmit/ordering.clj, transmit-lib/test/cmr/transmit/test/ordering.clj
Calling CRM Ordering when a provider is created or updated so that it can resync the copy of providers that it has
=> CMR-9187 - Sending provider events to ordering

access-control-app/src/cmr/access_control/services/group_service.clj, indexer-app/src/cmr/indexer/services/index_service.clj, ingest-app/src/cmr/ingest/services/ingest_service/util.clj, search-app/src/cmr/search/services/health_service.clj, system-int-test/test/cmr/system_int_test/misc/health_test.clj, transmit-lib/src/cmr/transmit/echo/rest.clj
removed the echo health check from 4 applications: access control, indexer, ingest, and search
=> CMR-9342 - removing calls to the echo health check

graph-db/package-lock.json
=> CMR-9324: GraphDB Builds Failing Snyk Scan

common-lib/src/cmr/common/util.clj, transmit-lib/src/cmr/transmit/tokens.clj
After legacy services shutdown, invalid tokens can get routed to a 301 returning endpoint for verification.  If we receive a 301 we will now assume the token does not exist as it has failed jwt and launchpad verification.  This is done to preserve the mock-echo testing functionality for now.  I ticket will be written to decouple CMR tests from mock echo.
=> CMR-9372 CMR Internal server error when disassociating tags

browse-scaler/README.md, browse-scaler/test-cicd.sh, browse-scaler/zip-browse-scaler.sh
When the RHEL8 update occured on bamboo we could no longer use `docker-compose` this command was changed to `docker compose`. Please see `https://docs.docker.com/engine/reference/commandline/compose/`
Build result branch: https://ci.earthdata.nasa.gov/browse/CN2-BN2584-3
=> CMR-9419: Browse Scaler Builds are Failing

metadata-db-app/src/cmr/metadata_db/data/oracle/collection_table.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/providers.clj, metadata-db-app/src/cmr/metadata_db/data/util.clj, metadata-db-app/test/cmr/metadata_db/test/data/oracle/collection_table.clj, metadata-db-app/test/cmr/metadata_db/test/data/oracle/util.clj, metadata-db-app/test/cmr/metadata_db/test/test_utils.clj
Fixed SQL injections in the provider and collection table files. There is a separate ticket (9431) that will fix the granule-table and concept files.
=> CMR 9430: Fix SQL Injection Vulnerabilities in CMR Metadata App in provider and collection files

access-control-app/project.clj, bootstrap-app/project.clj, common-app-lib/project.clj, common-lib/project.clj, indexer-app/project.clj, ingest-app/project.clj, metadata-db-app/project.clj, mock-echo-app/project.clj, search-app/project.clj, system-int-test/project.clj, system-int-test/test/cmr/system_int_test/search/granule_shapefile_search_test.clj, virtual-product-app/project.clj
Update Jetty to 9.4.53.v20231009 (as indicated by the CVE resolution path)
Update Ring to 1.10.0, as a result of the Jetty update.
=> CMR-9526 CVE-2023-36478

common-lib/src/cmr/common/cache.clj, common-lib/src/cmr/common/cache/in_memory_cache.clj, common-lib/src/cmr/common/util.clj, common-lib/test/cmr/common/test/generics.clj, common-lib/test/cmr/common/test/util.clj, redis-utils-lib/src/cmr/redis_utils/redis_cache.clj, search-app/src/cmr/search/services/acls/acl_results_handler_helper.clj, search-app/src/cmr/search/services/acls/collections_cache.clj, search-app/test/cmr/search/test/unit/services/acls/collections_cache.clj, search-app/test/cmr/search/test/unit/services/acls/granule_acls.clj, system-int-test/src/cmr/system_int_test/utils/dev_system_util.clj, system-int-test/test/cmr/system_int_test/admin/cache_api_test.clj, system-int-test/test/cmr/system_int_test/search/acls/temporal_collection_granule_test.clj, umm-spec-lib/src/cmr/umm_spec/acl_matchers.clj
This change moves the Granule ACL Collection cache from a local in-memory cache to a shared Redis service.
=> CMR-9504 Moving Granule ACL Collection Cache to Redis

search-app/src/cmr/search/api/keyword.clj
MMT is experiencing CORS errors when retrieving GET keyword/relative-urls from cmr-search-app.  This adds the relevant CORS header to the server response.
=> CMR-9559 adds cors header to keywords response

system-int-test/tests.edn
Adding to test configuration so a codecov file is generated by the integration tests
=> CMR-9555: Incorporate integration test coverage results into code coverage step

search-app/src/cmr/search/services/acls/collections_cache.clj, search-app/src/cmr/search/services/messages/collections_cache_messages.clj, search-app/test/cmr/search/test/unit/services/acls/granule_acls.clj, system-int-test/test/cmr/system_int_test/search/acls/temporal_collection_granule_test.clj
Moving the code over to the new hash map redis cache and breaking up the data into two different hashes within that cache to limit the request data being transmitted over the "wire".
=> Feature CMR-9539 - Update the coll-cache from standard redis to new Hash Map Redis 

common-lib/src/cmr/common/util.clj, search-app/src/cmr/search/results_handlers/granules_umm_json_results_handler.clj, system-int-test/src/cmr/system_int_test/data2/umm_json.clj, system-int-test/test/cmr/system_int_test/search/granule_search_test.clj, system-int-test/test/cmr/system_int_test/search/granule_umm_json_search_test.clj, umm-spec-lib/resources/json-schemas/granule/umm/v1.4/umm-g-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/granule/umm/v1.5/umm-g-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/granule/umm/v1.6.1/umm-g-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/granule/umm/v1.6.2/umm-g-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/granule/umm/v1.6.3/umm-g-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/granule/umm/v1.6.4/umm-g-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/granule/umm/v1.6.5/umm-g-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/granule/umm/v1.6/umm-g-search-results-json-schema.json, umm-spec-lib/src/cmr/umm_spec/json_schema.clj
Feature request:
This ticket is to include the collection_concept_id in the UMM_JSON:meta body for granule response data.
We include this in the .atom/.json response type, but not in the umm_json. The value is one of client convenience and response consistency. Currently, the clients need to reference the CollectionReference value to identify the parent collection.
=> CMR-9545: As a CMR Search User, I Want the Collection_Concept_Id to be Returned in the Granule UMM_JSON Response Format

.gitignore, access-control-app/src/cmr/access_control/system.clj, bootstrap-app/src/cmr/bootstrap/system.clj, common-app-lib/src/cmr/common_app/app_events.clj, common-app-lib/src/cmr/common_app/config.clj, common-app-lib/src/cmr/common_app/services/kms_fetcher.clj, common-lib/src/cmr/common/log.clj, common-lib/src/cmr/common/system.clj, dev-system/dev/refresh_persistent_settings.clj, dev-system/src/cmr/dev_system/system.clj, indexer-app/src/cmr/indexer/system.clj, ingest-app/src/cmr/ingest/runner.clj, ingest-app/src/cmr/ingest/system.clj, metadata-db-app/src/cmr/metadata_db/system.clj, mock-echo-app/src/cmr/mock_echo/system.clj, search-app/src/cmr/search/runner.clj, search-app/src/cmr/search/system.clj, system-int-test/src/cmr/system_int_test/system.clj, virtual-product-app/src/cmr/virtual_product/system.clj
1. Write a memory dump to the file system if sent a `kill -15 <pid>`. This memory dump can then be loaded into visual vm for analyses.
2. RefreshKmsCacheJob now uses a try/catch and writes a short error message if an exception is thrown to shorten the logs. This normally happens locally when starting CMR
3. Adding a new way to make local configurations through refresh_persistent_settings.clj which will not trigger a file change in git status
=> CMR-9591: Write a memory dump on exist if requested 

bootstrap-app/project.clj, bootstrap-app/src/cmr/bootstrap/data/metadata_retrieval/collection_metadata_cache.clj, bootstrap-app/src/cmr/bootstrap/system.clj, common-app-lib/src/cmr/common_app/data/metadata_retrieval/collection_metadata_cache.clj, dev-system/src/cmr/dev_system/system.clj, search-app/src/cmr/search/api/humanizer.clj, search-app/src/cmr/search/services/humanizers/humanizer_report_service.clj, search-app/src/cmr/search/services/humanizers/humanizer_service.clj, search-app/src/cmr/search/system.clj, system-int-test/src/cmr/system_int_test/utils/search_util.clj, system-int-test/src/cmr/system_int_test/utils/url_helper.clj, system-int-test/test/cmr/system_int_test/search/collection_humanized_search_test.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj, system-int-test/test/cmr/system_int_test/search/humanizer/humanizer_test.clj, system-int-test/test/cmr/system_int_test/search/sitemaps_test.clj
- Moved humanizer report refresh job to be called by bootstrap only
=> CMR-9684: Humanizer report cache to bootstrap

message-queue-lib/project.clj
`software.amazon.ion:ion-java@1.0.2` needed to be patched to a newer version
Updating `aws-java-sdk` to a newer version, as that controls the underlying `software.amazon.ion:ion-java` version.
- Access Control App
=> CMR-9736: Updating aws-java-sdk in message-queue-lib

common-lib/src/cmr/common/config.clj, message-queue-lib/project.clj, message-queue-lib/src/cmr/message_queue/config.clj, message-queue-lib/src/cmr/message_queue/queue/memory_queue.clj, message-queue-lib/src/cmr/message_queue/queue/queue_protocol.clj, message-queue-lib/src/cmr/message_queue/queue/sqs.clj, message-queue-lib/src/cmr/message_queue/services/queue.clj, message-queue-lib/src/cmr/message_queue/test/queue_broker_side_api.clj, message-queue-lib/src/cmr/message_queue/test/queue_broker_wrapper.clj
updated the lint tools and made changes to work with these tools and also the clj-kondo tool
Use this ticket to investigate the level of effort needed to bring a project up to code against clj-kondo.
Mostly changes made to remove code or define code in such a way as to be clearly declared by the run time in advance. (declare) statements all over the place now.
adding declare statements, removing unused variables. I did tell eastwood to ignore reflection warnings as I don't understand those yet
This is almost exclusively in message-queue-lib, one file in common.
- [n/a] I have updated/added unit and integration tests that prove my fix is effective or that my feature works
- [] I have made corresponding changes to the documentation
=> CMR-9783: Lint message-queue-lib

elastic-utils-lib/project.clj, elastic-utils-lib/src/cmr/elastic_utils/embedded_elastic_server.clj, redis-utils-lib/project.clj
Resolving an issue that is causing intermittent build failures
Saw references to higher startup timeouts than we had set, so I just increased the start timeout and bumped our version of testcontainers
Just the embedded elastic search. Embedded Redis somewhat as well, but only by virtue of updating testcontainer version
=> CMR-9810: Embedded elastic search failing to start on some builds

acl-lib/dev/user.clj, acl-lib/src/cmr/acl/acl_fetcher.clj, acl-lib/src/cmr/acl/core.clj
Changing the acl software to mitigate linter findings.
Removing not needed required statements and putting meaningless declarations in front of every macro so the linter doesn't complain about them. .
Acl library and all other dependencies.
- [x ] I have updated/added unit and integration tests that prove my fix is effective or that my feature works
- [x ] New and existing unit and int tests pass locally and remotely with my changes
- [x ] I have removed unnecessary/dead code and imports in files I have changed
- [x ] I have performed a self-review of my own code
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
=> CMR-9774: Updating code with linter recommendations

search-app/docs/api.md
Fix curl example in the `Specifying facet fields` section.
remove duplicate "/search" from url string.
The public docs.
=> Fix curl example in the `Specifying facet fields` section

umm-spec-lib/resources/example-data/iso19115/ISOExample-project.xml, umm-spec-lib/resources/example-data/iso19115/artificial_test_data.xml, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso19115_2.clj, umm-spec-lib/test/cmr/umm_spec/test/xml_to_umm_mappings/iso19115_2/temporal.clj
Fixing ISO temporal to only read the date value
Fixing ISO temporal to only read the date value
umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso19115_2.clj find-single-date-time
- [ x] I have updated/added unit and integration tests that prove my fix is effective or that my feature works
- [ x] New and existing unit and int tests pass locally and remotely with my changes
- [ x] I have removed unnecessary/dead code and imports in files I have changed
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
=> CMR-9867: Fixing ISO temporal to only read the date value

search-app/src/cmr/search/data/metadata_retrieval/metadata_transformer.clj
https://github.com/nasa/Common-Metadata-Repository/pull/1978 added several new logs to track transform strategy. This has added too much overhead to our event log creation and egress to the Splunk engine. 
Downgrade 3 of the new logs from INFO to DEBUG to reduce log traffic 
Summarize what you changed.
=> CMR-9877 Downgrade log-level from INFO to DEBUG for 3 transform strategy log events

system-int-test/test/cmr/system_int_test/ingest/granule_translation_test.clj, umm-spec-lib/src/cmr/umm_spec/test/umm_g/expected_util.clj, umm-spec-lib/src/cmr/umm_spec/umm_g/data_granule.clj
CMR granule json search. Customer wants granule_size returned to be calculated differently.
Add all the SizeInBytes (or Size if SizeInBytes is absent) in all the files when ingesting UMM-G granule and use it for granule_size.
CMR granule search
- [ x] I have updated/added unit and integration tests that prove my fix is effective or that my feature works
- [x ] New and existing unit and int tests pass locally and remotely with my changes
- [ x] I have removed unnecessary/dead code and imports in files I have changed
- [x ] I have performed a self-review of my own code
- [ x] My changes generate no new warnings
=> CMR-9839: Granule metadata with granuleSize info yields unexpected results at ingest

access-control-app/src/cmr/access_control/routes.clj, common-app-lib/src/cmr/common_app/api/request_logger.clj, common-app-lib/src/cmr/common_app/config.clj, indexer-app/src/cmr/indexer/api/routes.clj, metadata-db-app/src/cmr/metadata_db/api/routes.clj
Add remaining HTTP response event logs to access control app, indexer ap, and metadata db app. They were already existing in search and ingest and we originally had stated that after a couple months if we liked the logs they would be added to all.
Added necessary handlers
Logging
- [x ] I have updated/added unit and integration tests that prove my fix is effective or that my feature works
- [x ] New and existing unit and int tests pass locally and remotely with my changes
- [x ] I have removed unnecessary/dead code and imports in files I have changed
- [x ] I have performed a self-review of my own code
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
=> CMR-9665: Add HTTP response event to access control app, indexer app, metadata-db app

elastic-utils-lib/src/cmr/elastic_utils/search/es_index.clj
Log Volume for Elasticsearch Index Search is Too High
Switch log from info to debug
Elastic_utils
=> CMR-9268: Log Volume for Elasticsearch Index Search is Too High

.github/workflows/cmr-checks.yml, dev-system/support/run-kondo.sh
Require that code passed clj-kondo before allowing a merge into master
This change will add clj-kondo as a step to a GitHub action which will be successful if there are no errors from clj-kondo. Warnings will be allowed to pass.
The solution is to call clj-kondo in a docker container against the 7 sub-projects that have been cleaned up. The list of sub projects is expected to increase to all. To do this, a new script has been added to dev-system/support/run-kondo.sh to be run by the clj-kondo docker container. 
This should impact changes made to access-control-app/src, acl-lib/src, common-app-lib/src, common-lib/src, elastic-utils-lib/src, es-spatial-plugin/src, message-queue-lib/src
- [-] I have updated/added unit and integration tests that prove my fix is effective or that my feature …
=> CMR-9185: Require clj-kondo in GitHub

ingest-app/docs/api.md, ingest-app/src/cmr/ingest/services/messages.clj, ingest-app/src/cmr/ingest/validation/validation.clj, system-int-test/test/cmr/system_int_test/ingest/collection/collection_keyword_validation_test.clj
Validate Collection ProcessingLevel Id. when "Cmr-Validate-Keywords: true" header is set
Add the validation
CMR Ingest
- [ x] I have updated/added unit and integration tests that prove my fix is effective or that my feature works
- [ x] New and existing unit and int tests pass locally and remotely with my changes
- [ x] I have removed unnecessary/dead code and imports in files I have changed
- [ x] I have performed a self-review of my own code
- [x ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [x ] I have cleaned up integration tests by doing one or more of the following:
- transformed applicable int tests into …
=> CMR-9429: Validate collection processing level Id

search-app/docs/api.md
Found a mistake when testing. Link needs an s in it
adding an 's'
The parameter section discussing token has a link to the headers section
- [- ] I have updated/added unit and integration tests that prove my fix is effective or that my feature works
- [-] New and existing unit and int tests pass locally and remotely with my changes
- [-] I have removed unnecessary/dead code and imports in files I have changed
- [-] I have performed a self-review of my own code
- [-] I have commented my code, particularly in hard-to-understand areas
- [-] My changes generate no new warnings
- transformed applicable int …
=> CMR-9706: fixing link to headers

transmit-lib/src/cmr/transmit/http_helper.clj
Add 401 error handling to gracefully respond to POST/PUT requests with invalid Launchpad tokens
Added a 401 error handler
Search, Access Control, Ingest
=> CMR-8976: Add 401 handling to transmit response handler for POST, PUT requests

job-utilities/job-details.json, job-utilities/job_router/lambda_function.py, job-utilities/local_development/local_scheduler.py
If some infrastructure change causes the LB to be remade with the same name, it might not have the same DNS name, which requires job-router to need it's variables updated
Changed job-router to use the name of the LB to query AWS for the DNS name, so it isn't reliant on a more-likely-to-change value
job-router
- [x ] I have updated/added unit and integration tests that prove my fix is effective or that my feature works
- [x ] I have removed unnecessary/dead code and imports in files I have changed
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have cleaned up integration tests by doing one or more of the following:
- de-duped, consolidated, removed …
=> CMR-10009: Fix job-router load balancer referencing issues

metadata-db-app/src/cmr/metadata_db/data/oracle/granule_table.clj, metadata-db-app/src/cmr/metadata_db/migrations/090_add_granule_delete_revision_index.clj, metadata-db-app/src/cmr/metadata_db/services/jobs.clj
Adding indexes to granule tables to speed up DB queries for cleaning up old concepts.
Adding indexes to granule tables to speed up DB queries for cleaning up old concepts.
Granule Tables
=> CMR-10020 - Adding indexes to granule tables to speed up DB queries for cleaning up old concepts.

common-app-lib/src/cmr/common_app/api/request_logger.clj, common-app-lib/test/cmr/common_app/test/services/kms_fetcher_errors_test.clj, common-lib/src/cmr/common/log.clj, transmit-lib/src/cmr/transmit/kms.clj
The inclusion of SHA1 and MD5 output in the request logs really have no practical use for every day logs and are of minor interest outside of debugging.
This change will push these values to debug only status, meaning they will only display when logs are set to debug or more verbose.
This impacts the custom access log
- [-] I have updated/added unit and integration tests that prove my fix is effective or that my feature works
- [x ] I have removed unnecessary/dead code and imports in files I have changed
- refactored to reduce number of system state …
=> Feature: CMR-10013 - Removal of sha/md5 by default

indexer-app/project.clj, indexer-app/src/cmr/indexer/api/routes.clj, indexer-app/src/cmr/indexer/config.clj, indexer-app/src/cmr/indexer/data/collection_granule_aggregation_cache.clj, indexer-app/src/cmr/indexer/data/concept_parser.clj, indexer-app/src/cmr/indexer/data/concepts/attribute.clj, indexer-app/src/cmr/indexer/data/concepts/collection.clj, indexer-app/src/cmr/indexer/data/concepts/collection/platform.clj, indexer-app/src/cmr/indexer/data/concepts/generic_util.clj, indexer-app/src/cmr/indexer/data/concepts/granule.clj, indexer-app/src/cmr/indexer/data/concepts/orbit_calculated_spatial_domain.clj, indexer-app/src/cmr/indexer/data/concepts/subscription.clj, indexer-app/src/cmr/indexer/data/concepts/tag.clj, indexer-app/src/cmr/indexer/data/concepts/tool.clj, indexer-app/src/cmr/indexer/data/concepts/variable.clj, indexer-app/src/cmr/indexer/data/elasticsearch.clj, indexer-app/src/cmr/indexer/data/index_set.clj, indexer-app/src/cmr/indexer/data/index_set_elasticsearch.clj, indexer-app/src/cmr/indexer/data/metrics_fetcher.clj, indexer-app/src/cmr/indexer/runner.clj, indexer-app/src/cmr/indexer/services/autocomplete.clj, indexer-app/src/cmr/indexer/services/event_handler.clj, indexer-app/src/cmr/indexer/services/index_service.clj, indexer-app/src/cmr/indexer/services/index_set_service.clj, indexer-app/test/cmr/indexer/test/services/index_service.clj
There are three logs which generate logs in the millions per day. These three logs are for the same indexing event and represent: Start, finish, time to visibility.
The change here is to introduce a new configuration allowing Indexer to issue a single log entry when reporting time to visibility with additional information found in the start/stop log entries. This new log is also in json and is as short as possible.
There are also Kondo updates in this change.
- refactored to reduce number of system state resets by …
=> Feature: CMR-10025 - Condensed Index Event logs

.github/pull_request_template.md, dev-system/support/run-kondo.sh
updating the GitHub action to include indexer and ingest as both have been cleaned up
Updating the kondo script to include these services
- [-] I have updated/added unit and integration tests that prove my fix is effective or that my feature works
- [-] New and existing unit and int tests pass locally and remotely with my changes
- [-] I have removed unnecessary/dead code and imports in files I have changed
=> CMR-10063: adding ingest and indexer to kondo check

metadata-db-app/src/cmr/metadata_db/data/oracle/search.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, metadata-db-app/src/cmr/metadata_db/services/provider_service.clj
Reduce metadata-db logs
Change unnecessary logs from info to debug level
metadata-db
=> CMR-10026: Reduce metadata-db logs

indexer-app/src/cmr/indexer/services/index_service.clj, indexer-app/test/cmr/indexer/test/services/index_service.clj
Removing fv field and adding a concept type to ease parsing. Test also added.
1. This change will correct the JSON output in the time to visibility log so that it is parsable by Splunk.
2. Added Concept Type so that splunk queries do not have to do a regex to discover it
3. Removed spaces for even more space savings
This should impact anything that relies on the new time to visibility log.
- refactored to reduce number of system state resets by updating fixtures (use-fixtures :each …
=> CMR-10071: Fixing the Time To Visibility Log

common-app-lib/src/cmr/common_app/data/humanizer_alias_cache.clj, common-app-lib/src/cmr/common_app/services/cache_info.clj, common-lib/src/cmr/common/cache/in_memory_cache.clj
Lowering the log levels of several logs related to caching as these are not deemed to be needed in production at this time.
Caching info
=> CMR-10062: Lowering cache logs a log level to reduce size in splunk

access-control-app/src/cmr/access_control/routes.clj, access-control-app/src/cmr/access_control/system.clj, bootstrap-app/src/cmr/bootstrap/api/routes.clj, common-app-lib/src/cmr/common_app/api/request_logger.clj, indexer-app/src/cmr/indexer/api/routes.clj, ingest-app/src/cmr/ingest/routes.clj, metadata-db-app/src/cmr/metadata_db/api/routes.clj, search-app/src/cmr/search/routes.clj, system-int-test/src/cmr/system_int_test/data2/atom_json.clj, virtual-product-app/src/cmr/virtual_product/api/routes.clj
The JSON Access log does not calculate duration correctly.
The solution was to create a new Ring handler to capture the start time of a request. This handler is called as soon as possible in the Ring chain. Then the Log handler is to be called at the end of the chain and it uses the value to calculate duration.
While in the code, cleaned up the values populated:
* Removed values which are already in the headers
* Added all headers in bulk
* Added now-ms (current time as milliseconds)
* renamed uri to url
* added actual uri from system
* changed remote address so that IP6 and IP4 localhost addresses report as "localhost"
Common
metadata-db, ingest, search, indexer, bootstrap, virtual-product, access-control
Not changed: mock-echo (port 2999)
A test was changed so as to not issue warnings …
=> Bugfix CMR-10079: json access log

job-utilities/job_router/Dockerfile, job-utilities/job_router/README.md, job-utilities/job_router/lambda_function.py, job-utilities/job_router/run-docker.sh, job-utilities/job_router/service-ports.json
Update documentation and process for local job-router
Documentation for local usage of job-router was poor, and the code was in fact not set up properly for testing it locally
Documentation has been updated and code added to allow for basic local testing
job-router
- [N/A] I have updated/added unit and int tests that prove my fix is effective or that my feature works
- [N/A] clj-kondo has been run locally and all errors corrected
- [N/A] I have removed unnecessary/dead code and imports in files I have changed
- [N/A] I have cleaned up integration tests by doing one or more of the following:
- refactored to reduce number of system …
=> CMR-10070: Update documentation and process for local job-router

Generics.md, common-lib/src/cmr/common/config.clj, ingest-app/src/cmr/ingest/api/generic_documents.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/utils/generic.clj, schemas/resources/schemas/validate.py, schemas/resources/schemas/visualization/CHANGELOG.md, schemas/resources/schemas/visualization/v1.0.0/index.json, schemas/resources/schemas/visualization/v1.0.0/ingest.md, schemas/resources/schemas/visualization/v1.0.0/metadata.json, schemas/resources/schemas/visualization/v1.0.0/schema.json, schemas/resources/schemas/visualization/v1.0.0/search.md, schemas/resources/schemas/visualization/v1.0.0/spatial-temporal-extent.json, schemas/resources/schemas/visualization/v1.0.0/umm-vis-maps-schema.json, schemas/resources/schemas/visualization/v1.0.0/umm-vis-tiles-schema.json, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/test/cmr/search/test/unit/data/elastic_search_index_test.clj, search-app/test/cmr/search/test/unit/services/parameters_conversion.clj, system-int-test/src/cmr/system_int_test/utils/generic_util.clj
Adding in a version of the Visualization schema; ingest, indexing, and searching for visualization records.
Adding in a version of the Visualization schema; ingest, indexing, and searching for visualization records.
Summarize what you changed.
Impacts generic documents as this is where the visualization schema was added.
fixed a generic documents ingest loading schemas from the classpath
Added some visualization search parameters.
- [ X] I have updated/added unit and int tests that prove my fix is effective or that my feature works
- [ X] New and existing unit and int tests pass locally and remotely
- [ X] clj-kondo has been run locally and all errors corrected
- [ X] I have removed unnecessary/dead code and imports in files I have changed
- [ X] I …
=> Cmr-10030: Ingesting and Searching for Visualizations

ingest-app/src/cmr/ingest/services/subscriptions_helper.clj
Changing Sub/Not email to use EMCC AWS SES.
Changing Sub/Not email to use EMCC AWS SES.
Ingest subscription_helper.
=> CMR-9842: Changing Sub/Not email to use EMCC AWS SES.

job-utilities/job_router/requirements.txt
job-utilities/job-router bumping up urllib3 from version 1.26.18 to version 1.26.19
job-utilities/job-router bumping up urllib3 from version 1.26.18 to version 1.26.19
job-utilities/job-router
=> CMR-10058: job-utilities/job-router bumping up urllib3 from version 1.26.18 to version 1.26.19

common-lib/src/cmr/common/hash_cache.clj, ingest-app/src/cmr/ingest/api/routes.clj, ingest-app/src/cmr/ingest/api/subscriptions.clj, ingest-app/src/cmr/ingest/config.clj, ingest-app/src/cmr/ingest/services/ingest_service/subscription.clj, ingest-app/src/cmr/ingest/services/subscriptions_helper.clj, metadata-db-app/src/cmr/metadata_db/config.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, metadata-db-app/src/cmr/metadata_db/services/concept_validations.clj, metadata-db-app/src/cmr/metadata_db/services/sub_notifications.clj, metadata-db-app/src/cmr/metadata_db/services/subscription_cache.clj, metadata-db-app/src/cmr/metadata_db/services/subscriptions.clj, metadata-db-app/src/cmr/metadata_db/system.clj, metadata-db-app/test/cmr/metadata_db/test/services/subscription_cache_test.clj, metadata-db-app/test/cmr/metadata_db/test/services/subscriptions_test.clj, redis-utils-lib/src/cmr/redis_utils/redis_hash_cache.clj, redis-utils-lib/test/cmr/redis_utils/test/test_redis_cache.clj, system-int-test/src/cmr/system_int_test/data2/umm_spec_subscription.clj, system-int-test/test/cmr/system_int_test/admin/cache_api_test.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/subscriptions_test.clj, system-int-test/test/cmr/system_int_test/ingest/provider/provider_ingest_permissions_test.clj, umm-spec-lib/resources/json-schemas/subscription/umm/v1.1.1/umm-sub-json-schema.json, umm-spec-lib/resources/json-schemas/subscription/umm/v1.1.1/umm-sub-search-results-json-schema.json, umm-spec-lib/src/cmr/umm_spec/migration/version/subscription.clj, umm-spec-lib/src/cmr/umm_spec/versioning.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version/subscription.clj
Adding in the new subscription schema and setting the subscription cache when the ingest subscriptions are added or deleted.
Adding in the new subscription schema and setting the subscription cache when the ingest subscriptions are added or deleted.
Ingest, subscriptions, metadata_db
=> CMR-10134 Adding in the new subscription schema and setting the subscription cache when the ingest subscriptions are added or deleted.

indexer-app/src/cmr/indexer/services/index_service.clj, ingest-app/src/cmr/ingest/services/ingest_service/subscription.clj, metadata-db-app/project.clj, metadata-db-app/src/cmr/metadata_db/api/routes.clj, metadata-db-app/src/cmr/metadata_db/api/subscriptions.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/subscription.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, metadata-db-app/src/cmr/metadata_db/services/concept_validations.clj, metadata-db-app/src/cmr/metadata_db/services/subscription_cache.clj, metadata-db-app/src/cmr/metadata_db/services/subscriptions.clj, metadata-db-app/test/cmr/metadata_db/test/services/subscription_cache_test.clj, metadata-db-app/test/cmr/metadata_db/test/services/subscriptions_test.clj, system-int-test/test/cmr/system_int_test/ingest/subscription/subscription_ingest_test.clj, umm-spec-lib/resources/json-schemas/subscription/umm/v1.1.1/umm-sub-json-schema.json, umm-spec-lib/src/cmr/umm_spec/migration/version/subscription.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version/subscription.clj
Updated code to remove subscription information from redis cache upon subscription delete. Updated schema to allow multiple modes. Adding subscription to redis cache already in the code. 
Updated code to remove subscription information from redis cache upon subscription delete. Updated schema to allow multiple modes.
Metadata_db
=> CMR-10139: Updated code to remove subscription information from redis cache upon subscription delete. Updated schema to allow multiple modes.

common-app-lib/src/cmr/common_app/services/cache_info.clj, ingest-app/src/cmr/ingest/services/subscriptions_helper.clj, message-queue-lib/src/cmr/message_queue/pub_sub.clj, message-queue-lib/src/cmr/message_queue/queue/aws_queue.clj, message-queue-lib/src/cmr/message_queue/services/queue.clj, message-queue-lib/src/cmr/message_queue/topic/aws_topic.clj, message-queue-lib/src/cmr/message_queue/topic/local_topic.clj, message-queue-lib/src/cmr/message_queue/topic/topic_protocol.clj, message-queue-lib/test/cmr/message_queue/test/pub_sub_test.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/concept_delete_spec.clj, metadata-db-app/project.clj, metadata-db-app/src/cmr/metadata_db/api/subscriptions.clj, metadata-db-app/src/cmr/metadata_db/data/ingest_events.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/sub_notifications.clj, metadata-db-app/src/cmr/metadata_db/migrations/091_update_cmr_sub_notifications_table.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, metadata-db-app/src/cmr/metadata_db/services/sub_notifications.clj, metadata-db-app/src/cmr/metadata_db/services/subscription_cache.clj, metadata-db-app/src/cmr/metadata_db/services/subscriptions.clj, metadata-db-app/src/cmr/metadata_db/system.clj, metadata-db-app/test/cmr/metadata_db/test/services/subscriptions_test.clj, search-app/project.clj, system-int-test/test/cmr/system_int_test/ingest/subscription/subscription_processing_test.clj, transmit-lib/src/cmr/transmit/search.clj, transmit-lib/test/cmr/transmit/test/search.clj
Adding the capability to subscribe/unsubscribe to topics either AWS or local
Adding the capability to publish notification messages when it meets subscription criteria
Added the capability to subscribe/unsubscribe an AWS queue to either an AWS or local topic.
Added the capability to metadata_db to send notification messages if the concepts meet the subscription criteria.
Ingest Subscriptions and Metadata_DB.
=> CMR-10140-1: Adding subscribing to the local and AWS topics and publishing messages.

umm-spec-lib/resources/xml-schemas/dif10/UmmCommon_1.2.xsd
Adding the missing dif 10 dataset progress that was supposed to go into the first CMR-10173 PR
same as above
All translations
=> CMR-10173: Update dataset progress enum

message-queue-lib/src/cmr/message_queue/topic/aws_topic.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/subscription.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/sub_notifications.clj, metadata-db-app/src/cmr/metadata_db/migrations/092_update_cmr_subscriptions_table.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, metadata-db-app/src/cmr/metadata_db/services/concept_validations.clj, metadata-db-app/src/cmr/metadata_db/services/sub_notifications.clj, metadata-db-app/src/cmr/metadata_db/services/subscriptions.clj, metadata-db-app/test/cmr/metadata_db/test/services/subscriptions_test.clj
Fixing the ability to subscribe SQS queues correctly to the local and AWS topics. Moving subscription ARN to CMR_Subscriptions table.
Fixing the ability to subscribe SQS queues correctly to the local and AWS topics. Moving subscription ARN to CMR_Subscriptions table.
Ingest subscriptions
=> CMR-10141: Fixing the ability to subscribe SQS queues correctly to the local and AWS topics. Moving subscription ARN to CMR_Subscriptions table.

umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/echo10/related_url.clj
RelatedURL SubType field was not translating correctly for 'User's Guide' when ingested as Echo10 and translated into UMM-C
Add the User's Guide with 'USER'S GUIDE' spelling to translation map
=> CMR-10000: RelatedURL subtype not accessible through ECHO10 collection

common-app-lib/src/cmr/common_app/api/request_logger.clj
REPORT Logs Emitting Security Token in Clear Text
If the token exists, will obfuscate with ****. If it does not exist, will do nothing.
Logs across all apps
=> CMR-10215: REPORT Logs Emitting Security Token in Clear Text

metadata-db-app/src/cmr/metadata_db/services/subscriptions.clj
Added a check if the subscription is an ingest subscription, only then add the subscription.
Added a check if the subscription is an ingest subscription, only then add the subscription.
Subscriptions
=> CMR-10285: Adding check before subscribing to AWS that the subscription is an ingest subscription.

ingest-app/docs/api.md, ingest-app/src/cmr/ingest/api/collections.clj, ingest-app/src/cmr/ingest/config.clj
[CMR-10182](https://bugs.earthdata.nasa.gov/browse/CMR-10182) changed api behavior for ingesting collections by making cmr-validate-keywords default to true instead of its previous default behavior of false.
A feature toggle on top of this behavior change so we can control when this feature become public or not in all envs
Ingest
=> CMR-10287: Create feature toggle for cmr-validate-keyword default behavior change

umm-spec-lib/resources/json-schemas/variable/umm/v1.9.0/umm-var-json-schema.json
Update length of Variable - CodeSystemIdentifierMeaning field from 60 to 1024 and minItems to 1.
Update json schema file for Variable.
Ingest of Variable - field CodeSystemIdentifierMeaning.
=> CMR-9878: CodeSystemIdentifierMeaning maxlength to 1024, minItems to 1

message-queue-lib/project.clj
Snyk Vulnerability found and must be fixed for io.netty:netty-handler in cmr-message-queue-lib
Forced the underlying vulnerable library netty-handler to version 4.1.112.Final
Bootstrap, Access Control, Message Queue Lib
=> CMR-10398: Fix Synk vulnerability for netty

subscription/url-endpoint-test-lambda/src/url-endpoint-test-lambda.py
Using environment variable to set http subscription test lambda bucket name.
Using environment variable to set http subscription test lambda bucket name.
Using environment variable to set http subscription test lambda bucket name.
=> CMR-10313: Using environment variable to set http subscription test lambda bucket name.

indexer-app/src/cmr/indexer/services/autocomplete.clj, system-int-test/test/cmr/system_int_test/search/autocomplete/suggestion_permissions_test.clj
Autocomplete suggestions were not honoring collection permissions properly, returning in some cases autocomplete suggestions for collections that are not public to guest user.
The issue had two potential causes:
- The (map merge) call was combining two lists of hash maps (humanized fields and collection permissions) without properly accounting for deleted collections in both lists. When only one list removed deleted collections, the permissions became misaligned with the incorrect fields, causing unpredictable permission results whenever a batch included deleted collections.
- Additionally, the (remove nil?) operation after (map #(parse-collection context %)) could also be contributing to the problem. This is harder to verify since the nils represent collections that failed to parse, …
=> CMR-10430: CMR should honor permissions in the autocomplete responses

ingest-app/docs/api.md
To update doc on limitation of subscription queue create and update.
Currently, the ingest (NRT) subscriptions has a situation where if User1 creates a subscription to Coll1 and then User2 creates a different subscription to the same Coll1 for the same queue, it will overwrite the first subscription in the backend SNS subscription filter for that queue.
Add the limit to the CMR Ingest documentation page so that users understand what to expect
Ingest Doc
=> CMR-10455: Update subscription doc on subscription edge case limit

access-control-app/docs/acl-schema.md, access-control-app/docs/api.md, access-control-app/int-test/cmr/access_control/int_test/permission_check_test.clj, access-control-app/src/cmr/access_control/data/acl_schema.clj, access-control-app/src/cmr/access_control/services/acl_validation.clj
We are adding a new acl target for system acls for utilization in MMT.  This acl is for controlling keyword crud.
Added the target string to the acl schema, then added the crud configuration to the acl validation namespace.
cmr-access-control
=> CMR-10452: adds KEYWORD_MANAGEMENT_SYSTEM acl

common-lib/src/cmr/common/config.clj, schemas/resources/schemas/visualization-draft/v1.1.0/index.json, schemas/resources/schemas/visualization-draft/v1.1.0/ingest.md, schemas/resources/schemas/visualization-draft/v1.1.0/metadata.json, schemas/resources/schemas/visualization-draft/v1.1.0/search.md, search-app/src/cmr/search/api/concepts_lookup.clj, system-int-test/src/cmr/system_int_test/utils/generic_util.clj
Adding visualization drafts 
Adding the capability to CRUD visualization draft records.
new visualization draft records.
=> CMR-10518: adding visualization-drafts

elastic-utils-lib/src/cmr/elastic_utils/es_helper.clj, elastic-utils-lib/src/cmr/elastic_utils/index_util.clj, indexer-app/src/cmr/indexer/data/elasticsearch.clj, indexer-app/src/cmr/indexer/data/index_set.clj, indexer-app/src/cmr/indexer/services/index_service.clj, indexer-app/src/cmr/indexer/services/index_set_service.clj, system-int-test/src/cmr/system_int_test/utils/index_util.clj, system-int-test/test/cmr/system_int_test/bootstrap/rebalance_collections_test.clj, system-int-test/test/cmr/system_int_test/ingest/misc/deleted_collection_index_test.clj
Deleting a collection deletes an associated granule index if it exists
Deleting a collection deletes an associated granule index from elasticsearch and from the index-set (and index-set cache)
indexer
=> CMR-10099: When deleting a collection and its granules are in their own index, delete the index.

elastic-utils-lib/project.clj, elastic-utils-lib/src/cmr/elastic_utils/embedded_elastic_server.clj, es-spatial-plugin/project.clj
Update the def elastic version from "7.17.14" to "7.17.25"
Updated the version number where ever it showed up.
Changed elastic lib and the docker images 
elastic util lib, including the embedded docker images and the spatial plugin.
- [-] I have updated/added unit and int tests that prove my fix is effective or that my feature works
- [-] clj-kondo has been run locally and all errors corrected
- [-] I have removed unnecessary/dead code and imports in files I have changed
- refactored to reduce …
=> CMR-10533: Bumping up elastic to a recomended point release

search-app/src/cmr/search/results_handlers/timeline_results_handler.clj, search-app/src/cmr/search/services/query_execution/facets/temporal_facets.clj
Addressing a breaking change for elasticsearch 8.x
Fixing the usage of interval in date_histogram
Replaced interval with calendar_interval
granule timelines
=> CMR-10371: Evaluate and Address Breaking Changes for Migration to 8.x

system-validation-test/Gemfile, system-validation-test/Gemfile.lock
system-validaiton-test build was failing.
Updated the cucumber version to the one that will work with our current version of ruby, limited ffi to work with the current version of ruby
system-validation-tests
=> CMR-10549: updates system-validation-test cucumber version

common-lib/src/cmr/common/api/web_server.clj, dev-system/src/cmr/dev_system/config.clj, dev-system/src/cmr/dev_system/system.clj
The first attempt at pushing out the Jetty change failed in SIT as that environment ran the code in a different way (using different settings) which exposed an error. This version removes the use of libraries which caused the problem. 
It seams that the web_server.clj file was not always being compiled unless you called `cmr setup dev` between changes. After doing this I was able to get runtime errors.
NOTE: this pull request is into the first branch so that I can show just what was changed here. I will then merge that branch (which was approved already) into master.
1. Removed library calls which no longer exist.
2. Exposed dev-system configurations globally so that all apps can choose to run without compression and logs instead of assuming.
1. All web servers now have two new options …
=> CMR-10213 new jetty - Attempt 2

indexer-app/src/cmr/indexer/data/concepts/collection.clj, system-int-test/test/cmr/system_int_test/search/collection/collection_doi_search_test.clj
DOI search now only returns collections where the DOI of the collection matches, and not the associatedDOI's field
Modified the collection document indexing to not include associated dois in the doi field, so that the search parameter doi will only search on a collection's doi, not also associated dois.
cmr indexer and search app
=> CMR-10525: removes associatedDois from doi search on collections

elastic-utils-lib/src/cmr/elastic_utils/es_index_helper.clj, elastic-utils-lib/src/cmr/elastic_utils/index_util.clj, indexer-app/int-test/cmr/indexer/test/valid_data_crud_tests.clj, indexer-app/src/cmr/indexer/data/index_set_elasticsearch.clj, indexer-app/src/cmr/indexer/services/index_set_service.clj
This PR sets up the infrastructure to switch to search by aliases rather than index names directly by creating aliases for all CMR ES indices in dev-system.
Create aliases for all CMR ES indices in dev-system.
access-control and search applications where ES indices are created.
=> CMR-10766: Create aliases for all CMR indices in Elasticsearch at dev-start.

elastic-utils-lib/src/cmr/elastic_utils/search/es_debug.clj, search-app/src/cmr/search/data/elastic_search_index.clj, search-app/src/cmr/search/services/query_service.clj, search-app/src/cmr/search/system.clj
To update search app to work with split cluster
Added the two clusters as settings
- Search App
- reduced number of system state resets by updating fixtures. Ex) (use-fixtures :each (ingest/reset-fixture {})) to be :once instead of :each
=> CMR-10762: Update Search App to work with split-cluster (locally)

indexer-app/int-test/cmr/indexer/test/utility.clj, indexer-app/int-test/cmr/indexer/test/valid_data_crud_tests.clj
Check all sys tests work and added new test to make sure indexer update changes are tested
added new test to make sure indexer update changes are tested
All
- reduced number of system state resets by updating fixtures. Ex) (use-fixtures :each (ingest/reset-fixture {})) to be :once instead of :each
=> CMR-10764: Update sys-tests to work with split cluster

access-control-app/src/cmr/access_control/services/acl_service.clj, elastic-utils-lib/src/cmr/elastic_utils/search/ac_elasticsearch.clj, elastic-utils-lib/src/cmr/elastic_utils/search/access_control_index.clj, elastic-utils-lib/src/cmr/elastic_utils/search/es_index.clj, indexer-app/src/cmr/indexer/data/collection_granule_aggregation_cache.clj, indexer-app/src/cmr/indexer/data/concepts/deleted_granule.clj, indexer-app/src/cmr/indexer/data/elasticsearch.clj, search-app/src/cmr/search/data/elastic_search_index.clj, search-app/src/cmr/search/services/query_service.clj, search-app/test/cmr/search/test/unit/data/elastic_search_index_test.clj, system-int-test/test/cmr/system_int_test/ingest/misc/deleted_granules_index_test.clj
As a CMR operator, I want to CMR to use aliases when searching against Elasticsearch so that we can switch between underlying ES indices
Switch CMR to use aliases when searching against Elasticsearch so that we can switch between underlying ES indices
access-control, indexer and bootstrap apps.
- reduced number of system state resets by updating fixtures. Ex) (use-fixtures :each (ingest/reset-fixture {})) to be :once instead of :each
=> CMR-10768: As a CMR operator, I want to CMR to use aliases when searching against Elasticsearch so that we can switch between underlying ES indices

indexer-app/src/cmr/indexer/data/concepts/deleted_granule.clj, indexer-app/src/cmr/indexer/data/index_set.clj, system-int-test/test/cmr/system_int_test/ingest/misc/deleted_granules_index_test.clj
I would like to move the deleted-gran def from its current file to index-set file to consolidate where all the index names are AND to prevent consistent merge conflict issues with my feature branch CMR-10600-split-cluster-feature. This will need to move at some point because it creates cyclical dependency issues in the split cluster feature branch.
Move deleted-granule-index-alias def into index-set file
All
No logic should change. This is only a func move change.
- reduced number of system state resets by updating fixtures. Ex) (use-fixtures :each (ingest/reset-fixture {})) to be :once instead of :each
=> CMR-X: Move deleted gran index def
