nasa/Common-Metadata-Repository

CHANGELOG.md, access-control-app/acl_usage.md, ingest-app/api_docs.md, spatial-lib/src/cmr/spatial/tile.clj, umm-spec-lib/README.md
The wiki link that got removed was public, so I never did anything with it 👻. Rather than have a sentence with REMOVED in the middle of it, I opted to just remove it altogether.
=> Replace instances of REMOVED with something better

metadata-db-app/src/cmr/metadata_db/data/oracle/search.clj
Needed to support monitoring of batch indexing from splunk.
=> Changed logging level of batch concept retrieval from debug to info.

common-app-lib/resources/ops-humanizers.json
I need Lauren and Leo to review the humanizers that system engineering put into the ops-humanizers.json file.
=> adding new humanizers to the ops_humanizers.json file

.mailmap
I found a way to fix the contributor history, and this one wouldn't require rewriting history!
=> Add mailmap to fix contributor chart

indexer-app/src/cmr/indexer/data/concepts/granule.clj, indexer-app/src/cmr/indexer/data/index_set.clj, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/cleanup_test.clj, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/granule_save_test.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/granule_table.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, metadata-db-app/src/migrations/051_add_created_at_to_granule_tables.clj
- This is just pulling the relevant files from PR #86 into a more bite-sized pull request
=> CMR-4001 Add migrations and indexing logic

access-control-app/int_test/cmr/access_control/int_test/permission_check_test.clj, umm-spec-lib/src/cmr/umm_spec/acl_matchers.clj
Fixes some issues with the previous merge to CMR-3858
=> CMR-3858 fixes acl matcher and permission check test

metadata-db-app/src/migrations/052_add_coll_ids_catalog_acls.clj, metadata-db-app/src/migrations/054_fix_catalog_acl_concept_ids.clj
This pull request creates a new migration to fix corrupted catalog item ACLs.
=> CMR-3858 Update Catalog Item ACL endpoints to accept concept_id

spatial-lib/src/cmr/spatial/encoding/gmd.clj, spatial-lib/test/cmr/spatial/test/encoding/gmd.clj, umm-lib/src/cmr/umm/iso_mends/spatial.clj, umm-lib/src/cmr/umm/iso_smap/collection/spatial.clj, umm-lib/src/cmr/umm/iso_smap/granule/spatial.clj, umm-lib/src/cmr/umm/iso_smap/spatial.clj, umm-spec-lib/resources/json-schemas/umm/v1.9/umm-cmn-json-schema.json, umm-spec-lib/src/cmr/umm_spec/iso19115_2_util.clj, umm-spec-lib/src/cmr/umm_spec/test/expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/iso19115_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso19115_2.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso19115_2/spatial.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso19115_2/tiling_system.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso_smap.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso19115_2/spatial.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso19115_2/tiling_system.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_shared/distributions_related_url.clj
This PR fixes three issues 
CMR-3648 spatial mapping between ISO MENDS and UMM
CMR-3916 Tiling changes between ISO MENDS and UMM
CMR-3917 Tiling changes between ISO SMAP and UMM
I started with spatial mapping but since tiling was so inter-twined I ended up having to fix all three.
=> Fixed CMR-3648 ISO MENDS and UMM Mapping, CMR-3916/CMR-3917 ISO MENDS/SMAP Tiling mapping

common-app-lib/src/cmr/common_app/services/kms_lookup.clj, common-app-lib/test/cmr/common_app/test/services/kms_lookup.clj, ingest-app/src/cmr/ingest/services/messages.clj, system-int-test/src/cmr/system_int_test/data2/umm_spec_collection.clj, system-int-test/test/cmr/system_int_test/ingest/collection_keyword_validation_test.clj, transmit-lib/src/cmr/transmit/kms.clj
This PR adds collection's platform type to the kms validations.
=> As a Client User, I should receive an error when ingesting a collection with a Platform Type that is not in the KMS hierarchy

ingest-app/src/cmr/ingest/services/ingest_service.clj, ingest-app/src/cmr/ingest/services/messages.clj, system-int-test/src/cmr/system_int_test/utils/variable_util.clj, system-int-test/test/cmr/system_int_test/ingest/variable_ingest_test.clj, transmit-lib/src/cmr/transmit/variable.clj
I'd already done most of this in a previous branch; this work essentially adds (and corrects) some system integration tests and applies minor fixes to variable ingest code.
=> CMR-4167 Variable updates

metadata-db-app/README.md, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/search_test.clj, metadata-db-app/src/cmr/metadata_db/services/search_service.clj
=> CMR-4173: Fixed test and mdb search code for services.

common-app-lib/src/cmr/common_app/services/search/parameters/converters/nested_field.clj, indexer-app/src/cmr/indexer/data/concepts/variable.clj, indexer-app/src/cmr/indexer/data/index_set.clj, search-app/docs/api.md, search-app/src/cmr/search/services/messages/common_messages.clj, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, search-app/src/cmr/search/services/query_execution/facets/facets_v2_helper.clj, search-app/src/cmr/search/services/query_execution/facets/facets_v2_results_feature.clj, search-app/src/cmr/search/services/query_execution/facets/hierarchical_v2_facets.clj, system-int-test/src/cmr/system_int_test/utils/variable_util.clj, system-int-test/test/cmr/system_int_test/search/facets/collection_facets_v2_search_test.clj, system-int-test/test/cmr/system_int_test/search/facets/facet_responses.clj, system-int-test/test/cmr/system_int_test/search/variable/collection_measurement_search_test.clj
This added collection search by variables parameter (nested) and support to return Measurements and Variables in V2 facets.
=> CMR 4078: Added support to return Measurements and Variables in V2 facets

metadata-db-app/src/migrations/054_remove_provider_services_tables.clj
to determine provider specific services table and sequence names.
=> CMR-4263: Rewrite migration to not rely on source code functions

umm-spec-lib/src/cmr/umm_spec/test/echo10_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/echo10.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/echo10.clj
This PR adds CollectionCitation mappings for UMM <=> ECHO10
=> CMR-3930 adds echo10 mapping for collection citations

metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/delete_test.clj, metadata-db-app/src/cmr/metadata_db/data/memory_db.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/tag.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/variable.clj, system-int-test/test/cmr/system_int_test/ingest/provider_ingest_permissions_test.clj, system-int-test/test/cmr/system_int_test/ingest/variable_ingest_test.clj
Reverted changes due to failures in master CI/CD not present in CI/CD branch.
=> CMR-4247 - Rollback

metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/delete_test.clj, metadata-db-app/src/cmr/metadata_db/data/memory_db.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/tag.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/variable.clj, system-int-test/test/cmr/system_int_test/ingest/provider_ingest_permissions_test.clj, system-int-test/test/cmr/system_int_test/ingest/variable_ingest_test.clj
This is a re-try at the merge of CMR-4247, without the big refactor of the last commit in that branch.
=> CMR-4247 ingest delete updates (2)

common-app-lib/src/cmr/common_app/services/kms_lookup.clj, ingest-app/src/cmr/ingest/services/messages.clj, ingest-app/src/cmr/ingest/validation/validation.clj, system-int-test/test/cmr/system_int_test/ingest/collection_keyword_validation_test.clj
instead of Short Name and Long Name.
=> CMR-4235: Change data center validation to only look at Short Name

common-lib/src/cmr/common/concepts.clj, search-app/docs/api.md, search-app/src/cmr/search/api/routes.clj, search-app/src/cmr/search/services/acl_service.clj, system-int-test/src/cmr/system_int_test/data2/atom_json.clj, system-int-test/src/cmr/system_int_test/utils/search_util.clj, system-int-test/test/cmr/system_int_test/admin/cache_api_test.clj, system-int-test/test/cmr/system_int_test/search/variable/concept_retrieval_test.clj, system-int-test/test/cmr/system_int_test/search/variable/variable_association_test.clj
This is a quick feature-add for MMT so that they can do their testing and dev. The same ticket (CMR-4369) will have more branches to come that build upon this.
=> CMR-4369 search var by concept

search-app/docs/api.md, search-app/src/cmr/search/data/metadata_retrieval/metadata_transformer.clj, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, system-int-test/test/cmr/system_int_test/search/variable/variable_search_test.clj
As a Client User, I want to search variables by variable concept id.
=> CMR-4383: 

system-int-test/src/cmr/system_int_test/data2/umm_spec_variable.clj, umm-spec-lib/resources/json-schemas/umm/v1.9/umm-var-json-schema.json, umm-spec-lib/src/cmr/umm_spec/models/umm_variable_models.clj, umm-spec-lib/test/cmr/umm_spec/test/validation/umm_spec_variable_validation_tests.clj
This PR pulls in the latest UMM-Var schema with commit id: 2606c8c and updated CMR accordingly.
=> CMR-4378: Updated UMM-Var Schema to the latest at commit 2606c8c.

search-app/src/cmr/search/services/query_execution/facets/facets_v2_results_feature.clj, system-int-test/test/cmr/system_int_test/search/facets/collection_facets_v2_search_test.clj
EDSC is not ready to handle variable or service facets at this point. There is no reason to ever return the dummy facets that we used for the prototype last PI, so I removed that code. Variables will not be returned by default, but when EDSC is ready to start integrating variables we will set the CMR_INCLUDE_VARIABLE_FACETS=true configuration and they will be returned in V2 facets.
=> CMR-4403: Remove dummy service facets and disable variable facets by default

common-lib/src/cmr/common/util.clj, umm-spec-lib/resources/json-schemas/collection/umm/v1.10/umm-c-json-schema.json, umm-spec-lib/src/cmr/umm_spec/migration/collection_progress_migration.clj, umm-spec-lib/src/cmr/umm_spec/migration/distance_units_migration.clj, umm-spec-lib/src/cmr/umm_spec/migration/geographic_coordinate_units_migration.clj, umm-spec-lib/src/cmr/umm_spec/migration/version_migration.clj, umm-spec-lib/src/cmr/umm_spec/models/umm_collection_models.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version_migration.clj
This PR includes fixes for part B, C, E, F, I. of CMR-3365.
=> CMR-3365: Fixed B and E parts of the ticket.

umm-spec-lib/resources/json-schemas/collection/umm/v1.10/umm-cmn-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.9/umm-cmn-json-schema.json, umm-spec-lib/resources/json-schemas/service/umm/v1.0/umm-cmn-json-schema.json, umm-spec-lib/resources/json-schemas/variable/umm/v1.0/umm-cmn-json-schema.json, umm-spec-lib/src/cmr/umm_spec/dif_util.clj
None of these values have been used in UMM records. They are used in DIF 9 and DIF 10 and translated to UMM.
=> Cmr 4464 - Fixing RelatedURL sub-type typos

ingest-app/docs/api.md, ingest-app/src/cmr/ingest/api/collections.clj, ingest-app/src/cmr/ingest/api/core.clj, ingest-app/src/cmr/ingest/api/routes.clj, ingest-app/src/cmr/ingest/api/services.clj, ingest-app/src/cmr/ingest/api/variables.clj, ingest-app/src/cmr/ingest/services/ingest_service.clj, ingest-app/src/cmr/ingest/services/ingest_service/service.clj, ingest-app/src/cmr/ingest/services/ingest_service/variable.clj, ingest-app/src/cmr/ingest/validation/validation.clj, metadata-db-app/README.md, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/delete_test.clj, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/service_save_test.clj, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/variable_save_test.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/service.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/variable.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/variable_association.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/providers.clj, system-int-test/src/cmr/system_int_test/data2/umm_spec_service.clj, system-int-test/src/cmr/system_int_test/utils/ingest_util.clj, system-int-test/src/cmr/system_int_test/utils/service_util.clj, system-int-test/test/cmr/system_int_test/ingest/provider_ingest_permissions_test.clj, system-int-test/test/cmr/system_int_test/ingest/service_ingest_test.clj, system-int-test/test/cmr/system_int_test/ingest/variable_ingest_test.clj, umm-spec-lib/resources/json-schemas/service/umm/v1.0/umm-s-json-schema.json, umm-spec-lib/src/cmr/umm_spec/models/umm_service_models.clj, umm-spec-lib/src/cmr/umm_spec/test/umm_record_sanitizer.clj, umm-spec-lib/src/cmr/umm_spec/umm_spec_core.clj, umm-spec-lib/src/cmr/umm_spec/versioning.clj
This PR added save/delete service concept in metadata-db, added ingest-app endpoint for service update and delete, also updated umm-spec-lib for UMM-S support.
=> CMR-4468, 4469, 4273, etc.

access-control-app/Dockerfile, bootstrap-app/Dockerfile, common-app-lib/Dockerfile, cubby-app/Dockerfile, dev-system/Dockerfile, dev-system/support/build-for-container.sh, index-set-app/Dockerfile, indexer-app/Dockerfile, ingest-app/Dockerfile, metadata-db-app/Dockerfile, search-app/Dockerfile, virtual-product-app/Dockerfile
Some quick little clean-ups; this PR includes the commit from @chris-durbin's PR #310 and so can supersede it.
=> CMR-4457 - Reduce dockerfile redundancies

dev-system/support/build-and-test-ci.sh, dev-system/support/build-for-container.sh, dev-system/support/build.sh, project.clj, search-app/src/cmr/search/api/concepts_lookup.clj, search-app/src/cmr/search/api/concepts_search.clj, search-app/src/cmr/search/api/core.clj, search-app/src/cmr/search/api/providers.clj, search-app/src/cmr/search/api/routes.clj, search-app/src/cmr/search/services/query_service.clj, search-app/test/cmr/search/test/api/routes.clj, search-app/test/cmr/search/test/models/helpers.clj, search-app/test/cmr/search/test/services/query_execution.clj, search-app/test/cmr/search/test/services/query_execution/granule_counts_results_feature.clj, system-int-test/test/cmr/system_int_test/search/provider_holdings_test.clj
Instead of including this with the PR for the actual feature addition, I'm making a separate PR (in the interest of preserving @ygliuvt's sanity ... and good will!).
This is essentially a sequel to previous work that had started cleaning up/splitting up the search routes.
=> CMR-4479 Refactor search routes

dev-system/support/build-for-container.sh
Part of this was added the other day (the `clean-up` function); the rest of this was just done (removal of early exit, fix for directory change, and status messages to `stdout`).
=> CMR-4548 Docker build cleanup

common-app-lib/resources/templates/landing.html, common-app-lib/resources/templates/structure.html
The hero image fix broke some other pages, so this fixes the things that were broken by the PR that fixed the hero image
=> CMR-4567: fix documentation pages

indexer-app/src/cmr/indexer/data/concept_parser.clj, indexer-app/src/cmr/indexer/data/concepts/collection.clj, indexer-app/src/cmr/indexer/data/concepts/service.clj, indexer-app/src/cmr/indexer/data/concepts/variable.clj, indexer-app/src/cmr/indexer/data/elasticsearch.clj, indexer-app/src/cmr/indexer/data/index_set.clj, indexer-app/src/cmr/indexer/services/index_service.clj, metadata-db-app/README.md, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/delete_test.clj, metadata-db-app/src/cmr/metadata_db/config.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, search-app/docs/api.md, search-app/src/cmr/search/results_handlers/atom_json_results_handler.clj, search-app/src/cmr/search/results_handlers/atom_results_handler.clj, system-int-test/src/cmr/system_int_test/data2/atom.clj, system-int-test/src/cmr/system_int_test/data2/atom_json.clj, system-int-test/test/cmr/system_int_test/search/service/collection_service_search_test.clj, transmit-lib/src/cmr/transmit/metadata_db.clj
This PR sets up ingest service, variable association and service association events handling in CMR and added support to include has_formats field in collection search JSON response.
=> CMR-4485, CMR-4482

system-int-test/test/cmr/system_int_test/search/acls/collection.clj
I ran the test locally more than 50 times and could not reproduce the failure. I checked every build on every branch that is still in Bamboo for everyone's fork. This particular test does not have a single failure.
It looks like the test is not failing at all anymore or failing extremely infrequently. I changed the test code to provide more information if the test does fail again.
=> CMR-4523: Updated test to use functions for better reporting when there is a test failure.

search-app/docs/api.md, search-app/src/cmr/search/results_handlers/umm_json_results_helper.clj, system-int-test/src/cmr/system_int_test/data2/umm_json.clj, system-int-test/test/cmr/system_int_test/search/service/collection_service_search_test.clj, umm-spec-lib/resources/json-schemas/collection/umm/v1.0/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.1/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.10/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.2/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.3/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.4/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.5/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.6/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.7/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.8/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.9/umm-search-results-json-schema.json, umm-spec-lib/src/cmr/umm_spec/models/umm_collection_models.clj, umm-spec-lib/src/cmr/umm_spec/models/umm_common_models.clj
As a Client User, I want collection UMM JSON search response to include variable and service associations.
As a Client User, I want to collection search UMM JSON response to include has_variables, has_transforms, has_formats fields.
=> CMR-4486; CMR-4483

common-lib/project.clj, dev-system/project.clj, indexer-app/src/cmr/indexer/data/concepts/service.clj, indexer-app/src/cmr/indexer/data/index_set.clj, search-app/docs/api.md, search-app/src/cmr/search/results_handlers/atom_json_results_handler.clj, search-app/src/cmr/search/results_handlers/atom_results_handler.clj, search-app/src/cmr/search/results_handlers/umm_json_results_helper.clj, system-int-test/src/cmr/system_int_test/data2/atom.clj, system-int-test/src/cmr/system_int_test/data2/atom_json.clj, system-int-test/src/cmr/system_int_test/data2/umm_json.clj, system-int-test/test/cmr/system_int_test/search/service/collection_service_search_test.clj, umm-spec-lib/resources/json-schemas/collection/umm/v1.0/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.1/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.10/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.2/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.3/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.4/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.5/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.6/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.7/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.8/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.9/umm-search-results-json-schema.json
Not 100% sure if this is what @ygliuvt and @chris-durbin had in mind, but seems like it should be close :-)
=> CMR-4582 Add support for has-spatial-subsetting

search-app/docs/api.md
This PR updates the search api docs, changing ISO SMAP and ISO MENDs specification links
=> CMR-4541 CMR API documentation - change the link "See the specification" for ISO-MENDS (ISO-19115) and ISO SMAP

metadata-db-app/README.md, metadata-db-app/int_test/cmr/metadata_db/int_test/concepts/force_delete_test.clj, metadata-db-app/src/cmr/metadata_db/api/concepts.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, system-int-test/src/cmr/system_int_test/utils/metadata_db_util.clj, system-int-test/test/cmr/system_int_test/search/acls/collection.clj, system-int-test/test/cmr/system_int_test/search/service/force_delete_test.clj, system-int-test/test/cmr/system_int_test/search/variable/force_delete_test.clj, system-int-test/test/cmr/system_int_test/search/variable/variable_revisions_search_test.clj
Updated cascading delete behaviour for variables to match that of services.
=> CMR-4495 variable force delete

bootstrap-app/README.md, bootstrap-app/src/cmr/bootstrap/api/bulk_index.clj, bootstrap-app/src/cmr/bootstrap/api/routes.clj, bootstrap-app/src/cmr/bootstrap/data/bulk_index.clj, bootstrap-app/src/cmr/bootstrap/data/message_queue.clj, bootstrap-app/src/cmr/bootstrap/services/bootstrap_service.clj, bootstrap-app/src/cmr/bootstrap/services/dispatch/core.clj, bootstrap-app/src/cmr/bootstrap/services/dispatch/impl/async.clj, bootstrap-app/src/cmr/bootstrap/services/dispatch/impl/message_queue.clj, bootstrap-app/src/cmr/bootstrap/services/dispatch/impl/sync.clj, system-int-test/src/cmr/system_int_test/utils/bootstrap_util.clj, system-int-test/src/cmr/system_int_test/utils/url_helper.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/services_test.clj
As a CMR Operator, I want to bulk index all services for a given provider.
As a CMR Operator, I want to bulk index all services in CMR.
=> CMR-4500, CMR-4501

umm-spec-lib/resources/example_data/dif10/artificial_test_data_2.xml, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/dif10.clj, umm-spec-lib/test/cmr/umm_spec/test/xml_to_umm_mappings/dif10.clj
This pull request fixes the dif10 to umm parsing where the temporal extent RangeDateTimes are malformed in some way.
=> CMR-4592 Date parsing error in indexing

ingest-app/src/cmr/ingest/services/bulk_update_service.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj, umm-spec-lib/src/cmr/umm_spec/field_update.clj, umm-spec-lib/test/cmr/umm_spec/test/field_update.clj
This PR fixed the issues in both CMR-4607 and 4608.
=> CMR-4607-4608.

search-app/src/cmr/search/services/query_execution/facets/collection_v2_facets.clj, search-app/src/cmr/search/services/query_execution/facets/facets_v2_helper.clj, search-app/src/cmr/search/services/query_execution/facets/facets_v2_results_feature.clj, search-app/src/cmr/search/services/query_execution/facets/granule_v2_facets.clj, search-app/src/cmr/search/services/query_execution/facets/temporal_facets.clj, search-app/src/cmr/search/services/query_service.clj, search-app/src/cmr/search/services/query_walkers/facet_condition_resolver.clj, search-app/src/cmr/search/services/query_walkers/update_field_resolver.clj, system-int-test/test/cmr/system_int_test/search/facets/granule_v2_facets_search_test.clj
The facet response at this point looks like:
```
{:title "Browse Granules",
:has_children true,
:children
[{:title "Temporal",
:has_children true,
:children
[{:title "Year",
:has_children true,
:children
[{:title "2012", :count 1}
{:title "2011", :count 1}
{:title "2010", :count 2}
{:title "1999", :count 1}]}]}]}
```
=> CMR-4682: As a Client User, I want to include temporal facet counts by year in granule facets

README.md
Some minor fixes to the README from @tmm2018.
=> Community Contribution: Minor README tweaks.

search-app/docs/api.md
Also moved the Humanizers documentation after facets (somehow it was in the middle of the facets section) and other general cleanup.
=> CMR-4682: Add V2 Granule Facets to API docs

umm-spec-lib/resources/json-schemas/service/umm/v1.0/umm-s-json-schema.json, umm-spec-lib/src/cmr/umm_spec/models/umm_service_models.clj, umm-spec-lib/src/cmr/umm_spec/test/umm_record_sanitizer.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_json.clj
Before we cut 1.0, I was asked to add one more change -- this PR is that change.
=> CMR-4691: Additional UMM-S Updates

system-int-test/test/cmr/system_int_test/ingest/collection_misc_validation_test.clj, system-int-test/test/cmr/system_int_test/ingest/collection_umm_spec_validation_test.clj, umm-spec-lib/resources/example_data/echo10/C1000000490-LARC_ASDC.xml, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/dif10.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/dif9.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/echo10.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/get_umm_element.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso19115_2.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_smap.clj
This PR fixes the collection CollectionProgress validation to properly return errors/warnings on ingest when a value is not provided.
=> CMR-4719 I don't get a warning or error when ingesting an ECHO 10 record without a CollectionState element

search-app/docs/api.md, search-app/src/cmr/search/api/routes.clj, search-app/src/cmr/search/results_handlers/services_json_results_handler.clj, search-app/src/cmr/search/validators/validation.clj, system-int-test/src/cmr/system_int_test/utils/service_util.clj, system-int-test/src/cmr/system_int_test/utils/variable_util.clj, system-int-test/test/cmr/system_int_test/search/service/service_revisions_search_test.clj, system-int-test/test/cmr/system_int_test/search/service/service_search_test.clj
I modified some of the existing tests to perform JSON searches instead of reference searches.
=> CMR-4660: Add support for searching for services in JSON format.

common-lib/src/cmr/common/api/errors.clj, search-app/src/cmr/search/api/concepts_search.clj, system-int-test/test/cmr/system_int_test/search/granule_search_test.clj
=> CMR-4781: Temporarily block a very specific query

metadata-db-app/src/cmr/metadata_db/data/oracle/concepts.clj
=> CMR-4783: Add optimizer hint for query that is oddly slower for one collection

system-int-test/test/cmr/system_int_test/ingest/collection_ingest_test.clj, system-int-test/test/cmr/system_int_test/search/collection_doi_search_test.clj, umm-spec-lib/resources/example_data/iso-smap/CMR-4721.xml, umm-spec-lib/resources/example_data/iso19115/CMR-4721-MENDS.xml, umm-spec-lib/src/cmr/umm_spec/migration/doi_migration.clj, umm-spec-lib/src/cmr/umm_spec/migration/version/collection.clj, umm-spec-lib/src/cmr/umm_spec/test/expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/iso_shared.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso19115_2.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso_smap.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_shared/doi.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version/collection.clj
This PR adds MissingReason and Explanation mapping to ISO SMAP and MENDS.
=> CMR-4721 Implement DOI not applicable translations to ISO and SMAP.

search-app/src/cmr/search/api/concepts_search.clj, system-int-test/test/cmr/system_int_test/search/all_granule_search_test.clj
=> CMR-4752: Strike currently from the message returned for all granules queries

access-control-app/int-test/cmr/access_control/int_test/access_control_group_acl_test.clj, common-app-lib/src/cmr/common_app/api/request_context_user_augmenter.clj, ingest-app/src/cmr/ingest/api/routes.clj, system-int-test/test/cmr/system_int_test/search/acls/collection.clj, system-int-test/test/cmr/system_int_test/search/humanizer/community_usage_metrics_test.clj, system-int-test/test/cmr/system_int_test/search/humanizer/humanizer_test.clj, system-int-test/test/cmr/system_int_test/search/tagging/tag_crud_test.clj, transmit-lib/src/cmr/transmit/echo/tokens.clj
This PR should be reviewed together with the Legacy Services PR. This added checking of NAMS CMR Ingest group during ingest.
=> CMR-4732: Made CMR changes to check on NAMS CMR Ingest group.

ingest-app/resources/CMR-4722/OMSO2.003-collection.xml, ingest-app/resources/CMR-4722/OMSO2.003-granule.xml, system-int-test/test/cmr/system_int_test/search/granule_orbit_search_test.clj
Bug is with searches crossing the equator erroneously matching the granule. Also updated comment block to fix code that helps visualize data on Google Earth.
=> CMR-4722/CMR-4804: Added test tracking cause of failure for CMR-4722

ingest-app/resources/CMR-4839-4651/iso19115_artificial_test_data.xml, system-int-test/test/cmr/system_int_test/ingest/translation_test.clj, umm-spec-lib/src/cmr/umm_spec/migration/related_url_migration.clj, umm-spec-lib/src/cmr/umm_spec/migration/version/collection.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_shared/use_constraints.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version/collection.clj
1. Added 1.9 to 1.10 migration for OnlineResourceType change; 
2. Modified the iso=>UMM parsing.
=> CMR-4839: Contains the last piece of clarification for CMR-4651.

transmit-lib/src/cmr/transmit/echo/tokens.clj
This task started with trying to fix the transmit lib get current sids function to use the new post endpoint added in ECHO REST (locally in my branch) and ended with the realization that this function is not being used at all. So this PR is simply to remove it.
=> CMR-4810: Removed unused function.

common-lib/src/cmr/common/xml.clj, search-app/src/cmr/search/results_handlers/metadata_results_handler.clj, system-int-test/src/cmr/system_int_test/data2/core.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj, umm-spec-lib/src/cmr/umm_spec/test/expected_conversion.clj
Fixed error in searching UMM JSON collections in native format.
=> CMR-4869: Fixed error in searching UMM JSON collections in native format

umm-spec-lib/src/cmr/umm_spec/migration/version/service.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version/service.clj
Fixes issue with migration related to CMR-4870
=> CMR-4808 fixes migration

umm-spec-lib/src/cmr/umm_spec/migration/version/service.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version/service.clj
Publishing UMM-S in cmr-dev-system-uberjar.jar results in 500 error
=> CMR-4874 fixes bug, adds test coverage

common-app-lib/src/cmr/common_app/api/health.clj
Added a context to define a route with multiple http operations.
=> CMR-4850: Fixed the OPTIONS bug.

common-app-lib/src/cmr/common_app/config.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj
NOTE: I expect some tests to fail here. I'll get to them once CI finishes
=> CMR-4945: UMM-C default version 1.9 -> 1.10

README.md
=> Typo on string #104 & 143

access-control-app/int-test/cmr/access_control/int_test/fixtures.clj, access-control-app/src/cmr/access_control/services/acl_authorization.clj, access-control-app/src/cmr/access_control/services/acl_service.clj, access-control-app/src/cmr/access_control/services/auth_util.clj, acl-lib/src/cmr/acl/acl_fetcher.clj, acl-lib/src/cmr/acl/core.clj, common-app-lib/src/cmr/common_app/services/search/datetime_helper.clj, indexer-app/int-test/cmr/indexer/test/data/concepts/collection_acls.clj, indexer-app/src/cmr/indexer/data/concepts/collection.clj, mock-echo-app/src/cmr/mock_echo/client/echo_util.clj, search-app/src/cmr/search/services/acls/granule_acls.clj, search-app/test/cmr/search/test/services/acls/granule_acls.clj, system-int-test/test/cmr/system_int_test/search/acls/collection.clj, system-int-test/test/cmr/system_int_test/search/acls/granule.clj, system-int-test/test/cmr/system_int_test/search/acls/temporal_collection_granule.clj, system-int-test/test/cmr/system_int_test/virtual_product/translation_test.clj, transmit-lib/src/cmr/transmit/access_control.clj, transmit-lib/src/cmr/transmit/echo/acls.clj, umm-lib/src/cmr/umm/acl_matchers.clj, umm-spec-lib/src/cmr/umm_spec/acl_matchers.clj, umm-spec-lib/test/cmr/umm_spec/test/acl_matchers.clj
Reverts nasa/Common-Metadata-Repository#522
Temporary revert while heritage build is fixed, and MMT has a chance to put in some changes to their test suite
=> Revert "CMR-4954 decouple access-control from echo in dev-system"

search-app/src/cmr/search/results_handlers/umm_json_results_handler.clj, system-int-test/src/cmr/system_int_test/data2/granule_counts.clj, system-int-test/src/cmr/system_int_test/data2/umm_json.clj, umm-spec-lib/resources/json-schemas/collection/umm/v1.0/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.1/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.10/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.2/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.3/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.4/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.5/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.6/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.7/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.8/umm-search-results-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.9/umm-search-results-json-schema.json
To match granule-count in all other formats.
=> CMR-4706: Changed granule_count to granule-count in umm_json result.

bootstrap-app/src/cmr/bootstrap/api/routes.clj, system-int-test/src/cmr/system_int_test/utils/bootstrap_util.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/concepts_test.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/delete_test.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/services_test.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/validation_test.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/variables_test.clj, system-int-test/test/cmr/system_int_test/bootstrap/rebalance_collections_test.clj
Issue: "As a CMR Operator, I want any reindexing requests to the bootstrap application to be rejected if the user does not have system ingest management update permission."
Added (acl/verify-ingest-management-permission request-context :update) to all bulk_index requests.
Added/Modified the tests.
=> CMR-5008: 

bootstrap-app/src/cmr/bootstrap/system.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/concepts_test.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/validation_test.clj
This is the addition to the 5008 fix that was merged.
=> CMR-5008: Fixed the token issue and added some tests.

umm-spec-lib/resources/example-data/umm-json/variable/v1.2/V1200241825-EDF_DEV01_v1_2.json, umm-spec-lib/resources/example-data/umm-json/variable/v1.2/V1200267323-HMR_TME_v_1_2.json, umm-spec-lib/resources/json-schemas/variable/umm/v1.2/umm-var-json-schema.json, umm-spec-lib/src/cmr/umm_spec/models/umm_variable_models.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_json.clj
The proposed update to UMM-Var 1.2 has been made; this PR represents the changes we needed to make in order to support the update.
This update will remove a great deal of confusion that has already arisen around the metadata being saved in the given fields, and should make things much easier for future developers/project contributors.
=> CMR-5107: Bounds to IndexRanges

indexer-app/src/cmr/indexer/data/concepts/collection.clj, indexer-app/src/cmr/indexer/data/concepts/collection/keyword.clj, indexer-app/src/cmr/indexer/data/concepts/keyword_util.clj, indexer-app/test/cmr/indexer/test/data/concepts/keyword_util.clj
Clean the cmr.indexer.data.concepts.collection.keyword namespace to use
the functions present in the cmr.indexer.data.concepts.keyword-util
namespace.
=> CMR-4755: Clean collections keyword namespace.

access-control-app/docs/acl-schema.md, access-control-app/int-test/cmr/access_control/int_test/acl_crud_test.clj, access-control-app/int-test/cmr/access_control/int_test/permission_check_test.clj, access-control-app/src/cmr/access_control/data/acl_schema.clj, access-control-app/src/cmr/access_control/services/acl_validation.clj
This PR Implements the following ACL targets and permissions
System Level: "Dashboard Admin Role" - CRUD, "Dashboard ARC Curator Role" - CRUD
Provider Level: "Dashboard DAAC Curator Role" - CRUD
=> CMR-5182 Add New CMR Dashboard ACL rules

search-app/docs/api.md
Updated supported CORS parameters. Add note about DIF 9 going away
=> CMR-5213: Small API doc updates

system-int-test/test/cmr/system_int_test/search/collection_concept_retrieval_test.clj
Add integration test for collection html search.
=> CMR-5081: Add integration test for html search.

umm-spec-lib/src/cmr/umm_spec/umm_g/characteristic.clj, umm-spec-lib/src/cmr/umm_spec/umm_g/granule.clj, umm-spec-lib/src/cmr/umm_spec/umm_g/instrument.clj, umm-spec-lib/src/cmr/umm_spec/umm_g/platform.clj, umm-spec-lib/src/cmr/umm_spec/umm_g/sensor.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_g/granule.clj
=> CMR-5066: Added support for Platforms, Instruments, Characteristics,  etc. in UMM-G.

umm-spec-lib/src/cmr/umm_spec/umm_g/granule.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_g/granule.clj
=> CMR-5070: Added support of CloudCover in UMM-G.

umm-spec-lib/src/cmr/umm_spec/umm_g/granule.clj, umm-spec-lib/src/cmr/umm_spec/umm_g/tiling_system.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_g/generators.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_g/granule.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_g/sanitizer.clj
This PR includes some refactoring of the umm-g test namespace, and the mappings TilingIdentificationSystem <=> TwoDCoordinateSystem for UMM-G v1.4
=> CMR-5071 As a Client User, I want to parse and generate two-d-coordinate-system in SWOT granule metadata format

umm-spec-lib/src/cmr/umm_spec/umm_g/granule.clj, umm-spec-lib/src/cmr/umm_spec/umm_g/project.clj, umm-spec-lib/src/cmr/umm_spec/umm_g/related_url.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_g/granule.clj
=> CMR-5068: Added support to RelatedUrls in UMM-G.

umm-spec-lib/src/cmr/umm_spec/umm_g/additional_attribute.clj, umm-spec-lib/src/cmr/umm_spec/umm_g/granule.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_g/granule.clj
=> CMR-5069: Added support of AdditionalAttributes in UMM-G.

umm-spec-lib/src/cmr/umm_spec/umm_g/granule.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_g/granule.clj
=> CMR-5061: Added support of AccessConstraints in UMM-G.

umm-spec-lib/src/cmr/umm_spec/umm_g/granule.clj, umm-spec-lib/src/cmr/umm_spec/umm_g/spatial.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_g/granule.clj
=> CMR-5063: Added support of SpatialExtent in UMM-G.

umm-spec-lib/src/cmr/umm_spec/umm_g/granule.clj, umm-spec-lib/src/cmr/umm_spec/umm_g/orbit_calculated_spatial_domain.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_g/expected_util.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_g/generators.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_g/sanitizer.clj
=> CMR-5064: Added support of OrbitCalculatedSpatialDomains in UMM-G.

ingest-app/src/cmr/ingest/services/ingest_service/granule.clj, system-int-test/src/cmr/system_int_test/data2/granule.clj, system-int-test/test/cmr/system_int_test/ingest/granule_ingest_test.clj, umm-spec-lib/src/cmr/umm_spec/umm_g/granule.clj
=> CMR-5211: Turn on UMM-G granule validation during ingest when all the fields involved in granule validation are supported 

indexer-app/src/cmr/indexer/data/concepts/granule.clj, indexer-app/src/cmr/indexer/data/index_set.clj, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, system-int-test/src/cmr/system_int_test/data2/granule.clj, system-int-test/test/cmr/system_int_test/search/granule_search_day_night_test.clj, system-int-test/test/cmr/system_int_test/search/granule_search_feature_id_crid_id_test.clj
=> CMR-5186: Added support to search granules by feature-id and crid-id.

system-int-test/test/cmr/system_int_test/ingest/granule_validation_test.clj
=> CMR-5260: Added tests for UMM-G granule validation endpoint.

common-lib/src/cmr/common/mime_types.clj, search-app/src/cmr/search/api/concepts_lookup.clj, search-app/src/cmr/search/data/metadata_retrieval/metadata_transformer.clj, search-app/src/cmr/search/validators/validation.clj, system-int-test/test/cmr/system_int_test/ingest/granule_ingest_test.clj, system-int-test/test/cmr/system_int_test/search/granule_retrieval_test.clj, umm-spec-lib/src/cmr/umm_spec/legacy.clj
=> CMR-5166: As a Client User, I want to retrieve granules in UMM-G format.

metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/variable_save_test.clj, metadata-db-app/src/cmr/metadata_db/services/concept_constraints.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/variables_test.clj, system-int-test/test/cmr/system_int_test/search/variable/concept_retrieval_test.clj, system-int-test/test/cmr/system_int_test/search/variable/variable_revisions_search_test.clj, system-int-test/test/cmr/system_int_test/search/variable/variable_search_test.clj
=> CMR-5248: As a UMM-VAR creator I should be able to ingest multiple UMM-VAR with the same name in the same provider.

bootstrap-app/README.md, bootstrap-app/src/cmr/bootstrap/api/bulk_index.clj, bootstrap-app/src/cmr/bootstrap/api/routes.clj, bootstrap-app/src/cmr/bootstrap/services/bootstrap_service.clj, system-int-test/src/cmr/system_int_test/utils/bootstrap_util.clj, system-int-test/src/cmr/system_int_test/utils/url_helper.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/concepts_test.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/core.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/delete_test.clj
=> CMR-4395: Added endpoint in bootstrap-app to bulk index all providers.

system-int-test/test/cmr/system_int_test/ingest/variable_ingest_test.clj, transmit-lib/src/cmr/transmit/http_helper.clj
=> CMR-5248: Added handling of 422 error in transmit-lib; Added variable update tests.

umm-spec-lib/resources/json-schemas/granule/umm/v1.4/umm-g-json-schema.json, umm-spec-lib/src/cmr/umm_spec/json_schema.clj, umm-spec-lib/src/cmr/umm_spec/models/umm_granule_models.clj, umm-spec-lib/src/cmr/umm_spec/test/umm_generators.clj, umm-spec-lib/src/cmr/umm_spec/umm_json.clj
Refs at the top level of oneOf/anyOf are now expanded.
=> CMR-5212: Add anyOf/oneOf top level ref support.

system-int-test/test/cmr/system_int_test/ingest/collection_umm_spec_validation_test.clj, umm-spec-lib/src/cmr/umm_spec/validation/spatial.clj, umm-spec-lib/test/cmr/umm_spec/test/validation/spatial.clj
Add check for CoordinateSystem/GranuleSpatialRepresentation
=> CMR-5093: Validate Spatial enums for MENDS.

umm-spec-lib/src/cmr/umm_spec/json_schema.clj, umm-spec-lib/src/cmr/umm_spec/models/umm_granule_models.clj, umm-spec-lib/src/cmr/umm_spec/record_generator.clj, umm-spec-lib/src/cmr/umm_spec/test/umm_generators.clj, umm-spec-lib/src/cmr/umm_spec/umm_json.clj
Auto generate umm g model rather than manual addition.
=> CMR-5212: Fix umm g model

collection-renderer-lib/project.clj
I think this is the correct commit, it isn't the merge commit though so if its not correct let me know.
=> CMR-4784 update cmr_metadata_preview commit

system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/delete_test.clj
Couldn't reproduce locally, I have a hunch that this is a timing issue caused by not waiting after rebalancing, so I've added a extra wait-until-indexed call and an assert to check the rebalancing status before doing the bulk deletes.
=> CMR-5386 Adds assert and wait to rebalanacing index in bulk-delete test

common-lib/project.clj, common-lib/suppression.xml
Suppressed vulnerabilities which could not be updated. Set date for unsuppression to 2019-02-19.
=> CMR-5311: Check common-lib vulnerabilities.

system-int-test/resources/iso-samples/5216_Valid_IsoSmap_Granule.xml, system-int-test/resources/iso-samples/CMR-5269-IsoSmapGranule.xml, system-int-test/test/cmr/system_int_test/search/granule_orbit_search_test.clj, system-int-test/test/cmr/system_int_test/search/granule_search_format_test.clj, umm-spec-lib/src/cmr/umm_spec/validation/granule.clj, umm-spec-lib/test/cmr/umm_spec/test/validation/umm_spec_granule_validation_tests.clj
This code had unintended behavior changes which made ingest rules too strict in some cases. It is being reverted for now so we can decide how to have our cake and eat it too
=> Revert CMR-5281

ingest-app/src/cmr/ingest/config.clj, umm-spec-lib/resources/example-data/umm-json/variable/v1.4/V1200241825-EDF_DEV01_v1_4.json, umm-spec-lib/resources/example-data/umm-json/variable/v1.4/V1200267323-HMR_TME_v_1_4.json, umm-spec-lib/resources/json-schemas/variable/umm/v1.4/umm-cmn-json-schema.json, umm-spec-lib/resources/json-schemas/variable/umm/v1.4/umm-var-json-schema.json, umm-spec-lib/resources/json-schemas/variable/umm/v1.4/umm-var-search-results-json-schema.json, umm-spec-lib/src/cmr/umm_spec/migration/version/variable.clj, umm-spec-lib/src/cmr/umm_spec/models/umm_variable_models.clj, umm-spec-lib/src/cmr/umm_spec/versioning.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version/variable.clj
UMM-Var version 1.4 removes :AvgCompressionRateASCII and :AvgCompressionRateNetCDF4
and replace them with the new :AverageCompressionInformation [{:Format "ASCII" :Rate <rate>} {:Format "NetCDF-4" :Rate <rate>}]
=> CMR-5429: Added support for UMM-Var 1.4.

system-int-test/resources/CMR-5490/5490_dif9_blank_platform_sn.xml, system-int-test/src/cmr/system_int_test/data2/core.clj, system-int-test/test/cmr/system_int_test/ingest/collection_update_test.clj, system-int-test/test/cmr/system_int_test/search/collection_platform_instrument_sensor_search_test.clj, umm-spec-lib/src/cmr/umm_spec/util.clj
=> CMR-5490: Treat a platform with a blank short name in DIF9 as not provided

cmr-exchange/exchange-query/project.clj, cmr-exchange/exchange-query/src/cmr/exchange/query/impl/cmr.clj, cmr-exchange/exchange-query/test/cmr/exchange/query/tests/unit/core.clj, cmr-exchange/exchange-query/test/cmr/exchange/query/tests/unit/util.clj, cmr-exchange/metadata-proxy/project.clj, cmr-exchange/metadata-proxy/src/cmr/metadata/proxy/concepts/variable.clj, cmr-exchange/ous-plugin/project.clj, cmr-exchange/ous-plugin/src/cmr/ous/common.clj, cmr-exchange/ous-plugin/test/cmr/ous/tests/unit/util/query.clj, cmr-exchange/service-bridge/project.clj, cmr-exchange/service-bridge/test/cmr/opendap/tests/system/app/sizing/netcdf4.clj, cmr-exchange/ses-plugin/project.clj, cmr-exchange/ses-plugin/src/cmr/sizing/core.clj, cmr-exchange/ses-plugin/src/cmr/sizing/formats.clj
This ticket only handles variable_aliases search in SES.  As for service_id and the new formats that come with EGI request, they will be handled in future tickets.
=> CMR-5420-CMR-5421: Added support for variable alias search in SES.

indexer-app/src/cmr/indexer/data/concepts/collection.clj, indexer-app/src/cmr/indexer/data/concepts/collection/collection_util.clj, indexer-app/src/cmr/indexer/data/index_set.clj, search-app/docs/api.md, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, system-int-test/test/cmr/system_int_test/search/collection_boolean_flag_search_test.clj, umm-spec-lib/src/cmr/umm_spec/opendap_util.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_shared/distributions_related_url.clj
Adds has_opendap_url search parmeter for collection searches
=> CMR-5444 As a MMT User, I can search for collections that have a OPeNDAP service url

indexer-app/src/cmr/indexer/data/concepts/keyword_util.clj, indexer-app/src/cmr/indexer/data/concepts/variable.clj, search-app/docs/api.md, system-int-test/test/cmr/system_int_test/search/variable/variable_search_test.clj
Added keyword support for associated collection concept ids and the set name values of variables.
=> CMR-5369 Query for UMM_Var records by using various attributes in keyword search.

common-app-lib/resources/security/suppression.xml, cubby-app/resources/security/suppression.xml, es-spatial-plugin/resources/security/suppression.xml, index-set-app/resources/security/suppression.xml, mock-echo-app/resources/security/suppression.xml
Same vulnerabilities as with PR 716:
https://github.com/nasa/Common-Metadata-Repository/pull/716
=> CMR-5310,CMR-5312,CMR-5315,CMR-5316,CMR-5321: Fix vulnerabilities.

ingest-app/project.clj, ingest-app/src/cmr/ingest/config.clj, ingest-app/src/cmr/ingest/services/ingest_service/variable.clj, metadata-db-app/README.md, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/search/variable_search_test.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/utils/variable.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/variable_save_test.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/variable.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/search.clj, metadata-db-app/src/cmr/metadata_db/services/concept_constraints.clj, metadata-db-app/src/cmr/metadata_db/services/messages.clj, metadata-db-app/src/migrations/068_add_fingerprint_to_variables_table.clj, search-app/src/cmr/search/services/parameters/validation/track.clj, system-int-test/src/cmr/system_int_test/utils/variable_util.clj, system-int-test/test/cmr/system_int_test/ingest/variable_ingest_test.clj, umm-spec-lib/resources/example-data/umm-json/variable/v1.5/V1200241825-EDF_DEV01_v1_5.json
Design approach is at: https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=133744932
=> CMR-5291: As a metadata provider, I want CMR to validate variable name uniqueness.

collection-renderer-lib/resources/security/suppression.xml, common-app-lib/resources/security/suppression.xml, cubby-app/resources/security/suppression.xml, index-set-app/resources/security/suppression.xml, message-queue-lib/project.clj, message-queue-lib/resources/security/suppression.xml, metadata-db-app/project.clj, metadata-db-app/resources/security/suppression.xml, mock-echo-app/resources/security/suppression.xml, umm-lib/resources/security/suppression.xml, umm-spec-lib/resources/security/suppression.xml
* Use only needed aws-java-sdk packages in message-queue-lib.
* Update quartz in metadata-db.
* Suppress es, mintToken, clansi, and oracle vulnerabilities.
=> CMR-5320: metadata-db vulnerability updates.

ingest-app/README.md
wrap curl commands in `bash` code blocks and json in `json` code blocks
=> Update readme with better codeblocks

umm-spec-lib/src/cmr/umm_spec/test/iso19115_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/iso_shared.clj, umm-spec-lib/src/cmr/umm_spec/test/iso_smap_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/umm_record_sanitizer.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso19115_2.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso_shared/archive_and_dist_info.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso_shared/distributions_related_url.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso_smap.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso19115_2.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_shared/archive_and_dist_info.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_shared/distributions_related_url.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_smap.clj
Implements UMM-C 1.13 mapping for both ISO Mends and ISO SMAP
=> Update ISO MENDS Translation <=> UMM-C 1.13 ArchiveAndDistributionInformation

umm-spec-lib/resources/example-data/dif10/CMR-4908.xml, umm-spec-lib/src/cmr/umm_spec/util.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/dif10.clj, umm-spec-lib/test/cmr/umm_spec/test/umm_spec_test_util.clj
Values like "10MB" are failing to translate from dif10 XML to UMM in SIT, this PR is to fix that.
=> CMR-4908 Fixes Size/Unit parsing for certain Distribution_Size values.

umm-spec-lib/resources/json-schemas/variable/umm/v1.5/umm-var-json-schema.json
I added maxItems to be equal to 2 to the Lat and Long Ranges 
I increased the size of Definition from 1024 to 10000
=> Cmr 5687 Adding and changing constraints on the UMM-Var schema

dev-system/project.clj
=> CMR-5677: Change localcontext to singlethread.

bootstrap-app/README.md, bootstrap-app/src/cmr/bootstrap/data/fingerprint.clj, bootstrap-app/src/cmr/bootstrap/services/bootstrap_service.clj
Updated logging messages and log level.
=> CMR-5659 1

browse-scaler/src/docker-compose.yml, browse-scaler/zip-browse-scaler.sh
Had problems with permissions in CI tool because containers were writing
information as the wrong user id. This should address that.
=> Updating so testing containers run as right uid

ingest-app/src/config/ingest_migrate_config.clj, metadata-db-app/src/config/mdb_migrate_config.clj
Changes need to get migrations working in Bamboo
=> CMR-5479: Chane namespae prefixes in configs

browse-scaler/src/cache.js, browse-scaler/src/cmr.js, browse-scaler/src/index.js, browse-scaler/src/resize.js
- add some error handling
- update image filter regex
- properly return images from the cache
- fix resizing
=> CMR-5781: Fix caching and not-found response

project.clj
Fix site and api documentation routes.
=> CMR-5775: Generate static before install.

collection-renderer-lib/project.clj
* only render NASA logo in collection overview section for NASA data centers
* MMT-1881 - change tab to Citation Information
=> MMT-1851: only render NASA logo for NASA collections

system-int-test/test/cmr/system_int_test/ingest/provider_cmr_only_client_id_test.clj, system-int-test/test/cmr/system_int_test/virtual_product/virtual_product_test.clj, virtual-product-app/project.clj, virtual-product-app/src/cmr/virtual_product/services/virtual_product_service.clj
This PR adds the ability to ingest umm-json using virtual product service.
=> CMR-5848 Virtual product does not work with granules ingested as umm-json

.gitignore, browse-scaler/src/package-lock.json, browse-scaler/src/package.json
> browse-scaler@1.0.0 test /Users/mschmele/repositories/cmr/browse-scaler/src
> jest --coverage
-----------|----------|----------|----------|----------|-------------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------|----------|----------|----------|----------|-------------------|
All files  |     56.6 |       60 |       30 |    55.77 |                   |
cmr.js    |    51.35 |       50 |       25 |       50 |... 77,78,81,82,84 |
resize.js |    68.75 |       75 |       50 |    68.75 |    28,29,38,41,42 |
-----------|----------|----------|----------|----------|-------------------| command
=> CMR-5948: add code coverage option to

search-app/src/cmr/search/site/static.clj
=> CMR-5973: Added release version to CMR search api and site pages.

ingest-app/src/cmr/ingest/api/translation.clj
This was causing 500 errors in ingest when a user passed an accept header in the format "Accept: "
No test was added because I could not figure out how to simulate this with our internal http library and I didn't want to use (shell curl ...). Any suggestions appreciated.
=> CMR-5495 Fix issue with translation endpoint causing 500 error.

collection-renderer-lib/project.clj, collection-renderer-lib/src/cmr/collection_renderer/services/collection_renderer.clj, collection-renderer-lib/support/install_gems.sh
allow mmt to update preview gem version easily.
=> CMR-6049: Allow update of preview gem version.

site-templates/resources/templates/structure.html
Adds Google Tag Manager code to our pages
=> CMR-5247: Add Google Tag Manager code

browse-scaler/src/cache.js
Browse scaler to not fail on redis issues.
=> CMR-6076: Catch redis exception in browse scaler.

common-app-lib/src/cmr/common_app/config.clj, system-int-test/test/cmr/system_int_test/ingest/collection_ingest_test.clj, system-int-test/test/cmr/system_int_test/ingest/collection_translation_test.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj, umm-spec-lib/resources/json-schemas/collection/umm/v1.15/umm-c-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.15/umm-cmn-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.15/umm-search-results-json-schema.json, umm-spec-lib/src/cmr/umm_spec/migration/spatial_extent_migration.clj, umm-spec-lib/src/cmr/umm_spec/migration/version/collection.clj, umm-spec-lib/src/cmr/umm_spec/models/umm_collection_models.clj, umm-spec-lib/src/cmr/umm_spec/models/umm_common_models.clj, umm-spec-lib/src/cmr/umm_spec/test/dif10_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/echo10_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/iso19115_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/dif10/spatial.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/echo10/spatial.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso19115_2/spatial.clj, umm-spec-lib/src/cmr/umm_spec/util.clj, umm-spec-lib/src/cmr/umm_spec/versioning.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/dif10/spatial.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/echo10/spatial.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso19115_2/spatial.clj, umm-spec-lib/test/cmr/umm_spec/test/generate_and_parse.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version/collection.clj
HorizontalDataResolutions is changed from array of individual resolution of different type to HorizontalDataResolution, which is a map of different named groups, each group contains the same type of the resolutions. This helps return more specific error messages when the user enters the wrong info.
=> CMR-6118: Added UMM-C V1.15

common-lib/src/cmr/common/concepts.clj, ingest-app/src/cmr/ingest/services/jobs.clj, ingest-app/test/cmr/ingest/test/services/jobs.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/subscription_save_test.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/utils/subscription.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/utility.clj, metadata-db-app/src/cmr/metadata_db/api/concepts.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concept_tables.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/subscription.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/search.clj, metadata-db-app/src/cmr/metadata_db/migrations/069_setup_subscriptions_table.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, metadata-db-app/src/cmr/metadata_db/services/concept_validations.clj, metadata-db-app/src/cmr/metadata_db/services/jobs.clj, metadata-db-app/src/cmr/metadata_db/services/messages.clj, metadata-db-app/src/cmr/metadata_db/services/search_service.clj
This PR doesn't provide the complete functionality of the email subscription processing background job. There is another ticket that will add the actual sending email part.
=> CMR-6172: Added email subscription processing job and the metadata-db support

collection-renderer-lib/project.clj
Verified with Chris that the html file for the collection ingested looks good.
=> CMR-6236: Updated Collection Preview Gems.

access-control-app/src/cmr/access_control/services/group_service.clj, elastic-utils-lib/src/cmr/elastic_utils/es_helper.clj, elastic-utils-lib/src/cmr/elastic_utils/es_index_helper.clj, elastic-utils-lib/src/cmr/elastic_utils/index_util.clj, indexer-app/src/cmr/indexer/data/index_set_elasticsearch.clj
With this PR, dev-system starts up fully without error.
=> CMR-6134: More changes to insert and searching via ES 7.5.2 API.

search-app/src/cmr/search/api/autocomplete.clj, search-app/src/cmr/search/models/query.clj, search-app/src/cmr/search/results_handlers/autocomplete_results_handler.clj, search-app/src/cmr/search/services/autocomplete_service.clj, search-app/src/cmr/search/services/parameters/conversion.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, system-int-test/test/cmr/system_int_test/search/autocomplete_collection_facet_search_test.clj
Re-review of CMR autocomplete functionality
Paying particular attention to 
* CMR-Hits header
* CMR-Took header
* validation of input params
* input params using CMR standard value and syntax
=> CMR-6235 Autocomplete functionality, CMR parameters and headers

access-control-app/dev/user.clj, dev-system/dev/user.clj, dev-system/src/cmr/dev_system/system.clj, elastic-utils-lib/src/cmr/elastic_utils/embedded_elastic_server.clj, indexer-app/int-test/cmr/indexer/test/services/index_fields.clj
be able to configure embedded es log level with dev-system persistent settings.
=> CMR-6134: Configured embedded es log level.

indexer-app/src/cmr/indexer/services/index_service.clj, search-app/src/cmr/search/results_handlers/autocomplete_results_handler.clj, system-int-test/test/cmr/system_int_test/search/autocomplete/suggestion_reindex_test.clj, system-int-test/test/cmr/system_int_test/search/autocomplete_collection_facet_search_test.clj
=> CMR-6287: Changes to structure of science keyword indexing and response

search-app/project.clj
Updates geotools dependency version
=>  CMR-6315: Update geotools version

indexer-app/src/cmr/indexer/services/index_service.clj, search-app/src/cmr/search/services/autocomplete_service.clj, system-int-test/test/cmr/system_int_test/search/autocomplete/suggestion_reindex_test.clj, system-int-test/test/cmr/system_int_test/search/autocomplete_collection_facet_search_test.clj
Fixed re-indexing tests to properly test re-indexing code
=> CMR-6318 updated re-indexing to work better with es7

.gitignore, indexer-app/src/cmr/indexer/services/event_handler.clj, indexer-app/src/cmr/indexer/services/index_service.clj, indexer-app/src/cmr/indexer/system.clj, ingest-app/src/cmr/ingest/data/ingest_events.clj, ingest-app/src/cmr/ingest/services/jobs.clj, ingest-app/src/cmr/ingest/system.clj
Adding a job to run once every 24 hours to reindex autocomplete suggestions
=> CMR-6283 daily autocomplete suggestion reindex job

indexer-app/src/cmr/indexer/data/concepts/collection.clj, search-app/src/cmr/search/data/query_to_elastic.clj, search-app/src/cmr/search/services/community_usage_metrics/metrics_service.clj, search-app/src/cmr/search/services/parameters/legacy_parameters.clj, search-app/src/cmr/search/services/parameters/parameter_validation.clj, system-int-test/test/cmr/system_int_test/search/collection_sorting_search_test.clj
`usage_score` should now correctly sort collections
=> CMR-6365 collections search accepts usage_score sort parameter

ingest-app/resources/CMR-6431/iso-orbit-collection.xml, orbits-lib/resources/orbits/geometry_backtracking.rb, system-int-test/test/cmr/system_int_test/search/granule_orbit_search_test.clj
After the exception in the original ticket is fixed, there is another collection in SIT caused a different exception. This PR fixes the second exception that is uncovered once the first one is fixed.
=> CMR-6431: Fixed another case of exception in orbit code.

acl-lib/src/cmr/acl/core.clj, ingest-app/src/cmr/ingest/api/subscriptions.clj, ingest-app/src/cmr/ingest/system.clj, mock-echo-app/src/cmr/mock_echo/client/echo_util.clj, system-int-test/src/cmr/system_int_test/utils/subscription_util.clj, system-int-test/test/cmr/system_int_test/admin/cache_api_test.clj, system-int-test/test/cmr/system_int_test/ingest/subscription_ingest_test.clj, system-int-test/test/cmr/system_int_test/search/subscription/concept_retrieval_test.clj, system-int-test/test/cmr/system_int_test/search/subscription/subscription_revisions_search_test.clj, system-int-test/test/cmr/system_int_test/search/subscription/subscription_search_test.clj
Part1 of 2(This PR): Enforce EMAIL_SUBSCRIPTION_MANAGEMENT ACL on Subscription ingest.
Part2 of 2(To be continued): Enforce EMAIL_SUBSCRIPTION_MANAGEMENT ACL on Subscription search.
=> Cmr 6415 enforce email subscription management acl

common-app-lib/src/cmr/common_app/config.clj, indexer-app/src/cmr/indexer/data/concepts/collection.clj, indexer-app/src/cmr/indexer/data/concepts/collection/distributed_format_util.clj, indexer-app/test/cmr/indexer/test/data/concepts/collection/distributed_format_util.clj, system-int-test/test/cmr/system_int_test/search/collection_search_data_format_test.clj, system-int-test/test/cmr/system_int_test/search/collection_search_format_test.clj, system-int-test/test/cmr/system_int_test/search/umm_json_search_test.clj, umm-spec-lib/resources/example-data/iso19115/artificial_test_data.xml, umm-spec-lib/resources/json-schemas/collection/umm/v1.15.3/umm-c-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.15.3/umm-cmn-json-schema.json, umm-spec-lib/resources/json-schemas/collection/umm/v1.15.3/umm-search-results-json-schema.json, umm-spec-lib/src/cmr/umm_spec/migration/version/collection.clj, umm-spec-lib/src/cmr/umm_spec/models/umm_collection_models.clj, umm-spec-lib/src/cmr/umm_spec/test/dif10_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/echo10_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/expected_conversion_util.clj, umm-spec-lib/src/cmr/umm_spec/test/iso_shared.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso_shared/archive_and_dist_info.clj, umm-spec-lib/src/cmr/umm_spec/versioning.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/dif10.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/echo10.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_shared/archive_and_dist_info.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_shared/shared_iso_parsing_util.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version/collection.clj, umm-spec-lib/test/cmr/umm_spec/test/xml_to_umm_mappings/echo10.clj, umm-spec-lib/test/cmr/umm_spec/test/xml_to_umm_mappings/iso_shared/archive_and_dist_info.clj
Also moving the Format parsing code to the indexer so that translations work correctly and the parsing for Data Formats also works correctly.
=> Cmr 6366 - Creating UMM-C Version 1.15.3 - Adding FormatDescription for ArchiveAndDistributionInformation

collection-renderer-lib/project.clj
Updated the preview gems and tested the features stated in the ticket.
=> CMR-6483: Updated preview gems.

cmr-exchange/exchange-common/resources/security/suppression.xml, cmr-exchange/metadata-proxy/resources/security/suppression.xml, cmr-exchange/service-bridge/resources/security/suppression.xml, cmr-exchange/ses-plugin/resources/security/suppression.xml, ingest-app/project.clj, metadata-db-app/project.clj
Tests were run locally, both applications were built without errors, not sure what else to check to ensure it is working.
=> CMR-5370 - updating jar files to resolve a CVE

ingest-app/project.clj, ingest-app/src/cmr/ingest/services/jobs.clj, ingest-app/test/cmr/ingest/test/services/jobs.clj
changed the email message to markdown and added a test. Content changes per request
=> CMR-6612 - Update to Subscription Email Content

search-app/test/cmr/search/services/query_execution/facets/granule_v2_facets_test.clj
Code was pushed to master incorrectly. One test had not been resolved yet on the branch. This corrects the test.
=> CMR-6672 fixed failing test

search-app/resources/templates/search-provider-tag-landing-links.html, search-app/src/cmr/search/services/query_execution/facets/cycle_facets.clj, search-app/src/cmr/search/services/query_execution/facets/granule_v2_facets.clj, system-int-test/test/cmr/system_int_test/search/facets/granule_v2_facets_search_test.clj, system-int-test/test/cmr/system_int_test/site/holdings_provider_test.clj
=> CMR-6673 Fixed count of cycle aggregation to use id

search-app/src/cmr/search/services/query_execution/granule_counts_results_feature.clj, system-int-test/test/cmr/system_int_test/search/collection_spatial_search_test.clj
New test condition simply there to make sure there is no error when combining spatial OR option and granule counts feature
=> CMR-6722: Fix issue with granule_counts_results_feature and spatial ORing

search-app/docs/api.md
Looks like the order of my merge conflict resolution with my last merge didn't work.  This PR removes the bad lines.
=> CMR-6624 Fixes merge conflict documentation.

metadata-db-app/src/cmr/metadata_db/migrations/073_add_tool_associations_table.clj
This table should have the same content as CMR_SERVICE_ASSOCIATIONS, which combines 065_add_service_associations_table.clj and 067_add_indices_to_variable_service_association_tables.clj
=> CMR-6816: Created CMR_TOOL_ASSOCIATIONS table.

common-app-lib/src/cmr/common_app/api/routes.clj, ingest-app/src/cmr/ingest/routes.clj, search-app/src/cmr/search/routes.clj, system-int-test/test/cmr/system_int_test/header_test.clj
This PR is a revert of a revert done a while back, the new headers were causing issues with the css in the ingest and search documentation pages, a recent update has fixed that issue and allowed for these changes again.
=> CMR-5806 5809

search-app/test/cmr/search/test/services/humanizers/humanizer_range_facet_service.clj
As per Leo: Our tests are taking too long to run. I don’t think we need to test everything just for the sake of testing. The unit test above it is good enough for the default case.  So it was decided to delete the test. I have successfully built the branch 3 times without any errors. Building another one while this pull request is open.
=> CMR-6941 removing not needed intermittened failed test.

ingest-app/src/cmr/ingest/api/subscriptions.clj, system-int-test/test/cmr/system_int_test/ingest/subscription_ingest_test.clj
=> CMR-6807 Adds subscriber-id lookup to acl bypass for updating subscriptions

ingest-app/docs/api.md
* Updated GCMD links
* Moved Measurement Name keywords to correct section (this corresponds to variable validation, not collection)
=> CMR-6944: Updated ingest docs with new links for KMS

bootstrap-app/project.clj, cmr-exchange/dev-env-manager/project.clj, ingest-app/project.clj, message-queue-lib/project.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/reset_test.clj, metadata-db-app/project.clj, search-app/project.clj, system-int-test/project.clj, transmit-lib/project.clj
* Updated httpclient and other httpcomponents/codependencies where needed
* Fixed broken metadata-db-app integration test, which only passed by luck on old httpclient version
=> CMR-7016: Updated httpclient to 4.5.13

access-control-app/README.md, acl-lib/README.md, bootstrap-app/README.md, collection-renderer-lib/README.md, common-app-lib/README.md, common-lib/README.md, dev-system/README.md, elastic-utils-lib/README.md, es-spatial-plugin/README.md, indexer-app/README.md, ingest-app/README.md, message-queue-lib/README.md, metadata-db-app/README.md, mock-echo-app/README.md, oracle-lib/README.md, search-app/README.md, search-relevancy-test/README.md, site-templates/README.md, spatial-lib/README.md, transmit-lib/README.md, umm-lib/README.md, umm-spec-lib/README.md, virtual-product-app/README.md
Found a ticket to update readme files copyright date, found a bunch, I changed everything not in cmr-exchange.
=> CMR-6834 - updating the readme files

CONTRIBUTING.md, LICENSE, site-templates/LICENSE
Mitch found a file I missed, used a different grep chain and I found 3 in all.
grep -ir "copyright " * | grep -v 2021 | grep -v cmr-exchange | grep -v gml | grep -v xml | grep 20
=> CMR-6834 - updating License and contributing files

search-app/project.clj
* Explicitly imported Updated jackson-dataformat
=> CMR-7028: Update geotools subdependencies

search-app/project.clj
Reverts nasa/Common-Metadata-Repository#1152
=> Revert "CMR-7028: Update geotools subdependencies"

search-app/project.clj
* Explicitly imported newer version of jackson-dataformat
=> CMR-7028: Updated jackson-dataformat

ingest-app/docs/api.md, ingest-app/resources/granule_bulk_update_schema.json, ingest-app/src/cmr/ingest/api/bulk.clj, ingest-app/src/cmr/ingest/api/routes.clj, ingest-app/src/cmr/ingest/config.clj, ingest-app/src/cmr/ingest/services/bulk_update_service.clj, ingest-app/src/cmr/ingest/services/granule_bulk_update_service.clj, system-int-test/test/cmr/system_int_test/ingest/bulk_update/bulk_update_test.clj
Laying more foundation for bulk granule update. The majority of the work for this feature is going to be done in the upcoming sprint
=> CMR-7088: update API routes and documentation for bulk granule update

ingest-app/docs/api.md, ingest-app/test/cmr/ingest/api/subscriptions_test.clj, ingest-app/test/cmr/ingest/test/services/jobs.clj
updating the documentation to mention URL encoding and also adding a test for more code coverage which was in a ticket that got closed.
=> cmr-7144 - Updating API doc and adding a test

ingest-app/src/cmr/ingest/services/granule_bulk_update/opendap/umm_g.clj, ingest-app/test/cmr/ingest/services/granule_bulk_update/opendap/umm_g_test.clj
Fixed a missed case in appending umm-g opendap urls
=> CMR-7235 opendap append with umm-g

oracle-lib/README.md
Gave a better search term for finding the jars, helping any developers to find the correct version of the jars.
=> CMR-7241: Small docs change

ingest-app/docs/api.md
* Ingest API Document Granule Bulk Update Section Updated with best practices information for running BGU
=> CMR-7374: BGU usage documentation

search-app/project.clj
* Bumped rhino, nested dependency of `[metosin/ring-swagger "0.22.14"]`
=> CMR-7556: Bumped rhino version

search-app/src/cmr/search/services/query_execution/granule_counts_results_feature.clj, search-app/test/cmr/search/test/services/query_execution/granule_counts_results_feature.clj, system-int-test/test/cmr/system_int_test/search/granule_counts_search_test.clj
Rolling this back while I try to pinpoint errors coming up in SIT
=> CMR-6745: rollback

ingest-app/src/cmr/ingest/services/granule_bulk_update/size/echo10.clj, system-int-test/test/cmr/system_int_test/ingest/granule_bulk_update/granule_bulk_update_test.clj
* This commit was intended to be part of the last PR, but I forgot to push the changes up before merging. _Oof_
=> CMR-7504: Test fix

ingest-app/docs/api.md, ingest-app/resources/CMR-7505/7505-Updated.xml, ingest-app/resources/CMR-7505/7505.xml, ingest-app/resources/granule_bulk_update_schema.json, ingest-app/src/cmr/ingest/services/granule_bulk_update/format/echo10.clj, ingest-app/src/cmr/ingest/services/granule_bulk_update_service.clj, ingest-app/test/cmr/ingest/services/granule_bulk_update/checksum_size_format/echo10_test.clj, system-int-test/test/cmr/system_int_test/ingest/granule_bulk_update/granule_bulk_update_test.clj
* Simple BGU for <DataFormat> in echo10
=> CMR-7505: Bulk Granule Update for Format in Echo10

common-app-lib/src/cmr/common_app/api/routes.clj, common-app-lib/src/cmr/common_app/services/search.clj, common-app-lib/src/cmr/common_app/services/search/elastic_results_to_query_results.clj, common-app-lib/src/cmr/common_app/services/search/elastic_search_index.clj, common-app-lib/src/cmr/common_app/services/search/params.clj, common-app-lib/src/cmr/common_app/services/search/results_model.clj, search-app/docs/api.md, search-app/src/cmr/search/api/concepts_search.clj, search-app/src/cmr/search/results_handlers/atom_results_handler.clj, search-app/src/cmr/search/results_handlers/kml_results_handler.clj, search-app/src/cmr/search/results_handlers/metadata_results_handler.clj, search-app/src/cmr/search/results_handlers/umm_json_results_helper.clj, search-app/src/cmr/search/services/query_service.clj, search-app/src/cmr/search/validators/all_granule_validation.clj, search-app/src/cmr/search/validators/validation.clj, system-int-test/src/cmr/system_int_test/utils/search_util.clj, system-int-test/test/cmr/system_int_test/misc/header_test.clj, system-int-test/test/cmr/system_int_test/search/granule_timeline_test.clj, system-int-test/test/cmr/system_int_test/search/harvesting_test.clj, system-int-test/test/cmr/system_int_test/search/search_after_search_test.clj
See the API doc in this PR for description of the new search-after feature.
=> CMR-7040: As a client, I would like to search CMR with search_after parameter for deep paging

dev-system/.gitignore, search-app/src/cmr/search/services/query_execution/granule_counts_results_feature.clj, search-app/test/cmr/search/test/services/query_execution/granule_counts_results_feature.clj, system-int-test/test/cmr/system_int_test/search/granule_counts_search_test.clj
This reverts commit 5016e6dec4ffc6227af372e569034edb90bfbcb2.
=> Revert "CMR-6745: fix errors thrown with ORed granule counts (#1308)"

ingest-app/docs/api.md, ingest-app/resources/granule_bulk_update_schema.json, ingest-app/src/cmr/ingest/services/granule_bulk_update/mime_type/umm_g.clj, ingest-app/src/cmr/ingest/services/granule_bulk_update_service.clj, ingest-app/test/cmr/ingest/services/granule_bulk_update/mime_type/umm_g_test.clj, system-int-test/test/cmr/system_int_test/ingest/granule_bulk_update/granule_bulk_update_test.clj
- BGU for RelatedUrl MimeType in UMM-G
=> CMR-7547: BGU for RelatedUrl MimeType in UMM-G

umm-lib/resources/schema/dif10/UmmCommon_1.2.xsd, umm-spec-lib/resources/xml-schemas/dif10/UmmCommon_1.2.xsd
…atible and to allow the new value from KMS
=> DIF 10 - adding Crewed Spacecraft enumeration to Platform Types

umm-spec-lib/resources/example-data/error-cases/CMR-5366.xml, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/iso_shared/distributions_related_url.clj, umm-spec-lib/test/cmr/umm_spec/test/xml_to_umm_mappings/iso_shared/distributions_related_url.clj
=> CMR-7751 adding URLContentType parsing for ISO records in the distribution section

ingest-app/src/cmr/ingest/config.clj, system-int-test/test/cmr/system_int_test/ingest/variable_ingest_test.clj, umm-spec-lib/resources/json-schemas/variable/umm/v1.8/business_rules_v1.8.md, umm-spec-lib/src/cmr/umm_spec/metadata_specification.clj
Fixing a bug found while testing, ingest needed a small change. Also updated documentation in two files by suggestion from others.
=> CMR-7847 - fixing ingest variable bug and some documentation suggestions

graph-db/package-lock.json, graph-db/package.json, transmit-lib/src/cmr/transmit/config.clj, transmit-lib/src/cmr/transmit/kms.clj
making the KMS schema override setting a standard defconf instead of trying to use a direct ENV variable. Adding some logs to show what CMR is doing in SIT.
=> CMR-8009 - renaming configuration variable name and adding a log

ingest-app/README.md, metadata-db-app/src/cmr/metadata_db/api/provider.clj, system-int-test/test/cmr/system_int_test/ingest/provider_ingest_test.clj
Also modified consortium description in https://git.earthdata.nasa.gov/projects/CMR/repos/cmr-soap-services/pull-requests/249
=> CMR-7840: Added validation of consortium at ingest.

ingest-app/docs/api.md
=> CMR-7798 updated ingest documentation to say UMM JSON version is required.

ingest-app/docs/api.md, ingest-app/src/cmr/ingest/api/subscriptions.clj, system-int-test/test/cmr/system_int_test/bootstrap/bulk_index/subscriptions_test.clj, system-int-test/test/cmr/system_int_test/ingest/provider_ingest_permissions_test.clj, system-int-test/test/cmr/system_int_test/ingest/subscription_ingest_test.clj, system-int-test/test/cmr/system_int_test/search/subscription/concept_retrieval_test.clj, system-int-test/test/cmr/system_int_test/search/subscription/subscription_revisions_search_test.clj, system-int-test/test/cmr/system_int_test/search/subscription/subscription_search_test.clj
Reverts nasa/Common-Metadata-Repository#1436
=> Revert "Cmr 7197"

system-int-test/src/cmr/system_int_test/system.clj, system-int-test/test/cmr/system_int_test/ingest/subscription_processing_test.clj, system-int-test/test/cmr/system_int_test/transmit/urs_test.clj
=> CMR-7854:Add subscription-job manual endpoint

umm-spec-lib/src/cmr/umm_spec/test/umm_record_sanitizer.clj
generate_and_parse.clj covers all the translation testing for FreeAndOpenData.
=> CMR-7923: Testing FreeAndOpenData translation amoung different formats.

indexer-app/src/cmr/indexer/data/concepts/collection.clj, indexer-app/src/cmr/indexer/data/concepts/collection/humanizer.clj, indexer-app/src/cmr/indexer/data/concepts/collection/platform.clj, indexer-app/test/cmr/indexer/test/data/concepts/collection/humanizer.clj, system-int-test/test/cmr/system_int_test/search/autocomplete/suggestion_reindex_test.clj
This change humanizes the values for the new platform hierarchy. It is also needed for autocomplete.
=> CMR-8067 humanizing :platform2-humanized values

common-app-lib/resources/test-humanizers.json, dev-system/resources/kms_examples/platforms, indexer-app/src/cmr/indexer/data/concepts/collection/platform.clj, indexer-app/test/cmr/indexer/test/data/concepts/collection/humanizer.clj, system-int-test/test/cmr/system_int_test/search/facets/collection_facets_v2_search_test.clj, system-int-test/test/cmr/system_int_test/search/keyword_endpoint_test.clj
Otherwise valid keywords don't show up on the platform facets.
=> Cmr 8077 - If the humanized platform short name does not exist in KMS, look it up using the original short name.

search-app/test/cmr/search/test/services/query_execution/facets/facets_v2_results_feature_test.clj
Missed a unit test when I created the branch and merged CMR-7662.  These values shouldn't show up anymore in the facet result set.
=> CMR-7662 Fixes facet unit test

transmit-lib/src/cmr/transmit/kms.clj
Forgot to make this change, moving debug level
=> CMR-8093 - a suggestion was made to move this to info from debug

umm-spec-lib/src/cmr/umm_spec/test/expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso19115_2/spatial.clj, umm-spec-lib/test/cmr/umm_spec/test/generate_and_parse.clj
CMR-8197 has been merged. Need to fix a bug in the translation from UMM-C to iso19115.
=> Cmr 8197 fix iso19115 translation

indexer-app/src/cmr/indexer/data/concepts/collection.clj, indexer-app/src/cmr/indexer/data/concepts/tag.clj, indexer-app/src/cmr/indexer/data/index_set.clj, ingest-app/src/cmr/ingest/services/ingest_service/collection.clj, ingest-app/src/cmr/ingest/validation/validation.clj, system-int-test/test/cmr/system_int_test/ingest/collection_ingest_test.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/iso19115_2/spatial.clj
There are two parts to this PR:
1. Indexing part: Done without testing which will be done in the search ticket CMR-8129.
2. Validation part: Done with testing.
=> CMR-8140: Indexed and validated StandardProduct.

search-app/docs/api.md, search-app/src/cmr/search/results_handlers/atom_json_results_handler.clj, search-app/src/cmr/search/results_handlers/atom_results_handler.clj, system-int-test/src/cmr/system_int_test/data2/atom.clj, system-int-test/src/cmr/system_int_test/data2/atom_json.clj, system-int-test/test/cmr/system_int_test/search/collection_cloud_hosted_search_test.clj
This PR added cloud_hosted in both ATOM and JSON response formats.
=> CMR-8242: As EDSC, I would like to be able to determine if a collection is cloud_hosted or not via the CMR JSON response.

.github/workflows/graph-db.yml, graph-db/.nvmrc, graph-db/package-lock.json, graph-db/package.json, graph-db/serverless.yml, graph-db/serverless/src/bootstrapGremlinServer/__test__/handler.test.js, graph-db/serverless/src/indexCmrCollection/handler.js, graph-db/serverless/src/utils/cmr/__test__/fetchPageFromCmr.test.js, graph-db/serverless/src/utils/cmr/__test__/getSecureParam.test.js, graph-db/serverless/src/utils/cmr/__test__/indexCollection.test.js, graph-db/serverless/src/utils/cmr/__test__/indexInstrument.test.js, graph-db/serverless/src/utils/cmr/__test__/indexPlatform.test.js, graph-db/serverless/src/utils/cmr/__test__/indexProject.test.js, graph-db/serverless/src/utils/cmr/__test__/indexRelatedUrl.test.js, graph-db/serverless/src/utils/cmr/fetchPageFromCMR.js, graph-db/serverless/src/utils/cmr/getSecureParam.js, graph-db/webpack.config.js
Upgrades Serverless to 3+, as well as other necessary libraries and Node.
=> CMR-8223: Upgrades Serverless

indexer-app/src/cmr/indexer/data/concepts/generic.clj, indexer-app/src/cmr/indexer/data/concepts/generic_util.clj, indexer-app/src/cmr/indexer/data/index_set.clj, indexer-app/src/cmr/indexer/data/index_set_elasticsearch.clj, indexer-app/src/cmr/indexer/data/index_set_generics.clj, ingest-app/src/cmr/ingest/api/generic_documents.clj
Follow up merge, the other merge was done accidentally, these changes are from feedback from that pull request.)
https://github.com/nasa/Common-Metadata-Repository/pull/1591
Mostly the change here are comments, however in one file includes were cleaned up and lowercase functions were standardized around the CMR version.
=> CMR-8185 - Prototype feedback from demo version, ready to merge into feature branch (not master)

graph-db/README.md, graph-db/package-lock.json, graph-db/package.json
This fixes the latest DoS Snyk Vulnerability in graph-db.
=> CMR-8509: Denial of Service (DoS) in nasa/Common-Metadata-Repository(master):graph-db/package.json

metadata-db-app/src/cmr/metadata_db/data/memory_db.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concept_tables.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/variable_association.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/providers.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/search.clj, metadata-db-app/src/cmr/metadata_db/migrations/080_rename_variable_associations.clj, metadata-db-app/src/cmr/metadata_db/migrations/081_rename_variable_associations.clj
Modified the code to make use of this new common table with new columns.
=> CMR-8187-CMR-8472:  Renamed CMR_VARIABLE_ASSOCIATIONS to the new common CMR_ASSOCIATIONS table

metadata-db-app/src/cmr/metadata_db/data/memory_db.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/generic_documents.clj, metadata-db-app/src/cmr/metadata_db/services/generic_documents.clj, transmit-lib/src/cmr/transmit/generic_documents.clj
…generic concept can have their own.
=> CMR-8521 Fixing the generic concepts concept id prefix, so that each generic concept can have their own.

indexer-app/src/cmr/indexer/data/index_set_generics.clj, indexer-app/test/cmr/indexer/test/data/index_set_generics.clj
proposed solution for validating index.json files as they are processed by the index creation code. Bad index files are skipped.
=> cmr-8569 confirm that a valid index.json file exists

search-app/docs/api.md
Removed the ECHO token deprecation message from the search API doc
=> Removed echo-token deprecation notice from search api

indexer-app/src/cmr/indexer/data/concepts/generic.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/generic_association.clj, search-app/src/cmr/search/services/association_validation.clj, search-app/src/cmr/search/services/generic_association_service.clj, system-int-test/src/cmr/system_int_test/utils/association_util.clj, system-int-test/src/cmr/system_int_test/utils/generic_util.clj, system-int-test/test/cmr/system_int_test/search/generic_association_test.clj, transmit-lib/src/cmr/transmit/generic_association.clj
This PR includes the fix for CMR-8681, which has to be fixed first.
=> Cmr 8648 generic association validation

ingest-app/src/cmr/ingest/api/generic_documents.clj, metadata-db-app/src/cmr/metadata_db/data/memory_db.clj, system-int-test/test/cmr/system_int_test/ingest/generics_test.clj
* Removes Concept-sub-type from API and metadatadb
=> CMR-8659: Cleanup the concept-sub-type

indexer-app/src/cmr/indexer/data/concepts/generic.clj, indexer-app/src/cmr/indexer/data/concepts/tool.clj, indexer-app/src/cmr/indexer/services/index_service.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, search-app/docs/api.md, search-app/src/cmr/search/services/association_validation.clj, system-int-test/test/cmr/system_int_test/search/generic_association_test.clj
Included api update for CMR-8649.
=> CMR-8673: Allow generic association for Tools.

ingest-app/docs/api.md
While testing CMR-8694, some errors were found in example metadata for variables, this change updates these documents.
=> CMR-8792 - Variable Association Documentation Update

legacy-migration/README.md, legacy-migration/migrate.py
In this first cut of the script, it is only coded to work with SIT. We will update the code to work with other environments as we add more data migrations.
=> CMR-8732: First cut of the legacy service migration script to support DataQualitySummary migration.

legacy-migration/migrate.py
This PR added support to migrate DATA_QUAL_SUMMARY_ASSIGN table in legacy services.
=> CMR-8736: As a CMR developer, I want to migrate DATA_QUAL_SUMMARY_ASSIGN in Legacy Services to CMR core in SIT.

schemas/resources/schemas/order-option/v1.0.0/schema.json
* Increasing the max length for the id field in order-option
=> CMR-8804: Increasing the max length for the id field in order-option

legacy-migration/migrate.py
This PR added support to migrate EJB_CAT_OPTN_ASSGN in Legacy Services to CMR core as associations between OrderOption and Collection concepts.
=> CMR-8737: As a CMR developer, I want to migrate EJB_CAT_OPTN_ASSGN in Legacy Services to CMR core in SIT.

.editorconfig, common-app-lib/src/cmr/common_app/static.clj, common-lib/src/cmr/common/config.clj, common-lib/src/cmr/common/generics_documentation.clj, common-lib/test/cmr/common/test/generics_documentation.clj, ingest-app/docs/api.md, legacy-migration/migrate.py, schemas/resources/schemas/data-quality-summary/v1.0.0/ingest.md, schemas/resources/schemas/data-quality-summary/v1.0.0/search.md, schemas/resources/schemas/grid/v0.0.1/ingest.md, schemas/resources/schemas/grid/v0.0.1/search.md, schemas/resources/schemas/order-option/v1.0.0/ingest.md, schemas/resources/schemas/order-option/v1.0.0/search.md, schemas/resources/schemas/service-entry/v1.0.0/ingest.md, schemas/resources/schemas/service-entry/v1.0.0/search.md, schemas/resources/schemas/service-option/v1.0.0/ingest.md, schemas/resources/schemas/service-option/v1.0.0/search.md
* Adding a new variable to publish all Generic Document Version numbers as a list
* Clean up of all the Generic Search and Ingest Documents
=> CMR-8788 - Update Ingest and Search Documentation for Generics

ingest-app/src/cmr/ingest/services/subscriptions_helper.clj, ingest-app/test/cmr/ingest/test/services/subscriptions_helper.clj
Added a link to the subscription notification emails that goes to the link specified by the CMR_SUBSCRIPTION_MANAGEMENT_PAGE defconfig, which should be the environment specific edsc subscription management page
=> CMR-8065 As a user, I should be able to unsubscribe from a subscription notification email with a single click

legacy-migration/migrate.py, search-app/docs/api.md
Updated EJB_CAT_OPTN_ASSGN migration to be associations between collection and UMM-S.
Added SERVICE_OPTION_ASSIGNMENT migration.
=> CMR-8738: As a CMR developer, I want to migrate SERVICE_OPTION_ASSIGNMENT in Legacy Services to CMR core in SIT

graph-db/package-lock.json, graph-db/package.json
This fixed the graph-db deployment issue resulted from the package upgrade.
=> CMR-8841: Fixed graph-db deployment.

indexer-app/src/cmr/indexer/data/elasticsearch.clj, indexer-app/src/cmr/indexer/services/index_service.clj, indexer-app/test/cmr/indexer/test/services/index_service.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/search/association_search_test.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/concepts/utils/generic.clj, metadata-db-app/int-test/cmr/metadata_db/int_test/utility.clj, metadata-db-app/src/cmr/metadata_db/api/concepts.clj, metadata-db-app/src/cmr/metadata_db/data/concepts.clj, metadata-db-app/src/cmr/metadata_db/data/ingest_events.clj, metadata-db-app/src/cmr/metadata_db/data/memory_db.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/search.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/sql_helper.clj, metadata-db-app/src/cmr/metadata_db/services/concept_service.clj, metadata-db-app/src/cmr/metadata_db/services/search_service.clj, transmit-lib/src/cmr/transmit/metadata_db.clj
Reduced the number of calls to the database for associations. 
Reduced the number of unnecessary indexing of concepts when an associated concept is re-indexed.
=> Cmr 8830 - Refactored code to alleviate performance problems.

search-app/docs/api.md, search-app/src/cmr/search/results_handlers/variables_json_results_handler.clj, system-int-test/src/cmr/system_int_test/utils/variable_util.clj, system-int-test/test/cmr/system_int_test/search/generic_association_test.clj, system-int-test/test/cmr/system_int_test/search/high_concept_number_test.clj, system-int-test/test/cmr/system_int_test/search/variable/variable_search_test.clj
* Adds associations and association-details to the variable's json response
* Adds documentation for .json response for search app's api.md
=> CMR-8853: Add associations and association details for variable .json endpoint

graph-db/serverless/src/utils/cmr/indexProject.js, schemas/resources/schemas/data-quality-summary/v1.0.0/search.md, schemas/resources/schemas/grid/v0.0.1/search.md, schemas/resources/schemas/order-option/v1.0.0/search.md, schemas/resources/schemas/service-entry/v1.0.0/search.md, schemas/resources/schemas/service-option/v1.0.0/search.md, system-int-test/test/cmr/system_int_test/search/generics_test.clj
* Adds more tests for search parameters for generics
=> CMR-8828: Update the generic tests to add all of the parameters to make sure they work

browse-scaler/README.md, browse-scaler/src/package-lock.json, browse-scaler/src/package.json
SNYK suggested that AWS SDK be updated, local test of example run in README worked.
=> CMR-8928 - ticking up AWS SDK in Browse Scaler

graph-db/package-lock.json, graph-db/package.json
Fixing the build failure by updating the `simple-git` package
=> CMR-8931: GraphDB build failure - Snyk scan

transmit-lib/src/cmr/transmit/echo/tokens.clj
This is to fix the bug caused by the previous merge.
=> Cmr 8885 token validation new

graph-db/package-lock.json, graph-db/package.json
https://ci.earthdata.nasa.gov/browse/CN2-CG208-BTS-1
=> CMR-8977: Update fast-xml-parser version

schemas/resources/schemas/provider/v1.0.0/ingest.md, schemas/resources/schemas/provider/v1.0.0/schema.json
Adding some corrections found while working on this ticket in the provider management project. This change simplifies a regular expression which was proving hard to use. Also fixed some mistakes in the documentation.
=> CMR-8958 - small schema update

efs-lib/src/cmr/efs/connection.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts.clj
Cleaner job delete wasn't working right, so it's been fixed
=> CMR-8910 DELETE concept from EFS fix

efs-lib/src/cmr/efs/connection.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/concepts.clj, metadata-db-app/src/cmr/metadata_db/data/oracle/sql_helper.clj
Fixing an issue present with cascading deletes (as found when a collection is 'deleted' and granules associated have a cascading delete done on them)
=> CMR-8910 (3) Adding DELETE to EFS

legacy-migration/README.md, legacy-migration/providers/README.md, legacy-migration/providers/migrate.py
Write a script to move data from the old system to the new schema by reading the old tables and generating json files which are then loaded into the provider system using the new command line program.
This ticket does not need to talk directly to the database, the restful legacy service api may be enough. Also it does not need to write directly to CMR, it could just create metadata which is uploaded latter.
=> CMR-8965: Create script to update legacy providers to new system (CMR)

schemas/resources/schemas/grid/v0.0.1/metadata.json, schemas/resources/schemas/grid/v0.0.1/schema.json
This request just changes some of the constraint conditions in the grid schema.
=> CMR-9025 Adding in changed grid schema and example record.

browse-scaler/README.md, browse-scaler/src/docker-compose.test.yml
Redis version needs to be bumped to fix build plan on bamboo
https://ci.earthdata.nasa.gov/browse/CN2-BN2533
=> CMR-9259: Update Redis for Browse-Scaler

aurora-postgres-lib/project.clj, aurora-postgres-lib/src/cmr/aurora/config.clj, aurora-postgres-lib/src/cmr/aurora/connection.clj
DATASTORE PROTOTYPE -- NOT GOING TO MASTER -- SEEKING 1 APPROVAL ONLY (FROM TYLER H)
Aurora Lib with needed connection stuff, a pinging utility, and protocol stubs
=> cmr-9165: add aurora lib with connection config

browse-scaler/src/package-lock.json, browse-scaler/src/package.json
Updates `sharp` a lib used for image resizing in browse-scaler to fix a vulnerability on https://app.snyk.io/org/esdis-cumulus-core-gibs-cmr-etc./project/61a802a2-9f53-4da4-b33e-a6c564d32992/pr-check/31c4f0dd-7a80-4b1b-a6ee-2d6faac3bc77
=> CMR-9472: Updating Sharp Dependency

browse-scaler/src/package-lock.json, browse-scaler/src/package.json
Updates the `package.json` and the `package-lock.json`
Build: https://ci.earthdata.nasa.gov/browse/CN2-BN2617-2
=> CMR-9542: Snyk Vulnerability, Browse Scaler : Axios

search-app/docs/api.md
Update CMR temporal search documentation to include "between Julian days x,y"
=> CMR-9554: update temporal search documentation.

.gitignore, access-control-app/int-test/cmr/access_control/int_test/access_control_group_crud_test.clj, schema-validation-lib/project.clj, system-int-test/test/cmr/system_int_test/search/tagging/tag_association_test.clj
updated everit/json to new version in schema-validation-lib
=> CMR-9525: Resolve Snyk Vulnerability (multiple project impact) - Allocation of Resources Without Limits or Throttling

browse-scaler/src/package-lock.json
let npm audit fix update the Bable library
=> CMR-9562 - doing an npm fix in browse scaler

access-control-app/src/cmr/access_control/services/acl_search_service.clj, access-control-app/src/cmr/access_control/services/acl_service.clj
There was a new path I found where the parameter in question was accepting the removed property, this change removes that one as well.
=> CMR-9508 - Adding a correction discovered while testing

common-app-lib/src/cmr/common_app/data/search/collection_for_gran_acls_caches.clj
Fixing collections for gran acls cache refresh error
=> CMR-9589: fix fetching all collections call

browse-scaler/src/package-lock.json, browse-scaler/src/package.json
Fixes an issue being reported by snyk (we need to fix this though we do plan to retire this application)
Regression tested locally
=> CMR-9668: Browse-scaler - Snyk scan (Prototype Pollution)

ingest-app/src/cmr/ingest/api/generic_documents.clj, system-int-test/src/cmr/system_int_test/utils/generic_util.clj, system-int-test/test/cmr/system_int_test/ingest/generics_test.clj
This is for Generic Document only.
=> CMR-9411: Added checking of the version in Content-Type.

dev-system/Dockerfile.java17.builder
Temp PR, IGNORE if you are not John Teague
=> For John Teague Only -- do not merge

site-templates/resources/templates/structure.html
Added DAP tracking code to CMR site template file
Added DAP tracking code to CMR site template file
Added DAP tracking code to CMR site template file
cmr.earthdata.nasa.gov
=> CMR-9763: Install DAP tracking code onto cmr.earthdata.nasa.gov to comply with Agency requirements

CONTRIBUTING.md, README.md
Following the README to setup CMR was confusing, I went through the process and made any relevant updates as well as removed unnecessary steps that were causing confusion.
=> CMR-9694: Updates the README

umm-lib/resources/schema/echo10/Collection.xsd, umm-lib/resources/schema/echo10/MetadataCommon.xsd, umm-spec-lib/resources/example-data/echo10/ecse-1475.xml, umm-spec-lib/resources/xml-schemas/echo10/Collection.xsd, umm-spec-lib/resources/xml-schemas/echo10/MetadataCommon.xsd, umm-spec-lib/src/cmr/umm_spec/test/echo10_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/echo10.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/echo10.clj, umm-spec-lib/test/cmr/umm_spec/test/generate_and_parse.clj
=> CMR-9753: Added translation and tests between UMM-C and Echo10.

umm-lib/resources/schema/dif10/UmmCommon_1.2.xsd, umm-lib/resources/schema/dif10/dif_v10.2.xsd, umm-spec-lib/resources/example-data/dif10/ecse-1474.xml, umm-spec-lib/resources/xml-schemas/dif10/UmmCommon_1.2.xsd, umm-spec-lib/resources/xml-schemas/dif10/dif_v10.2.xsd, umm-spec-lib/src/cmr/umm_spec/test/dif10_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/echo10_expected_conversion.clj, umm-spec-lib/src/cmr/umm_spec/test/expected_conversion_util.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/dif10.clj, umm-spec-lib/src/cmr/umm_spec/umm_to_xml_mappings/dif10/spatial.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/dif10.clj, umm-spec-lib/src/cmr/umm_spec/xml_to_umm_mappings/dif10/spatial.clj, umm-spec-lib/test/cmr/umm_spec/test/generate_and_parse.clj, umm-spec-lib/test/cmr/umm_spec/test/xml_to_umm_mappings/dif10.clj
=> CMR-9754: Added dif10 translation for UMM-C 1.18

system-validation-test/Gemfile.lock
updating nokogiri library.
updating nokogiri library.
system-validation-test
- [ x] I have updated/added unit and integration tests that prove my fix is effective or that my feature works
- [ x] New and existing unit and int tests pass locally and remotely with my changes
- [ x] I have removed unnecessary/dead code and imports in files I have changed
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
=> CMR-9862: updating nokogiri library.

.github/pull_request_template.md
We have decided to do int test clean up slowly over time amongst PR's
Adding new step to PR template
N/A
=> pr-template-int-test-update

transmit-lib/src/cmr/transmit/urs.clj
adding a try catch block when EDL goes down and the CMR cannot parse the result.
adding a try catch block when EDL goes down and the CMR cannot parse the result.
transmit-lib/src/cmr/transmit/urs.clj
=> CMR-10086: Catching an exception if Earthdata Login goes down and the result is not what is expected.

metadata-db-app/int-test/cmr/metadata_db/int_test/utility.clj, metadata-db-app/src/cmr/metadata_db/services/sub_notifications.clj, system-int-test/test/cmr/system_int_test/ingest/subscription/subscription_processing_test.clj
Fixing broken build
Fixing broken build
Subscription
=> CMR-10141-1: Fixing broken build

metadata-db-app/src/cmr/metadata_db/data/oracle/concepts/subscription.clj
Fixing deleting subscription bug.
Fixing deleting subscription bug.
Fixing deleting subscription bug.
=> CMR-10141-2: Fixing deleting subscription bug.

ingest-app/docs/api.md, search-app/docs/api.md
The nested lists in the ingest and search api docs were not correct.
Add html list tags
Ingest and Search API Docs
=> CMR-10257: [Fix 2] Fix formatting issues on nested list in docs

umm-spec-lib/resources/json-schemas/variable/umm/v1.9.0/umm-var-json-schema.json, umm-spec-lib/src/cmr/umm_spec/migration/version/variable.clj, umm-spec-lib/test/cmr/umm_spec/test/migration/version/variable.clj
Small schema change to expand the size of a field in UMM-Var
- [-] I have updated/added unit and int tests that prove my fix is effective or that my feature works
- [-] clj-kondo has been run locally and all errors corrected
- [-] I have removed unnecessary/dead code and imports in files I have changed
- [-] I have commented my code, particularly in hard-to-understand areas
- [-] My changes generate no new warnings
- refactored to reduce number of system state resets by updating fixtures …
=> CMR-10458: fill value

.github/pull_request_template.md
To update the pr template. (This was not linked to any ticket)
Separate out check list
=> CMR-X: Update pr template
